import { GraphServiceClient } from "../mail/graphServiceClient";
import { FetchRequestAdapter } from "@microsoft/kiota-http-fetchlibrary";
import { Message } from "../mail/models/microsoft/graph/message";
import { ItemBody } from "../mail/models/microsoft/graph/itemBody";

import { SimpleAuthenticationProvider } from "@microsoft/microsoft-graph-client"

const token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IlFiNTNyYzZuWVgtMjlGWS1WSHZMRk1fZXlPQVZneEhFVWhZYXhvWmIydDAiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCIsImtpZCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNGNjN2E0Mi0zYzQ0LTQ0ZjMtYWFmMy02NjYzMDJhZWFiMDgvIiwiaWF0IjoxNjQ0MzQyMzczLCJuYmYiOjE2NDQzNDIzNzMsImV4cCI6MTY0NDM0Njk1MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZQWk1TmtlbXRUYm1XYXYyeFk2S1l6dVh0ODlLdHZscUVyWEwwS2JjanNVemFENEEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkNoZXR0aWFyIiwiZ2l2ZW5fbmFtZSI6ImUyMzkxYiIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjczLjE2OS4xNDguNzIiLCJuYW1lIjoiTmlraXRoYSBVZGF5a3VtYXIgQ2hldHRpYXIiLCJvaWQiOiI4MTM5NTZhMy00YTMwLTQ1OTYtOTE0Zi1iZmQ4NmE2NTdhMDkiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDBEMjg0RkFDQSIsInB3ZF9leHAiOiIwIiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInJoIjoiMC5BVmtBUW5yTTFFUTg4MFNxODJaakFxNnJDQU1BQUFBQUFBQUF3QUFBQUFBQUFBQlpBQlUuIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBDb250YWN0cy5SZWFkIENvbnRhY3RzLlJlYWRXcml0ZSBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRW50aXRsZW1lbnRNYW5hZ2VtZW50LlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZCBGaWxlcy5SZWFkLkFsbCBGaWxlcy5SZWFkV3JpdGUgRmlsZXMuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIE1haWwuUmVhZCBNYWlsLlJlYWQuU2hhcmVkIE1haWwuUmVhZEJhc2ljIE1haWwuUmVhZFdyaXRlIE1haWwuUmVhZFdyaXRlLlNoYXJlZCBNYWlsLlNlbmQgTWFpbGJveFNldHRpbmdzLlJlYWRXcml0ZSBOb3Rlcy5DcmVhdGUgTm90ZXMuUmVhZCBOb3Rlcy5SZWFkLkFsbCBOb3Rlcy5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgT3JnQ29udGFjdC5SZWFkLkFsbCBQZW9wbGUuUmVhZCBQZW9wbGUuUmVhZC5BbGwgUHJpbnRlci5GdWxsQ29udHJvbC5BbGwgUHJpbnRlci5SZWFkLkFsbCBQcmludGVyLlJlYWRXcml0ZS5BbGwgUHJpbnRlclNoYXJlLlJlYWQuQWxsIFByaW50ZXJTaGFyZS5SZWFkV3JpdGUuQWxsIHByb2ZpbGUgUmVwb3J0cy5SZWFkLkFsbCBTaXRlcy5GdWxsQ29udHJvbC5BbGwgU2l0ZXMuTWFuYWdlLkFsbCBTaXRlcy5SZWFkLkFsbCBTaXRlcy5SZWFkV3JpdGUuQWxsIFRhc2tzLlJlYWQgVGFza3MuUmVhZC5TaGFyZWQgVGFza3MuUmVhZFdyaXRlIFRhc2tzLlJlYWRXcml0ZS5TaGFyZWQgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoidG9waDEyYUVZMlpXOHdvczNZNjFpWlcyajlpNTVPa2tMWWRBT09idFpIcyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6ImQ0Y2M3YTQyLTNjNDQtNDRmMy1hYWYzLTY2NjMwMmFlYWIwOCIsInVuaXF1ZV9uYW1lIjoibmNoZXR0aWFAZ3JhcGhqc2RlbW8ub25taWNyb3NvZnQuY29tIiwidXBuIjoibmNoZXR0aWFAZ3JhcGhqc2RlbW8ub25taWNyb3NvZnQuY29tIiwidXRpIjoiQ21Gbm5CQU80RVdHTWExbTJKbEZBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJNWkJUSUFQQWNLUTRPSkxuREdzRW5EZHoxNkFzNmZFLTJ0NWVfLTZDdVRJIn0sInhtc190Y2R0IjoxNTk1NTM0ODMxfQ.UNGpBuw0RxP9g0T-ywDQ0Ce-xQyAnU9Q89eaEMFz7d6LSdCUr5zM1mL1uHoSFTNEOKRP2k3wMBgrc14rgC5f4uHjNevtKaCGOnlduk2gObund93OCw5FoK2XrljXesxSJX7byyZezMMKONNTwVViHqIWX_oHq_2rS7zZkhTzABTTm_YndGt_fFzAFIqKnVuH3Weu_91BpXH4Qt1dw1hQPs1vyqlmzrdc2dWfj1-COSm9HseXlKu-i78QMnMyfljsz7RQp24Px-6nB-QeEvY0LZUbbpauexuCfv7qIL5OjJv6mzhgFgwzx9SUCeOLjdUarJxNxMhSutMwxZOm0Sjjtg";

const simpleAuthenticationProvider = new SimpleAuthenticationProvider({getAccessTokenCallback:async () => { return token;}});

const core = new FetchRequestAdapter(simpleAuthenticationProvider);
const client = new GraphServiceClient(core);

async function getMessage() {
    // GET /users/{id | userPrincipalName}/messages
    const userRequestBuilder = client.usersById("813956a3-4a30-4596-914f-bfd86a657a09");
    const messageRequestBuilder = userRequestBuilder.messages;
    const message = await messageRequestBuilder.get();
    console.log(message.value);
}

getMessage().catch((e) => console.log(e));


async function post() {
    // GET /users/{id | userPrincipalName}/messages
    const userRequestBuilder = client.usersById("813956a3-4a30-4596-914f-bfd86a657a09");
    const messagesRequestBuilder = userRequestBuilder.messages;
    const message = new Message();
    message.subject = "test subject";
    const itemBody: ItemBody = new ItemBody();
   // itemBody.content = JSON.stringify({});
    const post = await messagesRequestBuilder.post(message);


    console.log((await (post)).subject);
}
