import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation113, operation114, operation115, operation116, operation117, operation118, operation119, operation120, operation121, operation122, operation4918, operation4919, operation4920, operation4921, operation4922, operation4923, operation4924, operation4925, operation4926, operation4927, operation4928, operation4929, operation4930, operation4931, operation4932, operation4933, operation4934, operation4935, operation4936, operation4937, operation4938, operation4939, operation4940, operation4941, operation4942, operation4943, operation4944, operation4945, operation4946, operation4947, operation4948, operation4949, operation4950, operation4951, operation4952, operation4953, operation4954, operation4955, operation4956, operation4957, operation4958, operation4959, operation4960, operation4961, operation4962, operation4963, operation4964, operation4965, operation4966, operation4967, operation4968, operation4969, operation4970, operation4971, operation4972, operation4973, operation4974, operation4975, operation4976, operation4977, operation4978, operation4979, operation4980, operation4981, operation4982, operation4983, operation4984, operation4985, operation4986, operation4987, operation4988, operation4989, operation4990, operation4991, operation4992, operation4993, operation4994, operation4995, operation4996, operation4997, operation4998, operation4999, operation5000, operation5001, operation5002, operation5003, operation5004, operation5005, operation5006, operation5007, operation5008, operation5009, operation5010, operation5011, operation5012, operation5013, operation5014, operation5015, operation5016, operation5017, operation5018, operation5019, operation5020, operation5021, operation5022 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/reports"):operation4918,
        (api:"/reports/dailyPrintUsageByPrinter"):operation4919,
        (api:"/reports/dailyPrintUsageByPrinter/{printUsageByPrinter-id}",printUsageByPrinterid: string):operation4920,
        (api:"/reports/dailyPrintUsageByPrinter/$count"):operation4921,
        (api:"/reports/dailyPrintUsageByUser"):operation4922,
        (api:"/reports/dailyPrintUsageByUser/{printUsageByUser-id}",printUsageByUserid: string):operation4923,
        (api:"/reports/dailyPrintUsageByUser/$count"):operation4924,
        (api:"/reports/microsoft.graph.deviceConfigurationDeviceActivity()"):operation4925,
        (api:"/reports/microsoft.graph.deviceConfigurationUserActivity()"):operation4926,
        (api:"/reports/microsoft.graph.getEmailActivityCounts(period='{period}')",period: string):operation4927,
        (api:"/reports/microsoft.graph.getEmailActivityUserCounts(period='{period}')",period: string):operation4928,
        (api:"/reports/microsoft.graph.getEmailActivityUserDetail(date={date})",date: string):operation4929,
        (api:"/reports/microsoft.graph.getEmailActivityUserDetail(period='{period}')",period: string):operation4930,
        (api:"/reports/microsoft.graph.getEmailAppUsageAppsUserCounts(period='{period}')",period: string):operation4931,
        (api:"/reports/microsoft.graph.getEmailAppUsageUserCounts(period='{period}')",period: string):operation4932,
        (api:"/reports/microsoft.graph.getEmailAppUsageUserDetail(date={date})",date: string):operation4933,
        (api:"/reports/microsoft.graph.getEmailAppUsageUserDetail(period='{period}')",period: string):operation4934,
        (api:"/reports/microsoft.graph.getEmailAppUsageVersionsUserCounts(period='{period}')",period: string):operation4935,
        (api:"/reports/microsoft.graph.getGroupArchivedPrintJobs(groupId='{groupId}',startDateTime='{startDateTime}',endDateTime='{endDateTime}')",groupId: string,startDateTime: string,endDateTime: string):operation4936,
        (api:"/reports/microsoft.graph.getMailboxUsageDetail(period='{period}')",period: string):operation4937,
        (api:"/reports/microsoft.graph.getMailboxUsageMailboxCounts(period='{period}')",period: string):operation4938,
        (api:"/reports/microsoft.graph.getMailboxUsageQuotaStatusMailboxCounts(period='{period}')",period: string):operation4939,
        (api:"/reports/microsoft.graph.getMailboxUsageStorage(period='{period}')",period: string):operation4940,
        (api:"/reports/microsoft.graph.getOffice365ActivationCounts()"):operation4941,
        (api:"/reports/microsoft.graph.getOffice365ActivationsUserCounts()"):operation4942,
        (api:"/reports/microsoft.graph.getOffice365ActivationsUserDetail()"):operation4943,
        (api:"/reports/microsoft.graph.getOffice365ActiveUserCounts(period='{period}')",period: string):operation4944,
        (api:"/reports/microsoft.graph.getOffice365ActiveUserDetail(date={date})",date: string):operation4945,
        (api:"/reports/microsoft.graph.getOffice365ActiveUserDetail(period='{period}')",period: string):operation4946,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityCounts(period='{period}')",period: string):operation4947,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityDetail(date={date})",date: string):operation4948,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityDetail(period='{period}')",period: string):operation4949,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityFileCounts(period='{period}')",period: string):operation4950,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityGroupCounts(period='{period}')",period: string):operation4951,
        (api:"/reports/microsoft.graph.getOffice365GroupsActivityStorage(period='{period}')",period: string):operation4952,
        (api:"/reports/microsoft.graph.getOffice365ServicesUserCounts(period='{period}')",period: string):operation4953,
        (api:"/reports/microsoft.graph.getOneDriveActivityFileCounts(period='{period}')",period: string):operation4954,
        (api:"/reports/microsoft.graph.getOneDriveActivityUserCounts(period='{period}')",period: string):operation4955,
        (api:"/reports/microsoft.graph.getOneDriveActivityUserDetail(date={date})",date: string):operation4956,
        (api:"/reports/microsoft.graph.getOneDriveActivityUserDetail(period='{period}')",period: string):operation4957,
        (api:"/reports/microsoft.graph.getOneDriveUsageAccountCounts(period='{period}')",period: string):operation4958,
        (api:"/reports/microsoft.graph.getOneDriveUsageAccountDetail(date={date})",date: string):operation4959,
        (api:"/reports/microsoft.graph.getOneDriveUsageAccountDetail(period='{period}')",period: string):operation4960,
        (api:"/reports/microsoft.graph.getOneDriveUsageFileCounts(period='{period}')",period: string):operation4961,
        (api:"/reports/microsoft.graph.getOneDriveUsageStorage(period='{period}')",period: string):operation4962,
        (api:"/reports/microsoft.graph.getPrinterArchivedPrintJobs(printerId='{printerId}',startDateTime='{startDateTime}',endDateTime='{endDateTime}')",printerId: string,startDateTime: string,endDateTime: string):operation4963,
        (api:"/reports/microsoft.graph.getSharePointActivityFileCounts(period='{period}')",period: string):operation4964,
        (api:"/reports/microsoft.graph.getSharePointActivityPages(period='{period}')",period: string):operation4965,
        (api:"/reports/microsoft.graph.getSharePointActivityUserCounts(period='{period}')",period: string):operation4966,
        (api:"/reports/microsoft.graph.getSharePointActivityUserDetail(date={date})",date: string):operation4967,
        (api:"/reports/microsoft.graph.getSharePointActivityUserDetail(period='{period}')",period: string):operation4968,
        (api:"/reports/microsoft.graph.getSharePointSiteUsageDetail(date={date})",date: string):operation4969,
        (api:"/reports/microsoft.graph.getSharePointSiteUsageDetail(period='{period}')",period: string):operation4970,
        (api:"/reports/microsoft.graph.getSharePointSiteUsageFileCounts(period='{period}')",period: string):operation4971,
        (api:"/reports/microsoft.graph.getSharePointSiteUsagePages(period='{period}')",period: string):operation4972,
        (api:"/reports/microsoft.graph.getSharePointSiteUsageSiteCounts(period='{period}')",period: string):operation4973,
        (api:"/reports/microsoft.graph.getSharePointSiteUsageStorage(period='{period}')",period: string):operation4974,
        (api:"/reports/microsoft.graph.getSkypeForBusinessActivityCounts(period='{period}')",period: string):operation4975,
        (api:"/reports/microsoft.graph.getSkypeForBusinessActivityUserCounts(period='{period}')",period: string):operation4976,
        (api:"/reports/microsoft.graph.getSkypeForBusinessActivityUserDetail(date={date})",date: string):operation4977,
        (api:"/reports/microsoft.graph.getSkypeForBusinessActivityUserDetail(period='{period}')",period: string):operation4978,
        (api:"/reports/microsoft.graph.getSkypeForBusinessDeviceUsageDistributionUserCounts(period='{period}')",period: string):operation4979,
        (api:"/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserCounts(period='{period}')",period: string):operation4980,
        (api:"/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserDetail(date={date})",date: string):operation4981,
        (api:"/reports/microsoft.graph.getSkypeForBusinessDeviceUsageUserDetail(period='{period}')",period: string):operation4982,
        (api:"/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityCounts(period='{period}')",period: string):operation4983,
        (api:"/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityMinuteCounts(period='{period}')",period: string):operation4984,
        (api:"/reports/microsoft.graph.getSkypeForBusinessOrganizerActivityUserCounts(period='{period}')",period: string):operation4985,
        (api:"/reports/microsoft.graph.getSkypeForBusinessParticipantActivityCounts(period='{period}')",period: string):operation4986,
        (api:"/reports/microsoft.graph.getSkypeForBusinessParticipantActivityMinuteCounts(period='{period}')",period: string):operation4987,
        (api:"/reports/microsoft.graph.getSkypeForBusinessParticipantActivityUserCounts(period='{period}')",period: string):operation4988,
        (api:"/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityCounts(period='{period}')",period: string):operation4989,
        (api:"/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityMinuteCounts(period='{period}')",period: string):operation4990,
        (api:"/reports/microsoft.graph.getSkypeForBusinessPeerToPeerActivityUserCounts(period='{period}')",period: string):operation4991,
        (api:"/reports/microsoft.graph.getTeamsDeviceUsageDistributionUserCounts(period='{period}')",period: string):operation4992,
        (api:"/reports/microsoft.graph.getTeamsDeviceUsageUserCounts(period='{period}')",period: string):operation4993,
        (api:"/reports/microsoft.graph.getTeamsDeviceUsageUserDetail(date={date})",date: string):operation4994,
        (api:"/reports/microsoft.graph.getTeamsDeviceUsageUserDetail(period='{period}')",period: string):operation4995,
        (api:"/reports/microsoft.graph.getTeamsUserActivityCounts(period='{period}')",period: string):operation4996,
        (api:"/reports/microsoft.graph.getTeamsUserActivityUserCounts(period='{period}')",period: string):operation4997,
        (api:"/reports/microsoft.graph.getTeamsUserActivityUserDetail(date={date})",date: string):operation4998,
        (api:"/reports/microsoft.graph.getTeamsUserActivityUserDetail(period='{period}')",period: string):operation4999,
        (api:"/reports/microsoft.graph.getUserArchivedPrintJobs(userId='{userId}',startDateTime='{startDateTime}',endDateTime='{endDateTime}')",userId: string,startDateTime: string,endDateTime: string):operation5000,
        (api:"/reports/microsoft.graph.getYammerActivityCounts(period='{period}')",period: string):operation5001,
        (api:"/reports/microsoft.graph.getYammerActivityUserCounts(period='{period}')",period: string):operation5002,
        (api:"/reports/microsoft.graph.getYammerActivityUserDetail(date={date})",date: string):operation5003,
        (api:"/reports/microsoft.graph.getYammerActivityUserDetail(period='{period}')",period: string):operation5004,
        (api:"/reports/microsoft.graph.getYammerDeviceUsageDistributionUserCounts(period='{period}')",period: string):operation5005,
        (api:"/reports/microsoft.graph.getYammerDeviceUsageUserCounts(period='{period}')",period: string):operation5006,
        (api:"/reports/microsoft.graph.getYammerDeviceUsageUserDetail(date={date})",date: string):operation5007,
        (api:"/reports/microsoft.graph.getYammerDeviceUsageUserDetail(period='{period}')",period: string):operation5008,
        (api:"/reports/microsoft.graph.getYammerGroupsActivityCounts(period='{period}')",period: string):operation5009,
        (api:"/reports/microsoft.graph.getYammerGroupsActivityDetail(date={date})",date: string):operation5010,
        (api:"/reports/microsoft.graph.getYammerGroupsActivityDetail(period='{period}')",period: string):operation5011,
        (api:"/reports/microsoft.graph.getYammerGroupsActivityGroupCounts(period='{period}')",period: string):operation5012,
        (api:"/reports/microsoft.graph.managedDeviceEnrollmentFailureDetails()"):operation5013,
        (api:"/reports/microsoft.graph.managedDeviceEnrollmentFailureDetails(skip={skip},top={top},filter='{filter}',skipToken='{skipToken}')",skip: string,top: string,filter: string,skipToken: string):operation5014,
        (api:"/reports/microsoft.graph.managedDeviceEnrollmentTopFailures()"):operation5015,
        (api:"/reports/microsoft.graph.managedDeviceEnrollmentTopFailures(period='{period}')",period: string):operation5016,
        (api:"/reports/monthlyPrintUsageByPrinter"):operation5017,
        (api:"/reports/monthlyPrintUsageByPrinter/{printUsageByPrinter-id}",printUsageByPrinterid: string):operation5018,
        (api:"/reports/monthlyPrintUsageByPrinter/$count"):operation5019,
        (api:"/reports/monthlyPrintUsageByUser"):operation5020,
        (api:"/reports/monthlyPrintUsageByUser/{printUsageByUser-id}",printUsageByUserid: string):operation5021,
        (api:"/reports/monthlyPrintUsageByUser/$count"):operation5022,
        (api:"/auditLogs"):operation113,
        (api:"/auditLogs/directoryAudits"):operation114,
        (api:"/auditLogs/directoryAudits/{directoryAudit-id}",directoryAuditid: string):operation115,
        (api:"/auditLogs/directoryAudits/$count"):operation116,
        (api:"/auditLogs/provisioning"):operation117,
        (api:"/auditLogs/provisioning/{provisioningObjectSummary-id}",provisioningObjectSummaryid: string):operation118,
        (api:"/auditLogs/provisioning/$count"):operation119,
        (api:"/auditLogs/signIns"):operation120,
        (api:"/auditLogs/signIns/{signIn-id}",signInid: string):operation121,
        (api:"/auditLogs/signIns/$count"):operation122,
    }
}

export {};