import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation143, operation144, operation145, operation146, operation147, operation148, operation149, operation150, operation151, operation152, operation153, operation154, operation155, operation156, operation157, operation158, operation159, operation160, operation161, operation162, operation163, operation164, operation165, operation166, operation167, operation168, operation169, operation170, operation171, operation172, operation173, operation174, operation175, operation176, operation177, operation178, operation179, operation180, operation181, operation182, operation183, operation184, operation185, operation186, operation187, operation188, operation189, operation190, operation191, operation192, operation193, operation194, operation195, operation196, operation197, operation198, operation199, operation200, operation201, operation202, operation203, operation204, operation205, operation206, operation207, operation208, operation209, operation210, operation211, operation212, operation213, operation214, operation215, operation216, operation217, operation218, operation219, operation220, operation221, operation222, operation223, operation224, operation225, operation226, operation227, operation228, operation229, operation230, operation231, operation232, operation233, operation234, operation235, operation236, operation237, operation238, operation239, operation240, operation3738, operation3739, operation3740, operation3741, operation3742, operation3743, operation3744, operation3745, operation3746, operation3747, operation3748, operation3749, operation3750, operation3751, operation3752, operation3753, operation3754, operation3755, operation3756, operation3757, operation3758, operation3759, operation3760, operation3761, operation3762, operation3763, operation3764, operation3765, operation3766, operation3767, operation3768, operation3769, operation3770, operation3771, operation3772, operation3773, operation3774, operation6003, operation6004, operation6005, operation6006, operation6007, operation6008, operation6009, operation6010, operation6011, operation6012, operation6013, operation6014, operation6015, operation6016, operation6017, operation6018, operation6019, operation6020, operation6021, operation6022, operation6023, operation6024, operation6025, operation6026, operation6027, operation6028, operation6029, operation6030, operation6031, operation6032, operation6033, operation6034, operation6035, operation6036, operation6037, operation6038, operation6039, operation6040, operation6041, operation6042, operation6043, operation6044, operation6045, operation6046, operation6047, operation6048, operation6049, operation6050, operation6051, operation6052, operation6053, operation6054, operation6055, operation6056, operation6057, operation6058, operation6059, operation6060, operation6061, operation6062, operation6063, operation6064, operation6065, operation6066, operation6067, operation6068, operation6069, operation6070, operation6071, operation6072, operation6073, operation6074, operation6075, operation6076, operation6077, operation6078, operation6079, operation6080, operation6081, operation6082, operation6083, operation6084, operation6085, operation6086, operation6087, operation6088, operation6089, operation6090, operation6091, operation6092, operation6093, operation6094, operation6095, operation6096, operation6097, operation6098, operation6099, operation6100, operation6101, operation6102, operation6103, operation6104, operation6105, operation6106, operation6107, operation6108, operation6109, operation6110, operation6111, operation6112, operation6113, operation6114, operation6115, operation6116, operation6117, operation6118, operation6119, operation6120, operation6121, operation6122, operation6123, operation6124, operation6125, operation6126, operation6127, operation6128, operation6129, operation6130, operation6131, operation6132, operation6133, operation6134, operation6135, operation6136, operation6137, operation6138, operation6139, operation6140, operation6141, operation6142, operation6143, operation6751, operation6752, operation6753, operation6754, operation6755, operation6756, operation6757, operation6758, operation6759, operation6760, operation6761, operation6762, operation6763, operation6764, operation6765, operation6766, operation6767, operation6768, operation6769, operation6770, operation6771, operation6772, operation6773, operation6774, operation6775, operation6776, operation6777, operation6778, operation6779, operation6780, operation6781, operation6782, operation6783, operation6784, operation6785, operation6786, operation6787, operation7132, operation7133, operation7134, operation7135, operation7136, operation7137, operation7138, operation7139, operation7140, operation7141, operation7142, operation7143, operation7144, operation7145, operation7146, operation7147, operation7148, operation7149, operation7150, operation7151, operation7152, operation7153, operation7154, operation7155, operation7156, operation7157, operation7158, operation7159, operation7160, operation7161, operation7162, operation7163, operation7164, operation7165, operation7166, operation7167, operation7168, operation7169, operation7170, operation7171, operation7172, operation7173, operation7174, operation7175, operation7176, operation7177, operation7178, operation7179, operation7180, operation7181, operation7182, operation7183, operation7184, operation7185, operation7186, operation7187, operation7188, operation7189, operation7190, operation7191, operation7192, operation7193, operation7194, operation7195, operation7196, operation7197, operation7198, operation7199, operation7200, operation7201, operation7202, operation7203, operation7204, operation7205, operation7206, operation7207, operation7208, operation7209, operation7210, operation7211, operation7212, operation7213, operation7214, operation7215, operation7216, operation7217, operation7218, operation7219, operation7220, operation7221, operation7222, operation7223, operation7224, operation7225, operation7226, operation7227, operation7228, operation7229, operation7230, operation7231, operation7232, operation7233, operation7234, operation7235, operation7236, operation7237, operation7238, operation7239, operation7240, operation7241, operation7242, operation7243, operation7244, operation7245, operation7246, operation7247, operation7248, operation7249, operation7250, operation7251, operation7252, operation7253, operation7254, operation7255, operation7256, operation7257, operation7258, operation7259, operation7260, operation7261, operation7262, operation7263, operation7264, operation7265 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/teams"):operation6003,
        (api:"/teams/{team-id}",teamid: string):operation6004,
        (api:"/teams/{team-id}/allChannels",teamid: string):operation6005,
        (api:"/teams/{team-id}/allChannels/{channel-id}",teamid: string,channelid: string):operation6006,
        (api:"/teams/{team-id}/allChannels/$count",teamid: string):operation6007,
        (api:"/teams/{team-id}/channels",teamid: string):operation6008,
        (api:"/teams/{team-id}/channels/{channel-id}",teamid: string,channelid: string):operation6009,
        (api:"/teams/{team-id}/channels/{channel-id}/filesFolder",teamid: string,channelid: string):operation6010,
        (api:"/teams/{team-id}/channels/{channel-id}/filesFolder/content",teamid: string,channelid: string):operation6011,
        (api:"/teams/{team-id}/channels/{channel-id}/members",teamid: string,channelid: string):operation6012,
        (api:"/teams/{team-id}/channels/{channel-id}/members/{conversationMember-id}",teamid: string,channelid: string,conversationMemberid: string):operation6013,
        (api:"/teams/{team-id}/channels/{channel-id}/members/$count",teamid: string,channelid: string):operation6014,
        (api:"/teams/{team-id}/channels/{channel-id}/members/microsoft.graph.add",teamid: string,channelid: string):operation6015,
        (api:"/teams/{team-id}/channels/{channel-id}/messages",teamid: string,channelid: string):operation6016,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}",teamid: string,channelid: string,chatMessageid: string):operation6017,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents",teamid: string,channelid: string,chatMessageid: string):operation6018,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",teamid: string,channelid: string,chatMessageid: string,chatMessageHostedContentid: string):operation6019,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/$count",teamid: string,channelid: string,chatMessageid: string):operation6020,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies",teamid: string,channelid: string,chatMessageid: string):operation6021,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6022,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6023,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation6024,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation6025,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count",teamid: string,channelid: string,chatMessageid: string):operation6026,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",teamid: string,channelid: string,chatMessageid: string):operation6027,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/$count",teamid: string,channelid: string):operation6028,
        (api:"/teams/{team-id}/channels/{channel-id}/messages/microsoft.graph.delta()",teamid: string,channelid: string):operation6029,
        (api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.completeMigration",teamid: string,channelid: string):operation6030,
        (api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",teamid: string,channelid: string,userId: string,tenantId: string,userPrincipalName: string):operation6031,
        (api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.provisionEmail",teamid: string,channelid: string):operation6032,
        (api:"/teams/{team-id}/channels/{channel-id}/microsoft.graph.removeEmail",teamid: string,channelid: string):operation6033,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams",teamid: string,channelid: string):operation6034,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6035,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6036,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation6037,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation6038,
        (api:"/teams/{team-id}/channels/{channel-id}/sharedWithTeams/$count",teamid: string,channelid: string):operation6039,
        (api:"/teams/{team-id}/channels/{channel-id}/tabs",teamid: string,channelid: string):operation6040,
        (api:"/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}",teamid: string,channelid: string,teamsTabid: string):operation6041,
        (api:"/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}/teamsApp",teamid: string,channelid: string,teamsTabid: string):operation6042,
        (api:"/teams/{team-id}/channels/{channel-id}/tabs/$count",teamid: string,channelid: string):operation6043,
        (api:"/teams/{team-id}/channels/$count",teamid: string):operation6044,
        (api:"/teams/{team-id}/channels/microsoft.graph.getAllMessages()",teamid: string):operation6045,
        (api:"/teams/{team-id}/group",teamid: string):operation6046,
        (api:"/teams/{team-id}/incomingChannels",teamid: string):operation6047,
        (api:"/teams/{team-id}/incomingChannels/{channel-id}",teamid: string,channelid: string):operation6048,
        (api:"/teams/{team-id}/incomingChannels/$count",teamid: string):operation6049,
        (api:"/teams/{team-id}/installedApps",teamid: string):operation6050,
        (api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}",teamid: string,teamsAppInstallationid: string):operation6051,
        (api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",teamid: string,teamsAppInstallationid: string):operation6052,
        (api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsApp",teamid: string,teamsAppInstallationid: string):operation6053,
        (api:"/teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",teamid: string,teamsAppInstallationid: string):operation6054,
        (api:"/teams/{team-id}/installedApps/$count",teamid: string):operation6055,
        (api:"/teams/{team-id}/members",teamid: string):operation6056,
        (api:"/teams/{team-id}/members/{conversationMember-id}",teamid: string,conversationMemberid: string):operation6057,
        (api:"/teams/{team-id}/members/$count",teamid: string):operation6058,
        (api:"/teams/{team-id}/members/microsoft.graph.add",teamid: string):operation6059,
        (api:"/teams/{team-id}/microsoft.graph.archive",teamid: string):operation6060,
        (api:"/teams/{team-id}/microsoft.graph.clone",teamid: string):operation6061,
        (api:"/teams/{team-id}/microsoft.graph.completeMigration",teamid: string):operation6062,
        (api:"/teams/{team-id}/microsoft.graph.sendActivityNotification",teamid: string):operation6063,
        (api:"/teams/{team-id}/microsoft.graph.unarchive",teamid: string):operation6064,
        (api:"/teams/{team-id}/operations",teamid: string):operation6065,
        (api:"/teams/{team-id}/operations/{teamsAsyncOperation-id}",teamid: string,teamsAsyncOperationid: string):operation6066,
        (api:"/teams/{team-id}/operations/$count",teamid: string):operation6067,
        (api:"/teams/{team-id}/photo",teamid: string):operation6068,
        (api:"/teams/{team-id}/photo/$value",teamid: string):operation6069,
        (api:"/teams/{team-id}/primaryChannel",teamid: string):operation6070,
        (api:"/teams/{team-id}/primaryChannel/filesFolder",teamid: string):operation6071,
        (api:"/teams/{team-id}/primaryChannel/filesFolder/content",teamid: string):operation6072,
        (api:"/teams/{team-id}/primaryChannel/members",teamid: string):operation6073,
        (api:"/teams/{team-id}/primaryChannel/members/{conversationMember-id}",teamid: string,conversationMemberid: string):operation6074,
        (api:"/teams/{team-id}/primaryChannel/members/$count",teamid: string):operation6075,
        (api:"/teams/{team-id}/primaryChannel/members/microsoft.graph.add",teamid: string):operation6076,
        (api:"/teams/{team-id}/primaryChannel/messages",teamid: string):operation6077,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}",teamid: string,chatMessageid: string):operation6078,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents",teamid: string,chatMessageid: string):operation6079,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",teamid: string,chatMessageid: string,chatMessageHostedContentid: string):operation6080,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/$count",teamid: string,chatMessageid: string):operation6081,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies",teamid: string,chatMessageid: string):operation6082,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}",teamid: string,chatMessageid: string,chatMessageid1: string):operation6083,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",teamid: string,chatMessageid: string,chatMessageid1: string):operation6084,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",teamid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation6085,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",teamid: string,chatMessageid: string,chatMessageid1: string):operation6086,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/$count",teamid: string,chatMessageid: string):operation6087,
        (api:"/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/microsoft.graph.delta()",teamid: string,chatMessageid: string):operation6088,
        (api:"/teams/{team-id}/primaryChannel/messages/$count",teamid: string):operation6089,
        (api:"/teams/{team-id}/primaryChannel/messages/microsoft.graph.delta()",teamid: string):operation6090,
        (api:"/teams/{team-id}/primaryChannel/microsoft.graph.completeMigration",teamid: string):operation6091,
        (api:"/teams/{team-id}/primaryChannel/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",teamid: string,userId: string,tenantId: string,userPrincipalName: string):operation6092,
        (api:"/teams/{team-id}/primaryChannel/microsoft.graph.provisionEmail",teamid: string):operation6093,
        (api:"/teams/{team-id}/primaryChannel/microsoft.graph.removeEmail",teamid: string):operation6094,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams",teamid: string):operation6095,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}",teamid: string,sharedWithChannelTeamInfoid: string):operation6096,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",teamid: string,sharedWithChannelTeamInfoid: string):operation6097,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",teamid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation6098,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",teamid: string,sharedWithChannelTeamInfoid: string):operation6099,
        (api:"/teams/{team-id}/primaryChannel/sharedWithTeams/$count",teamid: string):operation6100,
        (api:"/teams/{team-id}/primaryChannel/tabs",teamid: string):operation6101,
        (api:"/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}",teamid: string,teamsTabid: string):operation6102,
        (api:"/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}/teamsApp",teamid: string,teamsTabid: string):operation6103,
        (api:"/teams/{team-id}/primaryChannel/tabs/$count",teamid: string):operation6104,
        (api:"/teams/{team-id}/schedule",teamid: string):operation6105,
        (api:"/teams/{team-id}/schedule/microsoft.graph.share",teamid: string):operation6106,
        (api:"/teams/{team-id}/schedule/offerShiftRequests",teamid: string):operation6107,
        (api:"/teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}",teamid: string,offerShiftRequestid: string):operation6108,
        (api:"/teams/{team-id}/schedule/offerShiftRequests/$count",teamid: string):operation6109,
        (api:"/teams/{team-id}/schedule/openShiftChangeRequests",teamid: string):operation6110,
        (api:"/teams/{team-id}/schedule/openShiftChangeRequests/{openShiftChangeRequest-id}",teamid: string,openShiftChangeRequestid: string):operation6111,
        (api:"/teams/{team-id}/schedule/openShiftChangeRequests/$count",teamid: string):operation6112,
        (api:"/teams/{team-id}/schedule/openShifts",teamid: string):operation6113,
        (api:"/teams/{team-id}/schedule/openShifts/{openShift-id}",teamid: string,openShiftid: string):operation6114,
        (api:"/teams/{team-id}/schedule/openShifts/$count",teamid: string):operation6115,
        (api:"/teams/{team-id}/schedule/schedulingGroups",teamid: string):operation6116,
        (api:"/teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}",teamid: string,schedulingGroupid: string):operation6117,
        (api:"/teams/{team-id}/schedule/schedulingGroups/$count",teamid: string):operation6118,
        (api:"/teams/{team-id}/schedule/shifts",teamid: string):operation6119,
        (api:"/teams/{team-id}/schedule/shifts/{shift-id}",teamid: string,shiftid: string):operation6120,
        (api:"/teams/{team-id}/schedule/shifts/$count",teamid: string):operation6121,
        (api:"/teams/{team-id}/schedule/swapShiftsChangeRequests",teamid: string):operation6122,
        (api:"/teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}",teamid: string,swapShiftsChangeRequestid: string):operation6123,
        (api:"/teams/{team-id}/schedule/swapShiftsChangeRequests/$count",teamid: string):operation6124,
        (api:"/teams/{team-id}/schedule/timeOffReasons",teamid: string):operation6125,
        (api:"/teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}",teamid: string,timeOffReasonid: string):operation6126,
        (api:"/teams/{team-id}/schedule/timeOffReasons/$count",teamid: string):operation6127,
        (api:"/teams/{team-id}/schedule/timeOffRequests",teamid: string):operation6128,
        (api:"/teams/{team-id}/schedule/timeOffRequests/{timeOffRequest-id}",teamid: string,timeOffRequestid: string):operation6129,
        (api:"/teams/{team-id}/schedule/timeOffRequests/$count",teamid: string):operation6130,
        (api:"/teams/{team-id}/schedule/timesOff",teamid: string):operation6131,
        (api:"/teams/{team-id}/schedule/timesOff/{timeOff-id}",teamid: string,timeOffid: string):operation6132,
        (api:"/teams/{team-id}/schedule/timesOff/$count",teamid: string):operation6133,
        (api:"/teams/{team-id}/template",teamid: string):operation6134,
        (api:"/teams/$count"):operation6135,
        (api:"/teams/microsoft.graph.getAllMessages()"):operation6136,
        (api:"/teamsTemplates"):operation6137,
        (api:"/teamsTemplates/{teamsTemplate-id}",teamsTemplateid: string):operation6138,
        (api:"/teamsTemplates/$count"):operation6139,
        (api:"/teamwork"):operation6140,
        (api:"/teamwork/workforceIntegrations"):operation6141,
        (api:"/teamwork/workforceIntegrations/{workforceIntegration-id}",workforceIntegrationid: string):operation6142,
        (api:"/teamwork/workforceIntegrations/$count"):operation6143,
        (api:"/communications"):operation180,
    (api:"/communications/callRecords"):operation181,
    (api:"/communications/callRecords/{callRecord-id}",callRecordid: string):operation182,
    (api:"/communications/callRecords/{callRecord-id}/sessions",callRecordid: string):operation183,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}",callRecordid: string,sessionid: string):operation184,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments",callRecordid: string,sessionid: string):operation185,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}",callRecordid: string,sessionid: string,segmentid: string):operation186,
    (api:"/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/$count",callRecordid: string,sessionid: string):operation187,
    (api:"/communications/callRecords/{callRecord-id}/sessions/$count",callRecordid: string):operation188,
    (api:"/communications/callRecords/$count"):operation189,
    (api:"/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime='{fromDateTime}',toDateTime='{toDateTime}')",fromDateTime: string,toDateTime: string):operation190,
    (api:"/communications/callRecords/microsoft.graph.callRecords.getPstnCalls(fromDateTime='{fromDateTime}',toDateTime='{toDateTime}')",fromDateTime: string,toDateTime: string):operation191,
    (api:"/communications/calls"):operation192,
    (api:"/communications/calls/{call-id}",callid: string):operation193,
    (api:"/communications/calls/{call-id}/audioRoutingGroups",callid: string):operation194,
    (api:"/communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}",callid: string,audioRoutingGroupid: string):operation195,
    (api:"/communications/calls/{call-id}/audioRoutingGroups/$count",callid: string):operation196,
    (api:"/communications/calls/{call-id}/microsoft.graph.answer",callid: string):operation197,
    (api:"/communications/calls/{call-id}/microsoft.graph.cancelMediaProcessing",callid: string):operation198,
    (api:"/communications/calls/{call-id}/microsoft.graph.changeScreenSharingRole",callid: string):operation199,
    (api:"/communications/calls/{call-id}/microsoft.graph.keepAlive",callid: string):operation200,
    (api:"/communications/calls/{call-id}/microsoft.graph.mute",callid: string):operation201,
    (api:"/communications/calls/{call-id}/microsoft.graph.playPrompt",callid: string):operation202,
    (api:"/communications/calls/{call-id}/microsoft.graph.recordResponse",callid: string):operation203,
    (api:"/communications/calls/{call-id}/microsoft.graph.redirect",callid: string):operation204,
    (api:"/communications/calls/{call-id}/microsoft.graph.reject",callid: string):operation205,
    (api:"/communications/calls/{call-id}/microsoft.graph.subscribeToTone",callid: string):operation206,
    (api:"/communications/calls/{call-id}/microsoft.graph.transfer",callid: string):operation207,
    (api:"/communications/calls/{call-id}/microsoft.graph.unmute",callid: string):operation208,
    (api:"/communications/calls/{call-id}/microsoft.graph.updateRecordingStatus",callid: string):operation209,
    (api:"/communications/calls/{call-id}/operations",callid: string):operation210,
    (api:"/communications/calls/{call-id}/operations/{commsOperation-id}",callid: string,commsOperationid: string):operation211,
    (api:"/communications/calls/{call-id}/operations/$count",callid: string):operation212,
    (api:"/communications/calls/{call-id}/participants",callid: string):operation213,
    (api:"/communications/calls/{call-id}/participants/{participant-id}",callid: string,participantid: string):operation214,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.mute",callid: string,participantid: string):operation215,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.startHoldMusic",callid: string,participantid: string):operation216,
    (api:"/communications/calls/{call-id}/participants/{participant-id}/microsoft.graph.stopHoldMusic",callid: string,participantid: string):operation217,
    (api:"/communications/calls/{call-id}/participants/$count",callid: string):operation218,
    (api:"/communications/calls/{call-id}/participants/microsoft.graph.invite",callid: string):operation219,
    (api:"/communications/calls/$count"):operation220,
    (api:"/communications/calls/microsoft.graph.logTeleconferenceDeviceQuality"):operation221,
    (api:"/communications/microsoft.graph.getPresencesByUserId"):operation222,
    (api:"/communications/onlineMeetings"):operation223,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}",onlineMeetingid: string):operation224,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports",onlineMeetingid: string):operation225,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}",onlineMeetingid: string,meetingAttendanceReportid: string):operation226,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords",onlineMeetingid: string,meetingAttendanceReportid: string):operation227,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/{attendanceRecord-id}",onlineMeetingid: string,meetingAttendanceReportid: string,attendanceRecordid: string):operation228,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/$count",onlineMeetingid: string,meetingAttendanceReportid: string):operation229,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/$count",onlineMeetingid: string):operation230,
    (api:"/communications/onlineMeetings/{onlineMeeting-id}/attendeeReport",onlineMeetingid: string):operation231,
    (api:"/communications/onlineMeetings/$count"):operation232,
    (api:"/communications/onlineMeetings/microsoft.graph.createOrGet"):operation233,
    (api:"/communications/presences"):operation234,
    (api:"/communications/presences/{presence-id}",presenceid: string):operation235,
    (api:"/communications/presences/{presence-id}/microsoft.graph.clearPresence",presenceid: string):operation236,
    (api:"/communications/presences/{presence-id}/microsoft.graph.clearUserPreferredPresence",presenceid: string):operation237,
    (api:"/communications/presences/{presence-id}/microsoft.graph.setPresence",presenceid: string):operation238,
    (api:"/communications/presences/{presence-id}/microsoft.graph.setUserPreferredPresence",presenceid: string):operation239,
    (api:"/communications/presences/$count"):operation240,
    
    (api:"/appCatalogs"):operation6048,
    (api:"/appCatalogs/teamsApps"):operation6049,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}",teamsAppid: string):operation6050,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions",teamsAppid: string):operation6051,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/{teamsAppDefinition-id}",teamsAppid: string,teamsAppDefinitionid: string):operation6052,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/{teamsAppDefinition-id}/bot",teamsAppid: string,teamsAppDefinitionid: string):operation6053,
    (api:"/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/$count",teamsAppid: string):operation6054,
    (api:"/appCatalogs/teamsApps/$count"):operation6055,
    (api:"/chats"):operation143,
    (api:"/chats/{chat-id}",chatid: string):operation144,
    (api:"/chats/{chat-id}/installedApps",chatid: string):operation145,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}",chatid: string,teamsAppInstallationid: string):operation146,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",chatid: string,teamsAppInstallationid: string):operation147,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsApp",chatid: string,teamsAppInstallationid: string):operation148,
    (api:"/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",chatid: string,teamsAppInstallationid: string):operation149,
    (api:"/chats/{chat-id}/installedApps/$count",chatid: string):operation150,
    (api:"/chats/{chat-id}/members",chatid: string):operation151,
    (api:"/chats/{chat-id}/members/{conversationMember-id}",chatid: string,conversationMemberid: string):operation152,
    (api:"/chats/{chat-id}/members/$count",chatid: string):operation153,
    (api:"/chats/{chat-id}/members/microsoft.graph.add",chatid: string):operation154,
    (api:"/chats/{chat-id}/messages",chatid: string):operation155,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}",chatid: string,chatMessageid: string):operation156,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents",chatid: string,chatMessageid: string):operation157,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageHostedContentid: string):operation158,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/$count",chatid: string,chatMessageid: string):operation159,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies",chatid: string,chatMessageid: string):operation160,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",chatid: string,chatMessageid: string,chatMessageid1: string):operation161,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",chatid: string,chatMessageid: string,chatMessageid1: string):operation162,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation163,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",chatid: string,chatMessageid: string,chatMessageid1: string):operation164,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/$count",chatid: string,chatMessageid: string):operation165,
    (api:"/chats/{chat-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",chatid: string,chatMessageid: string):operation166,
    (api:"/chats/{chat-id}/messages/$count",chatid: string):operation167,
    (api:"/chats/{chat-id}/messages/microsoft.graph.delta()",chatid: string):operation168,
    (api:"/chats/{chat-id}/microsoft.graph.sendActivityNotification",chatid: string):operation169,
    (api:"/chats/{chat-id}/pinnedMessages",chatid: string):operation170,
    (api:"/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}",chatid: string,pinnedChatMessageInfoid: string):operation171,
    (api:"/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}/message",chatid: string,pinnedChatMessageInfoid: string):operation172,
    (api:"/chats/{chat-id}/pinnedMessages/$count",chatid: string):operation173,
    (api:"/chats/{chat-id}/tabs",chatid: string):operation174,
    (api:"/chats/{chat-id}/tabs/{teamsTab-id}",chatid: string,teamsTabid: string):operation175,
    (api:"/chats/{chat-id}/tabs/{teamsTab-id}/teamsApp",chatid: string,teamsTabid: string):operation176,
    (api:"/chats/{chat-id}/tabs/$count",chatid: string):operation177,
    (api:"/chats/$count"):operation178,
    (api:"/chats/microsoft.graph.getAllMessages()"):operation179,
    (api:"/me/chats"):operation3738,
    (api:"/me/chats/{chat-id}",chatid: string):operation3739,
    (api:"/me/chats/{chat-id}/installedApps",chatid: string):operation3740,
    (api:"/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}",chatid: string,teamsAppInstallationid: string):operation3741,
    (api:"/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",chatid: string,teamsAppInstallationid: string):operation3742,
    (api:"/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsApp",chatid: string,teamsAppInstallationid: string):operation3743,
    (api:"/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",chatid: string,teamsAppInstallationid: string):operation3744,
    (api:"/me/chats/{chat-id}/installedApps/$count",chatid: string):operation3745,
    (api:"/me/chats/{chat-id}/members",chatid: string):operation3746,
    (api:"/me/chats/{chat-id}/members/{conversationMember-id}",chatid: string,conversationMemberid: string):operation3747,
    (api:"/me/chats/{chat-id}/members/$count",chatid: string):operation3748,
    (api:"/me/chats/{chat-id}/members/microsoft.graph.add",chatid: string):operation3749,
    (api:"/me/chats/{chat-id}/messages",chatid: string):operation3750,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}",chatid: string,chatMessageid: string):operation3751,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/hostedContents",chatid: string,chatMessageid: string):operation3752,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageHostedContentid: string):operation3753,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/$count",chatid: string,chatMessageid: string):operation3754,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies",chatid: string,chatMessageid: string):operation3755,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",chatid: string,chatMessageid: string,chatMessageid1: string):operation3756,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",chatid: string,chatMessageid: string,chatMessageid1: string):operation3757,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",chatid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation3758,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",chatid: string,chatMessageid: string,chatMessageid1: string):operation3759,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/$count",chatid: string,chatMessageid: string):operation3760,
    (api:"/me/chats/{chat-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",chatid: string,chatMessageid: string):operation3761,
    (api:"/me/chats/{chat-id}/messages/$count",chatid: string):operation3762,
    (api:"/me/chats/{chat-id}/messages/microsoft.graph.delta()",chatid: string):operation3763,
    (api:"/me/chats/{chat-id}/microsoft.graph.sendActivityNotification",chatid: string):operation3764,
    (api:"/me/chats/{chat-id}/pinnedMessages",chatid: string):operation3765,
    (api:"/me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}",chatid: string,pinnedChatMessageInfoid: string):operation3766,
    (api:"/me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}/message",chatid: string,pinnedChatMessageInfoid: string):operation3767,
    (api:"/me/chats/{chat-id}/pinnedMessages/$count",chatid: string):operation3768,
    (api:"/me/chats/{chat-id}/tabs",chatid: string):operation3769,
    (api:"/me/chats/{chat-id}/tabs/{teamsTab-id}",chatid: string,teamsTabid: string):operation3770,
    (api:"/me/chats/{chat-id}/tabs/{teamsTab-id}/teamsApp",chatid: string,teamsTabid: string):operation3771,
    (api:"/me/chats/{chat-id}/tabs/$count",chatid: string):operation3772,
    (api:"/me/chats/$count"):operation3773,
    (api:"/me/chats/microsoft.graph.getAllMessages()"):operation3774,
    (api:"/users/{user-id}/chats",userid: string):operation6751,
    (api:"/users/{user-id}/chats/{chat-id}",userid: string,chatid: string):operation6752,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps",userid: string,chatid: string):operation6753,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps/{teamsAppInstallation-id}",userid: string,chatid: string,teamsAppInstallationid: string):operation6754,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",userid: string,chatid: string,teamsAppInstallationid: string):operation6755,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsApp",userid: string,chatid: string,teamsAppInstallationid: string):operation6756,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",userid: string,chatid: string,teamsAppInstallationid: string):operation6757,
    (api:"/users/{user-id}/chats/{chat-id}/installedApps/$count",userid: string,chatid: string):operation6758,
    (api:"/users/{user-id}/chats/{chat-id}/members",userid: string,chatid: string):operation6759,
    (api:"/users/{user-id}/chats/{chat-id}/members/{conversationMember-id}",userid: string,chatid: string,conversationMemberid: string):operation6760,
    (api:"/users/{user-id}/chats/{chat-id}/members/$count",userid: string,chatid: string):operation6761,
    (api:"/users/{user-id}/chats/{chat-id}/members/microsoft.graph.add",userid: string,chatid: string):operation6762,
    (api:"/users/{user-id}/chats/{chat-id}/messages",userid: string,chatid: string):operation6763,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}",userid: string,chatid: string,chatMessageid: string):operation6764,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents",userid: string,chatid: string,chatMessageid: string):operation6765,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",userid: string,chatid: string,chatMessageid: string,chatMessageHostedContentid: string):operation6766,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/$count",userid: string,chatid: string,chatMessageid: string):operation6767,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies",userid: string,chatid: string,chatMessageid: string):operation6768,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",userid: string,chatid: string,chatMessageid: string,chatMessageid1: string):operation6769,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",userid: string,chatid: string,chatMessageid: string,chatMessageid1: string):operation6770,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",userid: string,chatid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation6771,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",userid: string,chatid: string,chatMessageid: string,chatMessageid1: string):operation6772,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/$count",userid: string,chatid: string,chatMessageid: string):operation6773,
    (api:"/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",userid: string,chatid: string,chatMessageid: string):operation6774,
    (api:"/users/{user-id}/chats/{chat-id}/messages/$count",userid: string,chatid: string):operation6775,
    (api:"/users/{user-id}/chats/{chat-id}/messages/microsoft.graph.delta()",userid: string,chatid: string):operation6776,
    (api:"/users/{user-id}/chats/{chat-id}/microsoft.graph.sendActivityNotification",userid: string,chatid: string):operation6777,
    (api:"/users/{user-id}/chats/{chat-id}/pinnedMessages",userid: string,chatid: string):operation6778,
    (api:"/users/{user-id}/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}",userid: string,chatid: string,pinnedChatMessageInfoid: string):operation6779,
    (api:"/users/{user-id}/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}/message",userid: string,chatid: string,pinnedChatMessageInfoid: string):operation6780,
    (api:"/users/{user-id}/chats/{chat-id}/pinnedMessages/$count",userid: string,chatid: string):operation6781,
    (api:"/users/{user-id}/chats/{chat-id}/tabs",userid: string,chatid: string):operation6782,
    (api:"/users/{user-id}/chats/{chat-id}/tabs/{teamsTab-id}",userid: string,chatid: string,teamsTabid: string):operation6783,
    (api:"/users/{user-id}/chats/{chat-id}/tabs/{teamsTab-id}/teamsApp",userid: string,chatid: string,teamsTabid: string):operation6784,
    (api:"/users/{user-id}/chats/{chat-id}/tabs/$count",userid: string,chatid: string):operation6785,
    (api:"/users/{user-id}/chats/$count",userid: string):operation6786,
    (api:"/users/{user-id}/chats/microsoft.graph.getAllMessages()",userid: string):operation6787,
    (api:"/users/{user-id}/joinedTeams",userid: string):operation7132,
    (api:"/users/{user-id}/joinedTeams/{team-id}",userid: string,teamid: string):operation7133,
    (api:"/users/{user-id}/joinedTeams/{team-id}/allChannels",userid: string,teamid: string):operation7134,
    (api:"/users/{user-id}/joinedTeams/{team-id}/allChannels/{channel-id}",userid: string,teamid: string,channelid: string):operation7135,
    (api:"/users/{user-id}/joinedTeams/{team-id}/allChannels/$count",userid: string,teamid: string):operation7136,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels",userid: string,teamid: string):operation7137,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}",userid: string,teamid: string,channelid: string):operation7138,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/filesFolder",userid: string,teamid: string,channelid: string):operation7139,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/filesFolder/content",userid: string,teamid: string,channelid: string):operation7140,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/members",userid: string,teamid: string,channelid: string):operation7141,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/members/{conversationMember-id}",userid: string,teamid: string,channelid: string,conversationMemberid: string):operation7142,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/members/$count",userid: string,teamid: string,channelid: string):operation7143,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/members/microsoft.graph.add",userid: string,teamid: string,channelid: string):operation7144,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages",userid: string,teamid: string,channelid: string):operation7145,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7146,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7147,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",userid: string,teamid: string,channelid: string,chatMessageid: string,chatMessageHostedContentid: string):operation7148,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/$count",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7149,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7150,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",userid: string,teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation7151,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",userid: string,teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation7152,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",userid: string,teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation7153,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",userid: string,teamid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation7154,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7155,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",userid: string,teamid: string,channelid: string,chatMessageid: string):operation7156,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/$count",userid: string,teamid: string,channelid: string):operation7157,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/messages/microsoft.graph.delta()",userid: string,teamid: string,channelid: string):operation7158,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/microsoft.graph.completeMigration",userid: string,teamid: string,channelid: string):operation7159,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",userid: string,teamid: string,channelid: string,userId: string,tenantId: string,userPrincipalName: string):operation7160,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/microsoft.graph.provisionEmail",userid: string,teamid: string,channelid: string):operation7161,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/microsoft.graph.removeEmail",userid: string,teamid: string,channelid: string):operation7162,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams",userid: string,teamid: string,channelid: string):operation7163,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}",userid: string,teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation7164,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",userid: string,teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation7165,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",userid: string,teamid: string,channelid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation7166,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",userid: string,teamid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation7167,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/sharedWithTeams/$count",userid: string,teamid: string,channelid: string):operation7168,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/tabs",userid: string,teamid: string,channelid: string):operation7169,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}",userid: string,teamid: string,channelid: string,teamsTabid: string):operation7170,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}/teamsApp",userid: string,teamid: string,channelid: string,teamsTabid: string):operation7171,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/{channel-id}/tabs/$count",userid: string,teamid: string,channelid: string):operation7172,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/$count",userid: string,teamid: string):operation7173,
    (api:"/users/{user-id}/joinedTeams/{team-id}/channels/microsoft.graph.getAllMessages()",userid: string,teamid: string):operation7174,
    (api:"/users/{user-id}/joinedTeams/{team-id}/group",userid: string,teamid: string):operation7175,
    (api:"/users/{user-id}/joinedTeams/{team-id}/incomingChannels",userid: string,teamid: string):operation7176,
    (api:"/users/{user-id}/joinedTeams/{team-id}/incomingChannels/{channel-id}",userid: string,teamid: string,channelid: string):operation7177,
    (api:"/users/{user-id}/joinedTeams/{team-id}/incomingChannels/$count",userid: string,teamid: string):operation7178,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps",userid: string,teamid: string):operation7179,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps/{teamsAppInstallation-id}",userid: string,teamid: string,teamsAppInstallationid: string):operation7180,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",userid: string,teamid: string,teamsAppInstallationid: string):operation7181,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsApp",userid: string,teamid: string,teamsAppInstallationid: string):operation7182,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",userid: string,teamid: string,teamsAppInstallationid: string):operation7183,
    (api:"/users/{user-id}/joinedTeams/{team-id}/installedApps/$count",userid: string,teamid: string):operation7184,
    (api:"/users/{user-id}/joinedTeams/{team-id}/members",userid: string,teamid: string):operation7185,
    (api:"/users/{user-id}/joinedTeams/{team-id}/members/{conversationMember-id}",userid: string,teamid: string,conversationMemberid: string):operation7186,
    (api:"/users/{user-id}/joinedTeams/{team-id}/members/$count",userid: string,teamid: string):operation7187,
    (api:"/users/{user-id}/joinedTeams/{team-id}/members/microsoft.graph.add",userid: string,teamid: string):operation7188,
    (api:"/users/{user-id}/joinedTeams/{team-id}/microsoft.graph.archive",userid: string,teamid: string):operation7189,
    (api:"/users/{user-id}/joinedTeams/{team-id}/microsoft.graph.clone",userid: string,teamid: string):operation7190,
    (api:"/users/{user-id}/joinedTeams/{team-id}/microsoft.graph.completeMigration",userid: string,teamid: string):operation7191,
    (api:"/users/{user-id}/joinedTeams/{team-id}/microsoft.graph.sendActivityNotification",userid: string,teamid: string):operation7192,
    (api:"/users/{user-id}/joinedTeams/{team-id}/microsoft.graph.unarchive",userid: string,teamid: string):operation7193,
    (api:"/users/{user-id}/joinedTeams/{team-id}/operations",userid: string,teamid: string):operation7194,
    (api:"/users/{user-id}/joinedTeams/{team-id}/operations/{teamsAsyncOperation-id}",userid: string,teamid: string,teamsAsyncOperationid: string):operation7195,
    (api:"/users/{user-id}/joinedTeams/{team-id}/operations/$count",userid: string,teamid: string):operation7196,
    (api:"/users/{user-id}/joinedTeams/{team-id}/photo",userid: string,teamid: string):operation7197,
    (api:"/users/{user-id}/joinedTeams/{team-id}/photo/$value",userid: string,teamid: string):operation7198,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel",userid: string,teamid: string):operation7199,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/filesFolder",userid: string,teamid: string):operation7200,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/filesFolder/content",userid: string,teamid: string):operation7201,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/members",userid: string,teamid: string):operation7202,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/members/{conversationMember-id}",userid: string,teamid: string,conversationMemberid: string):operation7203,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/members/$count",userid: string,teamid: string):operation7204,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/members/microsoft.graph.add",userid: string,teamid: string):operation7205,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages",userid: string,teamid: string):operation7206,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}",userid: string,teamid: string,chatMessageid: string):operation7207,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents",userid: string,teamid: string,chatMessageid: string):operation7208,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",userid: string,teamid: string,chatMessageid: string,chatMessageHostedContentid: string):operation7209,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/$count",userid: string,teamid: string,chatMessageid: string):operation7210,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies",userid: string,teamid: string,chatMessageid: string):operation7211,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}",userid: string,teamid: string,chatMessageid: string,chatMessageid1: string):operation7212,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",userid: string,teamid: string,chatMessageid: string,chatMessageid1: string):operation7213,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",userid: string,teamid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation7214,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",userid: string,teamid: string,chatMessageid: string,chatMessageid1: string):operation7215,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/$count",userid: string,teamid: string,chatMessageid: string):operation7216,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/microsoft.graph.delta()",userid: string,teamid: string,chatMessageid: string):operation7217,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/$count",userid: string,teamid: string):operation7218,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/messages/microsoft.graph.delta()",userid: string,teamid: string):operation7219,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/microsoft.graph.completeMigration",userid: string,teamid: string):operation7220,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",userid: string,teamid: string,userId: string,tenantId: string,userPrincipalName: string):operation7221,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/microsoft.graph.provisionEmail",userid: string,teamid: string):operation7222,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/microsoft.graph.removeEmail",userid: string,teamid: string):operation7223,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams",userid: string,teamid: string):operation7224,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}",userid: string,teamid: string,sharedWithChannelTeamInfoid: string):operation7225,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",userid: string,teamid: string,sharedWithChannelTeamInfoid: string):operation7226,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",userid: string,teamid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation7227,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",userid: string,teamid: string,sharedWithChannelTeamInfoid: string):operation7228,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/sharedWithTeams/$count",userid: string,teamid: string):operation7229,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/tabs",userid: string,teamid: string):operation7230,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/tabs/{teamsTab-id}",userid: string,teamid: string,teamsTabid: string):operation7231,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/tabs/{teamsTab-id}/teamsApp",userid: string,teamid: string,teamsTabid: string):operation7232,
    (api:"/users/{user-id}/joinedTeams/{team-id}/primaryChannel/tabs/$count",userid: string,teamid: string):operation7233,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule",userid: string,teamid: string):operation7234,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/microsoft.graph.share",userid: string,teamid: string):operation7235,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/offerShiftRequests",userid: string,teamid: string):operation7236,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}",userid: string,teamid: string,offerShiftRequestid: string):operation7237,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/offerShiftRequests/$count",userid: string,teamid: string):operation7238,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShiftChangeRequests",userid: string,teamid: string):operation7239,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShiftChangeRequests/{openShiftChangeRequest-id}",userid: string,teamid: string,openShiftChangeRequestid: string):operation7240,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShiftChangeRequests/$count",userid: string,teamid: string):operation7241,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShifts",userid: string,teamid: string):operation7242,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShifts/{openShift-id}",userid: string,teamid: string,openShiftid: string):operation7243,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/openShifts/$count",userid: string,teamid: string):operation7244,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/schedulingGroups",userid: string,teamid: string):operation7245,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}",userid: string,teamid: string,schedulingGroupid: string):operation7246,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/schedulingGroups/$count",userid: string,teamid: string):operation7247,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/shifts",userid: string,teamid: string):operation7248,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/shifts/{shift-id}",userid: string,teamid: string,shiftid: string):operation7249,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/shifts/$count",userid: string,teamid: string):operation7250,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/swapShiftsChangeRequests",userid: string,teamid: string):operation7251,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}",userid: string,teamid: string,swapShiftsChangeRequestid: string):operation7252,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/swapShiftsChangeRequests/$count",userid: string,teamid: string):operation7253,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffReasons",userid: string,teamid: string):operation7254,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}",userid: string,teamid: string,timeOffReasonid: string):operation7255,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffReasons/$count",userid: string,teamid: string):operation7256,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffRequests",userid: string,teamid: string):operation7257,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffRequests/{timeOffRequest-id}",userid: string,teamid: string,timeOffRequestid: string):operation7258,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timeOffRequests/$count",userid: string,teamid: string):operation7259,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timesOff",userid: string,teamid: string):operation7260,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timesOff/{timeOff-id}",userid: string,teamid: string,timeOffid: string):operation7261,
    (api:"/users/{user-id}/joinedTeams/{team-id}/schedule/timesOff/$count",userid: string,teamid: string):operation7262,
    (api:"/users/{user-id}/joinedTeams/{team-id}/template",userid: string,teamid: string):operation7263,
    (api:"/users/{user-id}/joinedTeams/$count",userid: string):operation7264,
    (api:"/users/{user-id}/joinedTeams/microsoft.graph.getAllMessages()",userid: string):operation7265,
    }
}

export {};