import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation3775, operation3776, operation3777, operation3778, operation3779, operation3780, operation3781, operation3782, operation3783, operation3784, operation3785, operation3786, operation3787, operation3788, operation3789, operation3790, operation3791, operation3792, operation3793, operation3794, operation3795, operation3796, operation3797, operation3798, operation3799, operation3800, operation3801, operation3802, operation3803, operation3804, operation3805, operation3806, operation3807, operation3808, operation3809, operation3810, operation3811, operation3812, operation3813, operation3814, operation3815, operation3816, operation3817, operation3818, operation3819, operation3820, operation3821, operation3822, operation3823, operation3824, operation3825, operation3826, operation3827, operation3828, operation3829, operation3830, operation3831, operation3832, operation3833, operation3834, operation3835, operation3836, operation3837, operation3838, operation3839, operation6788, operation6789, operation6790, operation6791, operation6792, operation6793, operation6794, operation6795, operation6796, operation6797, operation6798, operation6799, operation6800, operation6801, operation6802, operation6803, operation6804, operation6805, operation6806, operation6807, operation6808, operation6809, operation6810, operation6811, operation6812, operation6813, operation6814, operation6815, operation6816, operation6817, operation6818, operation6819, operation6820, operation6821, operation6822, operation6823, operation6824, operation6825, operation6826, operation6827, operation6828, operation6829, operation6830, operation6831, operation6832, operation6833, operation6834, operation6835, operation6836, operation6837, operation6838, operation6839, operation6840, operation6841, operation6842, operation6843, operation6844, operation6845, operation6846, operation6847, operation6848, operation6849, operation6850, operation6851, operation6852 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {

        // me contacts
        (api: "/me/contactFolders"): operation3775,
        (api: "/me/contactFolders/{contactFolder-id}", contactFolderid: string): operation3776,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders", contactFolderid: string): operation3777,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}", contactFolderid: string, contactFolderid1: string): operation3778,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts", contactFolderid: string, contactFolderid1: string): operation3779,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}", contactFolderid: string, contactFolderid1: string, contactid: string): operation3780,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions", contactFolderid: string, contactFolderid1: string, contactid: string): operation3781,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions/{extension-id}", contactFolderid: string, contactFolderid1: string, contactid: string, extensionid: string): operation3782,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions/$count", contactFolderid: string, contactFolderid1: string, contactid: string): operation3783,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties", contactFolderid: string, contactFolderid1: string, contactid: string): operation3784,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", contactFolderid: string, contactFolderid1: string, contactid: string, multiValueLegacyExtendedPropertyid: string): operation3785,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties/$count", contactFolderid: string, contactFolderid1: string, contactid: string): operation3786,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/photo", contactFolderid: string, contactFolderid1: string, contactid: string): operation3787,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/photo/$value", contactFolderid: string, contactFolderid1: string, contactid: string): operation3788,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties", contactFolderid: string, contactFolderid1: string, contactid: string): operation3789,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", contactFolderid: string, contactFolderid1: string, contactid: string, singleValueLegacyExtendedPropertyid: string): operation3790,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties/$count", contactFolderid: string, contactFolderid1: string, contactid: string): operation3791,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/$count", contactFolderid: string, contactFolderid1: string): operation3792,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/microsoft.graph.delta()", contactFolderid: string, contactFolderid1: string): operation3793,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties", contactFolderid: string, contactFolderid1: string): operation3794,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", contactFolderid: string, contactFolderid1: string, multiValueLegacyExtendedPropertyid: string): operation3795,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties/$count", contactFolderid: string, contactFolderid1: string): operation3796,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties", contactFolderid: string, contactFolderid1: string): operation3797,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", contactFolderid: string, contactFolderid1: string, singleValueLegacyExtendedPropertyid: string): operation3798,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties/$count", contactFolderid: string, contactFolderid1: string): operation3799,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/$count", contactFolderid: string): operation3800,
        (api: "/me/contactFolders/{contactFolder-id}/childFolders/microsoft.graph.delta()", contactFolderid: string): operation3801,
        (api: "/me/contactFolders/{contactFolder-id}/contacts", contactFolderid: string): operation3802,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}", contactFolderid: string, contactid: string): operation3803,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions", contactFolderid: string, contactid: string): operation3804,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions/{extension-id}", contactFolderid: string, contactid: string, extensionid: string): operation3805,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions/$count", contactFolderid: string, contactid: string): operation3806,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties", contactFolderid: string, contactid: string): operation3807,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", contactFolderid: string, contactid: string, multiValueLegacyExtendedPropertyid: string): operation3808,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties/$count", contactFolderid: string, contactid: string): operation3809,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/photo", contactFolderid: string, contactid: string): operation3810,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/photo/$value", contactFolderid: string, contactid: string): operation3811,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties", contactFolderid: string, contactid: string): operation3812,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", contactFolderid: string, contactid: string, singleValueLegacyExtendedPropertyid: string): operation3813,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties/$count", contactFolderid: string, contactid: string): operation3814,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/$count", contactFolderid: string): operation3815,
        (api: "/me/contactFolders/{contactFolder-id}/contacts/microsoft.graph.delta()", contactFolderid: string): operation3816,
        (api: "/me/contactFolders/{contactFolder-id}/multiValueExtendedProperties", contactFolderid: string): operation3817,
        (api: "/me/contactFolders/{contactFolder-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", contactFolderid: string, multiValueLegacyExtendedPropertyid: string): operation3818,
        (api: "/me/contactFolders/{contactFolder-id}/multiValueExtendedProperties/$count", contactFolderid: string): operation3819,
        (api: "/me/contactFolders/{contactFolder-id}/singleValueExtendedProperties", contactFolderid: string): operation3820,
        (api: "/me/contactFolders/{contactFolder-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", contactFolderid: string, singleValueLegacyExtendedPropertyid: string): operation3821,
        (api: "/me/contactFolders/{contactFolder-id}/singleValueExtendedProperties/$count", contactFolderid: string): operation3822,
        (api: "/me/contactFolders/$count"): operation3823,
        (api: "/me/contactFolders/microsoft.graph.delta()"): operation3824,
        (api: "/me/contacts"): operation3825,
        (api: "/me/contacts/{contact-id}", contactid: string): operation3826,
        (api: "/me/contacts/{contact-id}/extensions", contactid: string): operation3827,
        (api: "/me/contacts/{contact-id}/extensions/{extension-id}", contactid: string, extensionid: string): operation3828,
        (api: "/me/contacts/{contact-id}/extensions/$count", contactid: string): operation3829,
        (api: "/me/contacts/{contact-id}/multiValueExtendedProperties", contactid: string): operation3830,
        (api: "/me/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", contactid: string, multiValueLegacyExtendedPropertyid: string): operation3831,
        (api: "/me/contacts/{contact-id}/multiValueExtendedProperties/$count", contactid: string): operation3832,
        (api: "/me/contacts/{contact-id}/photo", contactid: string): operation3833,
        (api: "/me/contacts/{contact-id}/photo/$value", contactid: string): operation3834,
        (api: "/me/contacts/{contact-id}/singleValueExtendedProperties", contactid: string): operation3835,
        (api: "/me/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", contactid: string, singleValueLegacyExtendedPropertyid: string): operation3836,
        (api: "/me/contacts/{contact-id}/singleValueExtendedProperties/$count", contactid: string): operation3837,
        (api: "/me/contacts/$count"): operation3838,
        (api: "/me/contacts/microsoft.graph.delta()"): operation3839,

        // user contacts
        (api: "/users/{user-id}/contactFolders", userid: string): operation6788,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}", userid: string, contactFolderid: string): operation6789,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders", userid: string, contactFolderid: string): operation6790,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}", userid: string, contactFolderid: string, contactFolderid1: string): operation6791,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts", userid: string, contactFolderid: string, contactFolderid1: string): operation6792,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6793,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6794,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions/{extension-id}", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string, extensionid: string): operation6795,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/extensions/$count", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6796,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6797,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string, multiValueLegacyExtendedPropertyid: string): operation6798,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/multiValueExtendedProperties/$count", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6799,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/photo", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6800,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/photo/$value", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6801,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6802,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string, singleValueLegacyExtendedPropertyid: string): operation6803,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/{contact-id}/singleValueExtendedProperties/$count", userid: string, contactFolderid: string, contactFolderid1: string, contactid: string): operation6804,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/$count", userid: string, contactFolderid: string, contactFolderid1: string): operation6805,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/contacts/microsoft.graph.delta()", userid: string, contactFolderid: string, contactFolderid1: string): operation6806,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties", userid: string, contactFolderid: string, contactFolderid1: string): operation6807,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactFolderid1: string, multiValueLegacyExtendedPropertyid: string): operation6808,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/multiValueExtendedProperties/$count", userid: string, contactFolderid: string, contactFolderid1: string): operation6809,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties", userid: string, contactFolderid: string, contactFolderid1: string): operation6810,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactFolderid1: string, singleValueLegacyExtendedPropertyid: string): operation6811,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/{contactFolder-id1}/singleValueExtendedProperties/$count", userid: string, contactFolderid: string, contactFolderid1: string): operation6812,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/$count", userid: string, contactFolderid: string): operation6813,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/childFolders/microsoft.graph.delta()", userid: string, contactFolderid: string): operation6814,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts", userid: string, contactFolderid: string): operation6815,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}", userid: string, contactFolderid: string, contactid: string): operation6816,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions", userid: string, contactFolderid: string, contactid: string): operation6817,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions/{extension-id}", userid: string, contactFolderid: string, contactid: string, extensionid: string): operation6818,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/extensions/$count", userid: string, contactFolderid: string, contactid: string): operation6819,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties", userid: string, contactFolderid: string, contactid: string): operation6820,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactid: string, multiValueLegacyExtendedPropertyid: string): operation6821,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/multiValueExtendedProperties/$count", userid: string, contactFolderid: string, contactid: string): operation6822,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/photo", userid: string, contactFolderid: string, contactid: string): operation6823,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/photo/$value", userid: string, contactFolderid: string, contactid: string): operation6824,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties", userid: string, contactFolderid: string, contactid: string): operation6825,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, contactid: string, singleValueLegacyExtendedPropertyid: string): operation6826,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/{contact-id}/singleValueExtendedProperties/$count", userid: string, contactFolderid: string, contactid: string): operation6827,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/$count", userid: string, contactFolderid: string): operation6828,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/contacts/microsoft.graph.delta()", userid: string, contactFolderid: string): operation6829,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/multiValueExtendedProperties", userid: string, contactFolderid: string): operation6830,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, multiValueLegacyExtendedPropertyid: string): operation6831,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/multiValueExtendedProperties/$count", userid: string, contactFolderid: string): operation6832,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/singleValueExtendedProperties", userid: string, contactFolderid: string): operation6833,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, contactFolderid: string, singleValueLegacyExtendedPropertyid: string): operation6834,
        (api: "/users/{user-id}/contactFolders/{contactFolder-id}/singleValueExtendedProperties/$count", userid: string, contactFolderid: string): operation6835,
        (api: "/users/{user-id}/contactFolders/$count", userid: string): operation6836,
        (api: "/users/{user-id}/contactFolders/microsoft.graph.delta()", userid: string): operation6837,
        (api: "/users/{user-id}/contacts", userid: string): operation6838,
        (api: "/users/{user-id}/contacts/{contact-id}", userid: string, contactid: string): operation6839,
        (api: "/users/{user-id}/contacts/{contact-id}/extensions", userid: string, contactid: string): operation6840,
        (api: "/users/{user-id}/contacts/{contact-id}/extensions/{extension-id}", userid: string, contactid: string, extensionid: string): operation6841,
        (api: "/users/{user-id}/contacts/{contact-id}/extensions/$count", userid: string, contactid: string): operation6842,
        (api: "/users/{user-id}/contacts/{contact-id}/multiValueExtendedProperties", userid: string, contactid: string): operation6843,
        (api: "/users/{user-id}/contacts/{contact-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, contactid: string, multiValueLegacyExtendedPropertyid: string): operation6844,
        (api: "/users/{user-id}/contacts/{contact-id}/multiValueExtendedProperties/$count", userid: string, contactid: string): operation6845,
        (api: "/users/{user-id}/contacts/{contact-id}/photo", userid: string, contactid: string): operation6846,
        (api: "/users/{user-id}/contacts/{contact-id}/photo/$value", userid: string, contactid: string): operation6847,
        (api: "/users/{user-id}/contacts/{contact-id}/singleValueExtendedProperties", userid: string, contactid: string): operation6848,
        (api: "/users/{user-id}/contacts/{contact-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, contactid: string, singleValueLegacyExtendedPropertyid: string): operation6849,
        (api: "/users/{user-id}/contacts/{contact-id}/singleValueExtendedProperties/$count", userid: string, contactid: string): operation6850,
        (api: "/users/{user-id}/contacts/$count", userid: string): operation6851,
        (api: "/users/{user-id}/contacts/microsoft.graph.delta()", userid: string): operation6852,
    }
}