import { GraphApis } from "../../lib/src/rest/graphAPIs";

import { operation1430, operation1431, operation1432, operation1433, operation1434, operation1435, operation1436, operation1437, operation1438, operation1439, operation1440, operation1441, operation1442, operation1443, operation1606, operation1607, operation1608, operation1609, operation1610, operation1611, operation1612, operation1613, operation1614, operation1615, operation1616, operation1617, operation1618, operation1619, operation1620, operation1621, operation1622, operation1623, operation1624, operation1625, operation1626, operation1627, operation1628, operation1629, operation1630, operation1631, operation1632, operation1633, operation1634, operation1635, operation1636, operation1637, operation1638, operation1639, operation1640, operation1641, operation1642, operation1643, operation1644, operation1645, operation1646, operation1647, operation1885, operation1886, operation1887, operation1888, operation1889, operation1890, operation1891, operation1892, operation1893, operation1894, operation1895, operation1896, operation1897, operation1898, operation1899, operation1900, operation1901, operation1902, operation1903, operation1904, operation1905, operation1906, operation1907, operation1908, operation1909, operation1910, operation1911, operation1912, operation1913, operation1914, operation1915, operation1916, operation1917, operation1918, operation1919, operation1920, operation1921, operation1922, operation1923, operation1924, operation1925, operation1926, operation1927, operation1928, operation1929, operation1930, operation1931, operation1932, operation1933, operation1934, operation1935, operation1936, operation1937, operation1938, operation1939, operation1940, operation1941, operation1942, operation1943, operation1944, operation1945, operation1946, operation1947, operation1948, operation1949, operation1950, operation1951, operation1952, operation1953, operation1954, operation1955, operation1956, operation1957, operation1958, operation1959, operation1960, operation1961, operation1962, operation1963, operation1964, operation1965, operation1966, operation1967, operation1968, operation1969, operation1970, operation2074, operation2075, operation2076, operation2077, operation2078, operation2079, operation2080, operation2081, operation2082, operation2083, operation2084, operation2085, operation2086, operation2087, operation2088, operation2089, operation2090, operation2091, operation2092, operation2093, operation2094, operation2095, operation2096, operation2097, operation2098, operation2099, operation2100, operation2101, operation2102, operation2103, operation2104, operation2105, operation2106, operation2107, operation2108, operation2109, operation2110, operation2111, operation2112, operation2135, operation2136, operation2137, operation2138, operation2139, operation2140, operation2141, operation2670, operation2671, operation2672, operation2673, operation2674, operation2675, operation2676, operation2677, operation2678, operation2679, operation2680, operation2681, operation2682, operation2683, operation2684, operation2685, operation2686, operation2687, operation2688, operation2689, operation2690, operation2691, operation2692, operation2693, operation2694, operation2695, operation2696, operation2697, operation2698, operation2699, operation2700, operation2701, operation2702, operation2703, operation2704, operation2705, operation2706, operation2707, operation2708, operation2709, operation2710, operation2711, operation2712, operation2713, operation2714, operation2715, operation2716, operation2717, operation2718, operation2719, operation2720, operation2721, operation2722, operation2723, operation2724, operation2725, operation2726, operation2727, operation2728, operation2729, operation2730, operation2731, operation2732, operation2733, operation2734, operation2735, operation2736, operation2737, operation2738, operation2739, operation2740, operation2741, operation2742, operation2743, operation2744, operation2745, operation2746, operation2747, operation2748, operation2749, operation2750, operation2751, operation2752, operation2753, operation2754, operation2755, operation2756, operation2757, operation2758, operation2759, operation2760, operation2761, operation2762, operation2763, operation2764, operation2765, operation2766, operation2767, operation2768, operation2769, operation2770, operation2771, operation2772, operation2773, operation2774, operation2775, operation2776, operation2777, operation2778, operation2779, operation2780, operation2781, operation2782, operation2783, operation2784, operation2785, operation2786, operation2787, operation2788, operation2789, operation2790, operation2791, operation2792, operation2793, operation2794, operation2795, operation2796, operation2797, operation2798, operation2799, operation2800, operation2801, operation2839, operation2840, operation2841, operation2842, operation2843, operation2844, operation2845, operation2846, operation2847, operation2848, operation2849, operation2850, operation2851, operation2852, operation2853, operation2854, operation2855, operation2856, operation2857, operation2858, operation2859, operation2860, operation2861, operation2862, operation2863, operation2864, operation2865, operation2866, operation2867, operation2868, operation2869, operation2870, operation2871, operation2872, operation2873, operation2874, operation2875, operation2876, operation2877, operation2878, operation2879, operation2880, operation2881, operation2882, operation2883, operation2884, operation2885, operation2886, operation2887, operation2888, operation2889, operation2890, operation2891, operation2892, operation2893, operation2894, operation2895, operation2896, operation2897, operation2898, operation2899 } from "../../lib/src/rest/operations";

declare module "../../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/groups"):operation1435,
        (api:"/groups/{group-id}",groupid: string):operation1436,
        (api:"/groups/{group-id}/acceptedSenders",groupid: string):operation1437,
        (api:"/groups/{group-id}/acceptedSenders/{directoryObject-id}/$ref",groupid: string,directoryObjectid: string):operation1438,
        (api:"/groups/{group-id}/acceptedSenders/$count",groupid: string):operation1439,
        (api:"/groups/{group-id}/acceptedSenders/$ref",groupid: string):operation1440,
        (api:"/groups/{group-id}/appRoleAssignments",groupid: string):operation1441,
        (api:"/groups/{group-id}/appRoleAssignments/{appRoleAssignment-id}",groupid: string,appRoleAssignmentid: string):operation1442,
        (api:"/groups/{group-id}/appRoleAssignments/$count",groupid: string):operation1443,    
        (api:"/groups/{group-id}/createdOnBehalfOf",groupid: string):operation1647,
        (api:"/groups/{group-id}/extensions",groupid: string):operation1885,
        (api:"/groups/{group-id}/extensions/{extension-id}",groupid: string,extensionid: string):operation1886,
        (api:"/groups/{group-id}/extensions/$count",groupid: string):operation1887,
        (api:"/groups/{group-id}/groupLifecyclePolicies",groupid: string):operation1888,
        (api:"/groups/{group-id}/groupLifecyclePolicies/{groupLifecyclePolicy-id}",groupid: string,groupLifecyclePolicyid: string):operation1889,
        (api:"/groups/{group-id}/groupLifecyclePolicies/{groupLifecyclePolicy-id}/microsoft.graph.addGroup",groupid: string,groupLifecyclePolicyid: string):operation1890,
        (api:"/groups/{group-id}/groupLifecyclePolicies/{groupLifecyclePolicy-id}/microsoft.graph.removeGroup",groupid: string,groupLifecyclePolicyid: string):operation1891,
        (api:"/groups/{group-id}/groupLifecyclePolicies/$count",groupid: string):operation1892,
        (api:"/groups/{group-id}/memberOf",groupid: string):operation1893,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}",groupid: string,directoryObjectid: string):operation1894,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation1895,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation1896,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation1897,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation1898,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation1899,
        (api:"/groups/{group-id}/memberOf/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation1900,
        (api:"/groups/{group-id}/memberOf/$count",groupid: string):operation1901,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.application",groupid: string):operation1902,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.application/$count",groupid: string):operation1903,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.device",groupid: string):operation1904,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.device/$count",groupid: string):operation1905,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.group",groupid: string):operation1906,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.group/$count",groupid: string):operation1907,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.orgContact",groupid: string):operation1908,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.orgContact/$count",groupid: string):operation1909,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.servicePrincipal",groupid: string):operation1910,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.servicePrincipal/$count",groupid: string):operation1911,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.user",groupid: string):operation1912,
        (api:"/groups/{group-id}/memberOf/microsoft.graph.user/$count",groupid: string):operation1913,
        (api:"/groups/{group-id}/members",groupid: string):operation1914,
        (api:"/groups/{group-id}/members/{directoryObject-id}/$ref",groupid: string,directoryObjectid: string):operation1915,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation1916,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation1917,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation1918,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation1919,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation1920,
        (api:"/groups/{group-id}/members/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation1921,
        (api:"/groups/{group-id}/members/$count",groupid: string):operation1922,
        (api:"/groups/{group-id}/members/$ref",groupid: string):operation1923,
        (api:"/groups/{group-id}/members/microsoft.graph.application",groupid: string):operation1924,
        (api:"/groups/{group-id}/members/microsoft.graph.application/$count",groupid: string):operation1925,
        (api:"/groups/{group-id}/members/microsoft.graph.device",groupid: string):operation1926,
        (api:"/groups/{group-id}/members/microsoft.graph.device/$count",groupid: string):operation1927,
        (api:"/groups/{group-id}/members/microsoft.graph.group",groupid: string):operation1928,
        (api:"/groups/{group-id}/members/microsoft.graph.group/$count",groupid: string):operation1929,
        (api:"/groups/{group-id}/members/microsoft.graph.orgContact",groupid: string):operation1930,
        (api:"/groups/{group-id}/members/microsoft.graph.orgContact/$count",groupid: string):operation1931,
        (api:"/groups/{group-id}/members/microsoft.graph.servicePrincipal",groupid: string):operation1932,
        (api:"/groups/{group-id}/members/microsoft.graph.servicePrincipal/$count",groupid: string):operation1933,
        (api:"/groups/{group-id}/members/microsoft.graph.user",groupid: string):operation1934,
        (api:"/groups/{group-id}/members/microsoft.graph.user/$count",groupid: string):operation1935,
        (api:"/groups/{group-id}/membersWithLicenseErrors",groupid: string):operation1936,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}",groupid: string,directoryObjectid: string):operation1937,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation1938,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation1939,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation1940,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation1941,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation1942,
        (api:"/groups/{group-id}/membersWithLicenseErrors/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation1943,
        (api:"/groups/{group-id}/membersWithLicenseErrors/$count",groupid: string):operation1944,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.application",groupid: string):operation1945,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.application/$count",groupid: string):operation1946,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.device",groupid: string):operation1947,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.device/$count",groupid: string):operation1948,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.group",groupid: string):operation1949,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.group/$count",groupid: string):operation1950,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.orgContact",groupid: string):operation1951,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.orgContact/$count",groupid: string):operation1952,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.servicePrincipal",groupid: string):operation1953,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.servicePrincipal/$count",groupid: string):operation1954,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.user",groupid: string):operation1955,
        (api:"/groups/{group-id}/membersWithLicenseErrors/microsoft.graph.user/$count",groupid: string):operation1956,
        (api:"/groups/{group-id}/microsoft.graph.addFavorite",groupid: string):operation1957,
        (api:"/groups/{group-id}/microsoft.graph.assignLicense",groupid: string):operation1958,
        (api:"/groups/{group-id}/microsoft.graph.checkGrantedPermissionsForApp",groupid: string):operation1959,
        (api:"/groups/{group-id}/microsoft.graph.checkMemberGroups",groupid: string):operation1960,
        (api:"/groups/{group-id}/microsoft.graph.checkMemberObjects",groupid: string):operation1961,
        (api:"/groups/{group-id}/microsoft.graph.getMemberGroups",groupid: string):operation1962,
        (api:"/groups/{group-id}/microsoft.graph.getMemberObjects",groupid: string):operation1963,
        (api:"/groups/{group-id}/microsoft.graph.removeFavorite",groupid: string):operation1964,
        (api:"/groups/{group-id}/microsoft.graph.renew",groupid: string):operation1965,
        (api:"/groups/{group-id}/microsoft.graph.resetUnseenCount",groupid: string):operation1966,
        (api:"/groups/{group-id}/microsoft.graph.restore",groupid: string):operation1967,
        (api:"/groups/{group-id}/microsoft.graph.subscribeByMail",groupid: string):operation1968,
        (api:"/groups/{group-id}/microsoft.graph.unsubscribeByMail",groupid: string):operation1969,
        (api:"/groups/{group-id}/microsoft.graph.validateProperties",groupid: string):operation1970,
        
        (api:"/groups/{group-id}/owners",groupid: string):operation2074,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/$ref",groupid: string,directoryObjectid: string):operation2075,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation2076,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation2077,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation2078,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation2079,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation2080,
        (api:"/groups/{group-id}/owners/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation2081,
        (api:"/groups/{group-id}/owners/$count",groupid: string):operation2082,
        (api:"/groups/{group-id}/owners/$ref",groupid: string):operation2083,
        (api:"/groups/{group-id}/owners/microsoft.graph.application",groupid: string):operation2084,
        (api:"/groups/{group-id}/owners/microsoft.graph.application/$count",groupid: string):operation2085,
        (api:"/groups/{group-id}/owners/microsoft.graph.device",groupid: string):operation2086,
        (api:"/groups/{group-id}/owners/microsoft.graph.device/$count",groupid: string):operation2087,
        (api:"/groups/{group-id}/owners/microsoft.graph.group",groupid: string):operation2088,
        (api:"/groups/{group-id}/owners/microsoft.graph.group/$count",groupid: string):operation2089,
        (api:"/groups/{group-id}/owners/microsoft.graph.orgContact",groupid: string):operation2090,
        (api:"/groups/{group-id}/owners/microsoft.graph.orgContact/$count",groupid: string):operation2091,
        (api:"/groups/{group-id}/owners/microsoft.graph.servicePrincipal",groupid: string):operation2092,
        (api:"/groups/{group-id}/owners/microsoft.graph.servicePrincipal/$count",groupid: string):operation2093,
        (api:"/groups/{group-id}/owners/microsoft.graph.user",groupid: string):operation2094,
        (api:"/groups/{group-id}/owners/microsoft.graph.user/$count",groupid: string):operation2095,
        (api:"/groups/{group-id}/permissionGrants",groupid: string):operation2096,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}",groupid: string,resourceSpecificPermissionGrantid: string):operation2097,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}/microsoft.graph.checkMemberGroups",groupid: string,resourceSpecificPermissionGrantid: string):operation2098,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}/microsoft.graph.checkMemberObjects",groupid: string,resourceSpecificPermissionGrantid: string):operation2099,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}/microsoft.graph.getMemberGroups",groupid: string,resourceSpecificPermissionGrantid: string):operation2100,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}/microsoft.graph.getMemberObjects",groupid: string,resourceSpecificPermissionGrantid: string):operation2101,
        (api:"/groups/{group-id}/permissionGrants/{resourceSpecificPermissionGrant-id}/microsoft.graph.restore",groupid: string,resourceSpecificPermissionGrantid: string):operation2102,
        (api:"/groups/{group-id}/permissionGrants/$count",groupid: string):operation2103,
        (api:"/groups/{group-id}/permissionGrants/microsoft.graph.getAvailableExtensionProperties",groupid: string):operation2104,
        (api:"/groups/{group-id}/permissionGrants/microsoft.graph.getByIds",groupid: string):operation2105,
        (api:"/groups/{group-id}/permissionGrants/microsoft.graph.validateProperties",groupid: string):operation2106,
        (api:"/groups/{group-id}/photo",groupid: string):operation2107,
        (api:"/groups/{group-id}/photo/$value",groupid: string):operation2108,
        (api:"/groups/{group-id}/photos",groupid: string):operation2109,
        (api:"/groups/{group-id}/photos/{profilePhoto-id}",groupid: string,profilePhotoid: string):operation2110,
        (api:"/groups/{group-id}/photos/{profilePhoto-id}/$value",groupid: string,profilePhotoid: string):operation2111,
        (api:"/groups/{group-id}/photos/$count",groupid: string):operation2112,
        
        (api:"/groups/{group-id}/rejectedSenders",groupid: string):operation2135,
        (api:"/groups/{group-id}/rejectedSenders/{directoryObject-id}/$ref",groupid: string,directoryObjectid: string):operation2136,
        (api:"/groups/{group-id}/rejectedSenders/$count",groupid: string):operation2137,
        (api:"/groups/{group-id}/rejectedSenders/$ref",groupid: string):operation2138,
        (api:"/groups/{group-id}/settings",groupid: string):operation2139,
        (api:"/groups/{group-id}/settings/{groupSetting-id}",groupid: string,groupSettingid: string):operation2140,
        (api:"/groups/{group-id}/settings/$count",groupid: string):operation2141,
        
        (api:"/groups/{group-id}/team",groupid: string):operation2670,
        (api:"/groups/{group-id}/team/allChannels",groupid: string):operation2671,
        (api:"/groups/{group-id}/team/allChannels/{channel-id}",groupid: string,channelid: string):operation2672,
        (api:"/groups/{group-id}/team/allChannels/$count",groupid: string):operation2673,
        (api:"/groups/{group-id}/team/channels",groupid: string):operation2674,
        (api:"/groups/{group-id}/team/channels/{channel-id}",groupid: string,channelid: string):operation2675,
        (api:"/groups/{group-id}/team/channels/{channel-id}/filesFolder",groupid: string,channelid: string):operation2676,
        (api:"/groups/{group-id}/team/channels/{channel-id}/filesFolder/content",groupid: string,channelid: string):operation2677,
        (api:"/groups/{group-id}/team/channels/{channel-id}/members",groupid: string,channelid: string):operation2678,
        (api:"/groups/{group-id}/team/channels/{channel-id}/members/{conversationMember-id}",groupid: string,channelid: string,conversationMemberid: string):operation2679,
        (api:"/groups/{group-id}/team/channels/{channel-id}/members/$count",groupid: string,channelid: string):operation2680,
        (api:"/groups/{group-id}/team/channels/{channel-id}/members/microsoft.graph.add",groupid: string,channelid: string):operation2681,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages",groupid: string,channelid: string):operation2682,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}",groupid: string,channelid: string,chatMessageid: string):operation2683,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/hostedContents",groupid: string,channelid: string,chatMessageid: string):operation2684,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",groupid: string,channelid: string,chatMessageid: string,chatMessageHostedContentid: string):operation2685,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/$count",groupid: string,channelid: string,chatMessageid: string):operation2686,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies",groupid: string,channelid: string,chatMessageid: string):operation2687,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}",groupid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation2688,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",groupid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation2689,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",groupid: string,channelid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation2690,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",groupid: string,channelid: string,chatMessageid: string,chatMessageid1: string):operation2691,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/$count",groupid: string,channelid: string,chatMessageid: string):operation2692,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/{chatMessage-id}/replies/microsoft.graph.delta()",groupid: string,channelid: string,chatMessageid: string):operation2693,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/$count",groupid: string,channelid: string):operation2694,
        (api:"/groups/{group-id}/team/channels/{channel-id}/messages/microsoft.graph.delta()",groupid: string,channelid: string):operation2695,
        (api:"/groups/{group-id}/team/channels/{channel-id}/microsoft.graph.completeMigration",groupid: string,channelid: string):operation2696,
        (api:"/groups/{group-id}/team/channels/{channel-id}/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",groupid: string,channelid: string,userId: string,tenantId: string,userPrincipalName: string):operation2697,
        (api:"/groups/{group-id}/team/channels/{channel-id}/microsoft.graph.provisionEmail",groupid: string,channelid: string):operation2698,
        (api:"/groups/{group-id}/team/channels/{channel-id}/microsoft.graph.removeEmail",groupid: string,channelid: string):operation2699,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams",groupid: string,channelid: string):operation2700,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}",groupid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation2701,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",groupid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation2702,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",groupid: string,channelid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation2703,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",groupid: string,channelid: string,sharedWithChannelTeamInfoid: string):operation2704,
        (api:"/groups/{group-id}/team/channels/{channel-id}/sharedWithTeams/$count",groupid: string,channelid: string):operation2705,
        (api:"/groups/{group-id}/team/channels/{channel-id}/tabs",groupid: string,channelid: string):operation2706,
        (api:"/groups/{group-id}/team/channels/{channel-id}/tabs/{teamsTab-id}",groupid: string,channelid: string,teamsTabid: string):operation2707,
        (api:"/groups/{group-id}/team/channels/{channel-id}/tabs/{teamsTab-id}/teamsApp",groupid: string,channelid: string,teamsTabid: string):operation2708,
        (api:"/groups/{group-id}/team/channels/{channel-id}/tabs/$count",groupid: string,channelid: string):operation2709,
        (api:"/groups/{group-id}/team/channels/$count",groupid: string):operation2710,
        (api:"/groups/{group-id}/team/channels/microsoft.graph.getAllMessages()",groupid: string):operation2711,
        (api:"/groups/{group-id}/team/group",groupid: string):operation2712,
        (api:"/groups/{group-id}/team/incomingChannels",groupid: string):operation2713,
        (api:"/groups/{group-id}/team/incomingChannels/{channel-id}",groupid: string,channelid: string):operation2714,
        (api:"/groups/{group-id}/team/incomingChannels/$count",groupid: string):operation2715,
        (api:"/groups/{group-id}/team/installedApps",groupid: string):operation2716,
        (api:"/groups/{group-id}/team/installedApps/{teamsAppInstallation-id}",groupid: string,teamsAppInstallationid: string):operation2717,
        (api:"/groups/{group-id}/team/installedApps/{teamsAppInstallation-id}/microsoft.graph.upgrade",groupid: string,teamsAppInstallationid: string):operation2718,
        (api:"/groups/{group-id}/team/installedApps/{teamsAppInstallation-id}/teamsApp",groupid: string,teamsAppInstallationid: string):operation2719,
        (api:"/groups/{group-id}/team/installedApps/{teamsAppInstallation-id}/teamsAppDefinition",groupid: string,teamsAppInstallationid: string):operation2720,
        (api:"/groups/{group-id}/team/installedApps/$count",groupid: string):operation2721,
        (api:"/groups/{group-id}/team/members",groupid: string):operation2722,
        (api:"/groups/{group-id}/team/members/{conversationMember-id}",groupid: string,conversationMemberid: string):operation2723,
        (api:"/groups/{group-id}/team/members/$count",groupid: string):operation2724,
        (api:"/groups/{group-id}/team/members/microsoft.graph.add",groupid: string):operation2725,
        (api:"/groups/{group-id}/team/microsoft.graph.archive",groupid: string):operation2726,
        (api:"/groups/{group-id}/team/microsoft.graph.clone",groupid: string):operation2727,
        (api:"/groups/{group-id}/team/microsoft.graph.completeMigration",groupid: string):operation2728,
        (api:"/groups/{group-id}/team/microsoft.graph.sendActivityNotification",groupid: string):operation2729,
        (api:"/groups/{group-id}/team/microsoft.graph.unarchive",groupid: string):operation2730,
        (api:"/groups/{group-id}/team/operations",groupid: string):operation2731,
        (api:"/groups/{group-id}/team/operations/{teamsAsyncOperation-id}",groupid: string,teamsAsyncOperationid: string):operation2732,
        (api:"/groups/{group-id}/team/operations/$count",groupid: string):operation2733,
        (api:"/groups/{group-id}/team/photo",groupid: string):operation2734,
        (api:"/groups/{group-id}/team/photo/$value",groupid: string):operation2735,
        (api:"/groups/{group-id}/team/primaryChannel",groupid: string):operation2736,
        (api:"/groups/{group-id}/team/primaryChannel/filesFolder",groupid: string):operation2737,
        (api:"/groups/{group-id}/team/primaryChannel/filesFolder/content",groupid: string):operation2738,
        (api:"/groups/{group-id}/team/primaryChannel/members",groupid: string):operation2739,
        (api:"/groups/{group-id}/team/primaryChannel/members/{conversationMember-id}",groupid: string,conversationMemberid: string):operation2740,
        (api:"/groups/{group-id}/team/primaryChannel/members/$count",groupid: string):operation2741,
        (api:"/groups/{group-id}/team/primaryChannel/members/microsoft.graph.add",groupid: string):operation2742,
        (api:"/groups/{group-id}/team/primaryChannel/messages",groupid: string):operation2743,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}",groupid: string,chatMessageid: string):operation2744,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/hostedContents",groupid: string,chatMessageid: string):operation2745,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}",groupid: string,chatMessageid: string,chatMessageHostedContentid: string):operation2746,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/hostedContents/$count",groupid: string,chatMessageid: string):operation2747,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies",groupid: string,chatMessageid: string):operation2748,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}",groupid: string,chatMessageid: string,chatMessageid1: string):operation2749,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents",groupid: string,chatMessageid: string,chatMessageid1: string):operation2750,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}",groupid: string,chatMessageid: string,chatMessageid1: string,chatMessageHostedContentid: string):operation2751,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count",groupid: string,chatMessageid: string,chatMessageid1: string):operation2752,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/$count",groupid: string,chatMessageid: string):operation2753,
        (api:"/groups/{group-id}/team/primaryChannel/messages/{chatMessage-id}/replies/microsoft.graph.delta()",groupid: string,chatMessageid: string):operation2754,
        (api:"/groups/{group-id}/team/primaryChannel/messages/$count",groupid: string):operation2755,
        (api:"/groups/{group-id}/team/primaryChannel/messages/microsoft.graph.delta()",groupid: string):operation2756,
        (api:"/groups/{group-id}/team/primaryChannel/microsoft.graph.completeMigration",groupid: string):operation2757,
        (api:"/groups/{group-id}/team/primaryChannel/microsoft.graph.doesUserHaveAccess(userId='{userId}',tenantId='{tenantId}',userPrincipalName='{userPrincipalName}')",groupid: string,userId: string,tenantId: string,userPrincipalName: string):operation2758,
        (api:"/groups/{group-id}/team/primaryChannel/microsoft.graph.provisionEmail",groupid: string):operation2759,
        (api:"/groups/{group-id}/team/primaryChannel/microsoft.graph.removeEmail",groupid: string):operation2760,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams",groupid: string):operation2761,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}",groupid: string,sharedWithChannelTeamInfoid: string):operation2762,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers",groupid: string,sharedWithChannelTeamInfoid: string):operation2763,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/{conversationMember-id}",groupid: string,sharedWithChannelTeamInfoid: string,conversationMemberid: string):operation2764,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams/{sharedWithChannelTeamInfo-id}/allowedMembers/$count",groupid: string,sharedWithChannelTeamInfoid: string):operation2765,
        (api:"/groups/{group-id}/team/primaryChannel/sharedWithTeams/$count",groupid: string):operation2766,
        (api:"/groups/{group-id}/team/primaryChannel/tabs",groupid: string):operation2767,
        (api:"/groups/{group-id}/team/primaryChannel/tabs/{teamsTab-id}",groupid: string,teamsTabid: string):operation2768,
        (api:"/groups/{group-id}/team/primaryChannel/tabs/{teamsTab-id}/teamsApp",groupid: string,teamsTabid: string):operation2769,
        (api:"/groups/{group-id}/team/primaryChannel/tabs/$count",groupid: string):operation2770,
        (api:"/groups/{group-id}/team/schedule",groupid: string):operation2771,
        (api:"/groups/{group-id}/team/schedule/microsoft.graph.share",groupid: string):operation2772,
        (api:"/groups/{group-id}/team/schedule/offerShiftRequests",groupid: string):operation2773,
        (api:"/groups/{group-id}/team/schedule/offerShiftRequests/{offerShiftRequest-id}",groupid: string,offerShiftRequestid: string):operation2774,
        (api:"/groups/{group-id}/team/schedule/offerShiftRequests/$count",groupid: string):operation2775,
        (api:"/groups/{group-id}/team/schedule/openShiftChangeRequests",groupid: string):operation2776,
        (api:"/groups/{group-id}/team/schedule/openShiftChangeRequests/{openShiftChangeRequest-id}",groupid: string,openShiftChangeRequestid: string):operation2777,
        (api:"/groups/{group-id}/team/schedule/openShiftChangeRequests/$count",groupid: string):operation2778,
        (api:"/groups/{group-id}/team/schedule/openShifts",groupid: string):operation2779,
        (api:"/groups/{group-id}/team/schedule/openShifts/{openShift-id}",groupid: string,openShiftid: string):operation2780,
        (api:"/groups/{group-id}/team/schedule/openShifts/$count",groupid: string):operation2781,
        (api:"/groups/{group-id}/team/schedule/schedulingGroups",groupid: string):operation2782,
        (api:"/groups/{group-id}/team/schedule/schedulingGroups/{schedulingGroup-id}",groupid: string,schedulingGroupid: string):operation2783,
        (api:"/groups/{group-id}/team/schedule/schedulingGroups/$count",groupid: string):operation2784,
        (api:"/groups/{group-id}/team/schedule/shifts",groupid: string):operation2785,
        (api:"/groups/{group-id}/team/schedule/shifts/{shift-id}",groupid: string,shiftid: string):operation2786,
        (api:"/groups/{group-id}/team/schedule/shifts/$count",groupid: string):operation2787,
        (api:"/groups/{group-id}/team/schedule/swapShiftsChangeRequests",groupid: string):operation2788,
        (api:"/groups/{group-id}/team/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}",groupid: string,swapShiftsChangeRequestid: string):operation2789,
        (api:"/groups/{group-id}/team/schedule/swapShiftsChangeRequests/$count",groupid: string):operation2790,
        (api:"/groups/{group-id}/team/schedule/timeOffReasons",groupid: string):operation2791,
        (api:"/groups/{group-id}/team/schedule/timeOffReasons/{timeOffReason-id}",groupid: string,timeOffReasonid: string):operation2792,
        (api:"/groups/{group-id}/team/schedule/timeOffReasons/$count",groupid: string):operation2793,
        (api:"/groups/{group-id}/team/schedule/timeOffRequests",groupid: string):operation2794,
        (api:"/groups/{group-id}/team/schedule/timeOffRequests/{timeOffRequest-id}",groupid: string,timeOffRequestid: string):operation2795,
        (api:"/groups/{group-id}/team/schedule/timeOffRequests/$count",groupid: string):operation2796,
        (api:"/groups/{group-id}/team/schedule/timesOff",groupid: string):operation2797,
        (api:"/groups/{group-id}/team/schedule/timesOff/{timeOff-id}",groupid: string,timeOffid: string):operation2798,
        (api:"/groups/{group-id}/team/schedule/timesOff/$count",groupid: string):operation2799,
        (api:"/groups/{group-id}/team/template",groupid: string):operation2800,
        (api:"/groups/{group-id}/threads",groupid: string):operation2801,
        (api:"/groups/{group-id}/transitiveMemberOf",groupid: string):operation2839,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}",groupid: string,directoryObjectid: string):operation2840,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation2841,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation2842,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation2843,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation2844,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation2845,
        (api:"/groups/{group-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation2846,
        (api:"/groups/{group-id}/transitiveMemberOf/$count",groupid: string):operation2847,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.application",groupid: string):operation2848,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.application/$count",groupid: string):operation2849,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.device",groupid: string):operation2850,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.device/$count",groupid: string):operation2851,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.group",groupid: string):operation2852,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.group/$count",groupid: string):operation2853,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.orgContact",groupid: string):operation2854,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.orgContact/$count",groupid: string):operation2855,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.servicePrincipal",groupid: string):operation2856,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.servicePrincipal/$count",groupid: string):operation2857,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.user",groupid: string):operation2858,
        (api:"/groups/{group-id}/transitiveMemberOf/microsoft.graph.user/$count",groupid: string):operation2859,
        (api:"/groups/{group-id}/transitiveMembers",groupid: string):operation2860,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}",groupid: string,directoryObjectid: string):operation2861,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.application",groupid: string,directoryObjectid: string):operation2862,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.device",groupid: string,directoryObjectid: string):operation2863,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.group",groupid: string,directoryObjectid: string):operation2864,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.orgContact",groupid: string,directoryObjectid: string):operation2865,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.servicePrincipal",groupid: string,directoryObjectid: string):operation2866,
        (api:"/groups/{group-id}/transitiveMembers/{directoryObject-id}/microsoft.graph.user",groupid: string,directoryObjectid: string):operation2867,
        (api:"/groups/{group-id}/transitiveMembers/$count",groupid: string):operation2868,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.application",groupid: string):operation2869,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.application/$count",groupid: string):operation2870,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.device",groupid: string):operation2871,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.device/$count",groupid: string):operation2872,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.group",groupid: string):operation2873,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.group/$count",groupid: string):operation2874,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.orgContact",groupid: string):operation2875,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.orgContact/$count",groupid: string):operation2876,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.servicePrincipal",groupid: string):operation2877,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.servicePrincipal/$count",groupid: string):operation2878,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.user",groupid: string):operation2879,
        (api:"/groups/{group-id}/transitiveMembers/microsoft.graph.user/$count",groupid: string):operation2880,
        (api:"/groups/$count"):operation2881,
        (api:"/groups/microsoft.graph.delta()"):operation2882,
        (api:"/groups/microsoft.graph.getAvailableExtensionProperties"):operation2883,
        (api:"/groups/microsoft.graph.getByIds"):operation2884,
        (api:"/groups/microsoft.graph.validateProperties"):operation2885,
        (api:"/groupLifecyclePolicies"):operation1430,
        (api:"/groupLifecyclePolicies/{groupLifecyclePolicy-id}",groupLifecyclePolicyid: string):operation1431,
        (api:"/groupLifecyclePolicies/{groupLifecyclePolicy-id}/microsoft.graph.addGroup",groupLifecyclePolicyid: string):operation1432,
        (api:"/groupLifecyclePolicies/{groupLifecyclePolicy-id}/microsoft.graph.removeGroup",groupLifecyclePolicyid: string):operation1433,
        (api:"/groupLifecyclePolicies/$count"):operation1434,
    
        (api:"/groupSettings"):operation2886,
        (api:"/groupSettings/{groupSetting-id}",groupSettingid: string):operation2887,
        (api:"/groupSettings/$count"):operation2888,
        (api:"/groupSettingTemplates"):operation2889,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}",groupSettingTemplateid: string):operation2890,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}/microsoft.graph.checkMemberGroups",groupSettingTemplateid: string):operation2891,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}/microsoft.graph.checkMemberObjects",groupSettingTemplateid: string):operation2892,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}/microsoft.graph.getMemberGroups",groupSettingTemplateid: string):operation2893,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}/microsoft.graph.getMemberObjects",groupSettingTemplateid: string):operation2894,
        (api:"/groupSettingTemplates/{groupSettingTemplate-id}/microsoft.graph.restore",groupSettingTemplateid: string):operation2895,
        (api:"/groupSettingTemplates/$count"):operation2896,
        (api:"/groupSettingTemplates/microsoft.graph.getAvailableExtensionProperties"):operation2897,
        (api:"/groupSettingTemplates/microsoft.graph.getByIds"):operation2898,
        (api:"/groupSettingTemplates/microsoft.graph.validateProperties"):operation2899,
    }
}

export { };