import { GraphApis } from "../../lib/src/rest/graphAPIs";

import { operation1448, operation1449, operation1450, operation1451, operation1452, operation1453, operation1454, operation1455, operation1456, operation1457, operation1458, operation1459, operation1460, operation1461, operation1462, operation1463, operation1464, operation1465, operation1466, operation1467, operation1468, operation1469, operation1470, operation1471, operation1472, operation1473, operation1474, operation1475, operation1476, operation1477, operation1478, operation1479, operation1480, operation1481, operation1482, operation1483, operation1484, operation1485, operation1486, operation1487, operation1488, operation1489, operation1490, operation1491, operation1492, operation1493, operation1494, operation1495, operation1496, operation1497, operation1556, operation1557, operation1558, operation1559, operation1560, operation1561, operation1562, operation1563, operation1564, operation1565, operation1566, operation1567, operation1568, operation1569, operation1570, operation1571, operation1572, operation1573, operation1574, operation1575, operation1576, operation1577, operation1578, operation1579, operation1580, operation1581, operation1582, operation1583, operation1584, operation1585, operation1586, operation1587, operation1588, operation1589, operation1590, operation1591, operation1592, operation1593, operation1594, operation1595, operation1596, operation1597, operation1598, operation1599, operation1600, operation1601, operation1602, operation1603, operation1604, operation1605, operation3349, operation3350, operation3351, operation3352, operation3353, operation3354, operation3355, operation3356, operation3357, operation3358, operation3359, operation3360, operation3361, operation3362, operation3363, operation3364, operation3365, operation3366, operation3367, operation3368, operation3369, operation3370, operation3371, operation3372, operation3373, operation3374, operation3375, operation3376, operation3377, operation3378, operation3379, operation3380, operation3381, operation3382, operation3383, operation3384, operation3385, operation3386, operation3387, operation3388, operation3389, operation3390, operation3391, operation3392, operation3393, operation3394, operation3395, operation3396, operation3397, operation3398, operation3464, operation3465, operation3466, operation3467, operation3468, operation3469, operation3470, operation3471, operation3472, operation3473, operation3474, operation3475, operation3476, operation3477, operation3478, operation3479, operation3480, operation3481, operation3482, operation3483, operation3484, operation3485, operation3486, operation3487, operation3488, operation3489, operation3490, operation3491, operation3492, operation3493, operation3494, operation3495, operation3496, operation3497, operation3498, operation3499, operation3500, operation3501, operation3502, operation3503, operation3504, operation3505, operation3506, operation3507, operation3508, operation3509, operation3510, operation3511, operation3512, operation3513, operation3579, operation3580, operation3581, operation3582, operation3583, operation3584, operation3585, operation3586, operation3587, operation3588, operation3589, operation3590, operation3591, operation3592, operation3593, operation3594, operation3595, operation3596, operation3597, operation3598, operation3599, operation3600, operation3601, operation3602, operation3603, operation3604, operation3605, operation3606, operation3607, operation3608, operation3609, operation3610, operation3611, operation3612, operation3613, operation3614, operation3615, operation3616, operation3617, operation3618, operation3619, operation3620, operation3621, operation3622, operation3623, operation3624, operation3625, operation3626, operation3627, operation3628, operation3688, operation3689, operation3690, operation3691, operation3692, operation3693, operation3694, operation3695, operation3696, operation3697, operation3698, operation3699, operation3700, operation3701, operation3702, operation3703, operation3704, operation3705, operation3706, operation3707, operation3708, operation3709, operation3710, operation3711, operation3712, operation3713, operation3714, operation3715, operation3716, operation3717, operation3718, operation3719, operation3720, operation3721, operation3722, operation3723, operation3724, operation3725, operation3726, operation3727, operation3728, operation3729, operation3730, operation3731, operation3732, operation3733, operation3734, operation3735, operation3736, operation3737, operation6362, operation6363, operation6364, operation6365, operation6366, operation6367, operation6368, operation6369, operation6370, operation6371, operation6372, operation6373, operation6374, operation6375, operation6376, operation6377, operation6378, operation6379, operation6380, operation6381, operation6382, operation6383, operation6384, operation6385, operation6386, operation6387, operation6388, operation6389, operation6390, operation6391, operation6392, operation6393, operation6394, operation6395, operation6396, operation6397, operation6398, operation6399, operation6400, operation6401, operation6402, operation6403, operation6404, operation6405, operation6406, operation6407, operation6408, operation6409, operation6410, operation6411, operation6592, operation6593, operation6594, operation6595, operation6596, operation6597, operation6598, operation6599, operation6600, operation6601, operation6602, operation6603, operation6604, operation6605, operation6606, operation6607, operation6608, operation6609, operation6610, operation6611, operation6612, operation6613, operation6614, operation6615, operation6616, operation6617, operation6618, operation6619, operation6620, operation6621, operation6622, operation6623, operation6624, operation6625, operation6626, operation6627, operation6628, operation6629, operation6630, operation6631, operation6632, operation6633, operation6634, operation6635, operation6636, operation6637, operation6638, operation6639, operation6640, operation6641, operation6701, operation6702, operation6703, operation6704, operation6705, operation6706, operation6707, operation6708, operation6709, operation6710, operation6711, operation6712, operation6713, operation6714, operation6715, operation6716, operation6717, operation6718, operation6719, operation6720, operation6721, operation6722, operation6723, operation6724, operation6725, operation6726, operation6727, operation6728, operation6729, operation6730, operation6731, operation6732, operation6733, operation6734, operation6735, operation6736, operation6737, operation6738, operation6739, operation6740, operation6741, operation6742, operation6743, operation6744, operation6745, operation6746, operation6747, operation6748, operation6749, operation6750 } from "../../lib/src/rest/operations";

declare module "../../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api: "/groups/{group-id}/calendar/calendarView", groupid: string): operation1448,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}", groupid: string, eventid: string): operation1449,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/attachments", groupid: string, eventid: string): operation1450,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/attachments/{attachment-id}", groupid: string, eventid: string, attachmentid: string): operation1451,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/attachments/$count", groupid: string, eventid: string): operation1452,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", groupid: string, eventid: string): operation1453,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/calendar", groupid: string, eventid: string): operation1454,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/extensions", groupid: string, eventid: string): operation1455,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/extensions/{extension-id}", groupid: string, eventid: string, extensionid: string): operation1456,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/extensions/$count", groupid: string, eventid: string): operation1457,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances", groupid: string, eventid: string): operation1458,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}", groupid: string, eventid: string, eventid1: string): operation1459,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments", groupid: string, eventid: string, eventid1: string): operation1460,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", groupid: string, eventid: string, eventid1: string, attachmentid: string): operation1461,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/$count", groupid: string, eventid: string, eventid1: string): operation1462,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", groupid: string, eventid: string, eventid1: string): operation1463,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/calendar", groupid: string, eventid: string, eventid1: string): operation1464,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions", groupid: string, eventid: string, eventid1: string): operation1465,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", groupid: string, eventid: string, eventid1: string, extensionid: string): operation1466,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/$count", groupid: string, eventid: string, eventid1: string): operation1467,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", groupid: string, eventid: string, eventid1: string): operation1468,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", groupid: string, eventid: string, eventid1: string): operation1469,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", groupid: string, eventid: string, eventid1: string): operation1470,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", groupid: string, eventid: string, eventid1: string): operation1471,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", groupid: string, eventid: string, eventid1: string): operation1472,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", groupid: string, eventid: string, eventid1: string): operation1473,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", groupid: string, eventid: string, eventid1: string): operation1474,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", groupid: string, eventid: string, eventid1: string): operation1475,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation1476,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", groupid: string, eventid: string, eventid1: string): operation1477,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", groupid: string, eventid: string, eventid1: string): operation1478,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation1479,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", groupid: string, eventid: string, eventid1: string): operation1480,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/$count", groupid: string, eventid: string): operation1481,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/instances/microsoft.graph.delta()", groupid: string, eventid: string): operation1482,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.accept", groupid: string, eventid: string): operation1483,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.cancel", groupid: string, eventid: string): operation1484,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.decline", groupid: string, eventid: string): operation1485,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.dismissReminder", groupid: string, eventid: string): operation1486,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.forward", groupid: string, eventid: string): operation1487,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.snoozeReminder", groupid: string, eventid: string): operation1488,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/microsoft.graph.tentativelyAccept", groupid: string, eventid: string): operation1489,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties", groupid: string, eventid: string): operation1490,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation1491,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties/$count", groupid: string, eventid: string): operation1492,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties", groupid: string, eventid: string): operation1493,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation1494,
        (api: "/groups/{group-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties/$count", groupid: string, eventid: string): operation1495,
        (api: "/groups/{group-id}/calendar/calendarView/$count", groupid: string): operation1496,
        (api: "/groups/{group-id}/calendar/calendarView/microsoft.graph.delta()", groupid: string): operation1497,

        (api: "/groups/{group-id}/calendarView", groupid: string): operation1556,
        (api: "/groups/{group-id}/calendarView/{event-id}", groupid: string, eventid: string): operation1557,
        (api: "/groups/{group-id}/calendarView/{event-id}/attachments", groupid: string, eventid: string): operation1558,
        (api: "/groups/{group-id}/calendarView/{event-id}/attachments/{attachment-id}", groupid: string, eventid: string, attachmentid: string): operation1559,
        (api: "/groups/{group-id}/calendarView/{event-id}/attachments/$count", groupid: string, eventid: string): operation1560,
        (api: "/groups/{group-id}/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", groupid: string, eventid: string): operation1561,
        (api: "/groups/{group-id}/calendarView/{event-id}/calendar", groupid: string, eventid: string): operation1562,
        (api: "/groups/{group-id}/calendarView/{event-id}/extensions", groupid: string, eventid: string): operation1563,
        (api: "/groups/{group-id}/calendarView/{event-id}/extensions/{extension-id}", groupid: string, eventid: string, extensionid: string): operation1564,
        (api: "/groups/{group-id}/calendarView/{event-id}/extensions/$count", groupid: string, eventid: string): operation1565,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances", groupid: string, eventid: string): operation1566,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}", groupid: string, eventid: string, eventid1: string): operation1567,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/attachments", groupid: string, eventid: string, eventid1: string): operation1568,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", groupid: string, eventid: string, eventid1: string, attachmentid: string): operation1569,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/attachments/$count", groupid: string, eventid: string, eventid1: string): operation1570,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", groupid: string, eventid: string, eventid1: string): operation1571,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/calendar", groupid: string, eventid: string, eventid1: string): operation1572,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/extensions", groupid: string, eventid: string, eventid1: string): operation1573,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", groupid: string, eventid: string, eventid1: string, extensionid: string): operation1574,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count", groupid: string, eventid: string, eventid1: string): operation1575,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", groupid: string, eventid: string, eventid1: string): operation1576,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", groupid: string, eventid: string, eventid1: string): operation1577,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", groupid: string, eventid: string, eventid1: string): operation1578,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", groupid: string, eventid: string, eventid1: string): operation1579,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", groupid: string, eventid: string, eventid1: string): operation1580,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", groupid: string, eventid: string, eventid1: string): operation1581,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", groupid: string, eventid: string, eventid1: string): operation1582,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", groupid: string, eventid: string, eventid1: string): operation1583,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation1584,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", groupid: string, eventid: string, eventid1: string): operation1585,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", groupid: string, eventid: string, eventid1: string): operation1586,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation1587,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", groupid: string, eventid: string, eventid1: string): operation1588,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/$count", groupid: string, eventid: string): operation1589,
        (api: "/groups/{group-id}/calendarView/{event-id}/instances/microsoft.graph.delta()", groupid: string, eventid: string): operation1590,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.accept", groupid: string, eventid: string): operation1591,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.cancel", groupid: string, eventid: string): operation1592,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.decline", groupid: string, eventid: string): operation1593,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.dismissReminder", groupid: string, eventid: string): operation1594,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.forward", groupid: string, eventid: string): operation1595,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.snoozeReminder", groupid: string, eventid: string): operation1596,
        (api: "/groups/{group-id}/calendarView/{event-id}/microsoft.graph.tentativelyAccept", groupid: string, eventid: string): operation1597,
        (api: "/groups/{group-id}/calendarView/{event-id}/multiValueExtendedProperties", groupid: string, eventid: string): operation1598,
        (api: "/groups/{group-id}/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation1599,
        (api: "/groups/{group-id}/calendarView/{event-id}/multiValueExtendedProperties/$count", groupid: string, eventid: string): operation1600,
        (api: "/groups/{group-id}/calendarView/{event-id}/singleValueExtendedProperties", groupid: string, eventid: string): operation1601,
        (api: "/groups/{group-id}/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation1602,
        (api: "/groups/{group-id}/calendarView/{event-id}/singleValueExtendedProperties/$count", groupid: string, eventid: string): operation1603,
        (api: "/groups/{group-id}/calendarView/$count", groupid: string): operation1604,
        (api: "/groups/{group-id}/calendarView/microsoft.graph.delta()", groupid: string): operation1605,

        (api: "/me/calendar/calendarView"): operation3349,
        (api: "/me/calendar/calendarView/{event-id}", eventid: string): operation3350,
        (api: "/me/calendar/calendarView/{event-id}/attachments", eventid: string): operation3351,
        (api: "/me/calendar/calendarView/{event-id}/attachments/{attachment-id}", eventid: string, attachmentid: string): operation3352,
        (api: "/me/calendar/calendarView/{event-id}/attachments/$count", eventid: string): operation3353,
        (api: "/me/calendar/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", eventid: string): operation3354,
        (api: "/me/calendar/calendarView/{event-id}/calendar", eventid: string): operation3355,
        (api: "/me/calendar/calendarView/{event-id}/extensions", eventid: string): operation3356,
        (api: "/me/calendar/calendarView/{event-id}/extensions/{extension-id}", eventid: string, extensionid: string): operation3357,
        (api: "/me/calendar/calendarView/{event-id}/extensions/$count", eventid: string): operation3358,
        (api: "/me/calendar/calendarView/{event-id}/instances", eventid: string): operation3359,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}", eventid: string, eventid1: string): operation3360,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/attachments", eventid: string, eventid1: string): operation3361,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", eventid: string, eventid1: string, attachmentid: string): operation3362,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/$count", eventid: string, eventid1: string): operation3363,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", eventid: string, eventid1: string): operation3364,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/calendar", eventid: string, eventid1: string): operation3365,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/extensions", eventid: string, eventid1: string): operation3366,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", eventid: string, eventid1: string, extensionid: string): operation3367,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/$count", eventid: string, eventid1: string): operation3368,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", eventid: string, eventid1: string): operation3369,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", eventid: string, eventid1: string): operation3370,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", eventid: string, eventid1: string): operation3371,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", eventid: string, eventid1: string): operation3372,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", eventid: string, eventid1: string): operation3373,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", eventid: string, eventid1: string): operation3374,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", eventid: string, eventid1: string): operation3375,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", eventid: string, eventid1: string): operation3376,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation3377,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", eventid: string, eventid1: string): operation3378,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", eventid: string, eventid1: string): operation3379,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation3380,
        (api: "/me/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", eventid: string, eventid1: string): operation3381,
        (api: "/me/calendar/calendarView/{event-id}/instances/$count", eventid: string): operation3382,
        (api: "/me/calendar/calendarView/{event-id}/instances/microsoft.graph.delta()", eventid: string): operation3383,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.accept", eventid: string): operation3384,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.cancel", eventid: string): operation3385,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.decline", eventid: string): operation3386,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.dismissReminder", eventid: string): operation3387,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.forward", eventid: string): operation3388,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.snoozeReminder", eventid: string): operation3389,
        (api: "/me/calendar/calendarView/{event-id}/microsoft.graph.tentativelyAccept", eventid: string): operation3390,
        (api: "/me/calendar/calendarView/{event-id}/multiValueExtendedProperties", eventid: string): operation3391,
        (api: "/me/calendar/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", eventid: string, multiValueLegacyExtendedPropertyid: string): operation3392,
        (api: "/me/calendar/calendarView/{event-id}/multiValueExtendedProperties/$count", eventid: string): operation3393,
        (api: "/me/calendar/calendarView/{event-id}/singleValueExtendedProperties", eventid: string): operation3394,
        (api: "/me/calendar/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", eventid: string, singleValueLegacyExtendedPropertyid: string): operation3395,
        (api: "/me/calendar/calendarView/{event-id}/singleValueExtendedProperties/$count", eventid: string): operation3396,
        (api: "/me/calendar/calendarView/$count"): operation3397,
        (api: "/me/calendar/calendarView/microsoft.graph.delta()"): operation3398,

        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView", calendarGroupid: string, calendarid: string): operation3464,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}", calendarGroupid: string, calendarid: string, eventid: string): operation3465,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments", calendarGroupid: string, calendarid: string, eventid: string): operation3466,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/{attachment-id}", calendarGroupid: string, calendarid: string, eventid: string, attachmentid: string): operation3467,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/$count", calendarGroupid: string, calendarid: string, eventid: string): operation3468,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", calendarGroupid: string, calendarid: string, eventid: string): operation3469,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/calendar", calendarGroupid: string, calendarid: string, eventid: string): operation3470,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions", calendarGroupid: string, calendarid: string, eventid: string): operation3471,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions/{extension-id}", calendarGroupid: string, calendarid: string, eventid: string, extensionid: string): operation3472,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions/$count", calendarGroupid: string, calendarid: string, eventid: string): operation3473,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances", calendarGroupid: string, calendarid: string, eventid: string): operation3474,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3475,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3476,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string, attachmentid: string): operation3477,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/$count", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3478,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3479,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/calendar", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3480,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3481,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string, extensionid: string): operation3482,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3483,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3484,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3485,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3486,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3487,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3488,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3489,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3490,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3491,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation3492,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3493,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3494,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation3495,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", calendarGroupid: string, calendarid: string, eventid: string, eventid1: string): operation3496,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/$count", calendarGroupid: string, calendarid: string, eventid: string): operation3497,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/microsoft.graph.delta()", calendarGroupid: string, calendarid: string, eventid: string): operation3498,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.accept", calendarGroupid: string, calendarid: string, eventid: string): operation3499,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.cancel", calendarGroupid: string, calendarid: string, eventid: string): operation3500,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.decline", calendarGroupid: string, calendarid: string, eventid: string): operation3501,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.dismissReminder", calendarGroupid: string, calendarid: string, eventid: string): operation3502,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.forward", calendarGroupid: string, calendarid: string, eventid: string): operation3503,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.snoozeReminder", calendarGroupid: string, calendarid: string, eventid: string): operation3504,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.tentativelyAccept", calendarGroupid: string, calendarid: string, eventid: string): operation3505,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties", calendarGroupid: string, calendarid: string, eventid: string): operation3506,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", calendarGroupid: string, calendarid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation3507,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/$count", calendarGroupid: string, calendarid: string, eventid: string): operation3508,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties", calendarGroupid: string, calendarid: string, eventid: string): operation3509,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", calendarGroupid: string, calendarid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation3510,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/$count", calendarGroupid: string, calendarid: string, eventid: string): operation3511,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/$count", calendarGroupid: string, calendarid: string): operation3512,
        (api: "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/microsoft.graph.delta()", calendarGroupid: string, calendarid: string): operation3513,

        (api: "/me/calendars/{calendar-id}/calendarView", calendarid: string): operation3579,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}", calendarid: string, eventid: string): operation3580,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/attachments", calendarid: string, eventid: string): operation3581,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/attachments/{attachment-id}", calendarid: string, eventid: string, attachmentid: string): operation3582,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/attachments/$count", calendarid: string, eventid: string): operation3583,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", calendarid: string, eventid: string): operation3584,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/calendar", calendarid: string, eventid: string): operation3585,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/extensions", calendarid: string, eventid: string): operation3586,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/extensions/{extension-id}", calendarid: string, eventid: string, extensionid: string): operation3587,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/extensions/$count", calendarid: string, eventid: string): operation3588,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances", calendarid: string, eventid: string): operation3589,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}", calendarid: string, eventid: string, eventid1: string): operation3590,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments", calendarid: string, eventid: string, eventid1: string): operation3591,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", calendarid: string, eventid: string, eventid1: string, attachmentid: string): operation3592,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/$count", calendarid: string, eventid: string, eventid1: string): operation3593,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", calendarid: string, eventid: string, eventid1: string): operation3594,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/calendar", calendarid: string, eventid: string, eventid1: string): operation3595,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions", calendarid: string, eventid: string, eventid1: string): operation3596,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", calendarid: string, eventid: string, eventid1: string, extensionid: string): operation3597,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count", calendarid: string, eventid: string, eventid1: string): operation3598,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", calendarid: string, eventid: string, eventid1: string): operation3599,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", calendarid: string, eventid: string, eventid1: string): operation3600,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", calendarid: string, eventid: string, eventid1: string): operation3601,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", calendarid: string, eventid: string, eventid1: string): operation3602,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", calendarid: string, eventid: string, eventid1: string): operation3603,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", calendarid: string, eventid: string, eventid1: string): operation3604,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", calendarid: string, eventid: string, eventid1: string): operation3605,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", calendarid: string, eventid: string, eventid1: string): operation3606,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", calendarid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation3607,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", calendarid: string, eventid: string, eventid1: string): operation3608,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", calendarid: string, eventid: string, eventid1: string): operation3609,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", calendarid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation3610,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", calendarid: string, eventid: string, eventid1: string): operation3611,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/$count", calendarid: string, eventid: string): operation3612,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/instances/microsoft.graph.delta()", calendarid: string, eventid: string): operation3613,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.accept", calendarid: string, eventid: string): operation3614,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.cancel", calendarid: string, eventid: string): operation3615,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.decline", calendarid: string, eventid: string): operation3616,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.dismissReminder", calendarid: string, eventid: string): operation3617,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.forward", calendarid: string, eventid: string): operation3618,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.snoozeReminder", calendarid: string, eventid: string): operation3619,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.tentativelyAccept", calendarid: string, eventid: string): operation3620,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties", calendarid: string, eventid: string): operation3621,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", calendarid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation3622,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/$count", calendarid: string, eventid: string): operation3623,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties", calendarid: string, eventid: string): operation3624,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", calendarid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation3625,
        (api: "/me/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/$count", calendarid: string, eventid: string): operation3626,
        (api: "/me/calendars/{calendar-id}/calendarView/$count", calendarid: string): operation3627,
        (api: "/me/calendars/{calendar-id}/calendarView/microsoft.graph.delta()", calendarid: string): operation3628,

        (api: "/me/calendarView"): operation3688,
        (api: "/me/calendarView/{event-id}", eventid: string): operation3689,
        (api: "/me/calendarView/{event-id}/attachments", eventid: string): operation3690,
        (api: "/me/calendarView/{event-id}/attachments/{attachment-id}", eventid: string, attachmentid: string): operation3691,
        (api: "/me/calendarView/{event-id}/attachments/$count", eventid: string): operation3692,
        (api: "/me/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", eventid: string): operation3693,
        (api: "/me/calendarView/{event-id}/calendar", eventid: string): operation3694,
        (api: "/me/calendarView/{event-id}/extensions", eventid: string): operation3695,
        (api: "/me/calendarView/{event-id}/extensions/{extension-id}", eventid: string, extensionid: string): operation3696,
        (api: "/me/calendarView/{event-id}/extensions/$count", eventid: string): operation3697,
        (api: "/me/calendarView/{event-id}/instances", eventid: string): operation3698,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}", eventid: string, eventid1: string): operation3699,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/attachments", eventid: string, eventid1: string): operation3700,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", eventid: string, eventid1: string, attachmentid: string): operation3701,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/attachments/$count", eventid: string, eventid1: string): operation3702,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", eventid: string, eventid1: string): operation3703,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/calendar", eventid: string, eventid1: string): operation3704,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/extensions", eventid: string, eventid1: string): operation3705,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", eventid: string, eventid1: string, extensionid: string): operation3706,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/extensions/$count", eventid: string, eventid1: string): operation3707,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", eventid: string, eventid1: string): operation3708,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", eventid: string, eventid1: string): operation3709,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", eventid: string, eventid1: string): operation3710,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", eventid: string, eventid1: string): operation3711,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", eventid: string, eventid1: string): operation3712,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", eventid: string, eventid1: string): operation3713,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", eventid: string, eventid1: string): operation3714,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", eventid: string, eventid1: string): operation3715,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation3716,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", eventid: string, eventid1: string): operation3717,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", eventid: string, eventid1: string): operation3718,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation3719,
        (api: "/me/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", eventid: string, eventid1: string): operation3720,
        (api: "/me/calendarView/{event-id}/instances/$count", eventid: string): operation3721,
        (api: "/me/calendarView/{event-id}/instances/microsoft.graph.delta()", eventid: string): operation3722,
        (api: "/me/calendarView/{event-id}/microsoft.graph.accept", eventid: string): operation3723,
        (api: "/me/calendarView/{event-id}/microsoft.graph.cancel", eventid: string): operation3724,
        (api: "/me/calendarView/{event-id}/microsoft.graph.decline", eventid: string): operation3725,
        (api: "/me/calendarView/{event-id}/microsoft.graph.dismissReminder", eventid: string): operation3726,
        (api: "/me/calendarView/{event-id}/microsoft.graph.forward", eventid: string): operation3727,
        (api: "/me/calendarView/{event-id}/microsoft.graph.snoozeReminder", eventid: string): operation3728,
        (api: "/me/calendarView/{event-id}/microsoft.graph.tentativelyAccept", eventid: string): operation3729,
        (api: "/me/calendarView/{event-id}/multiValueExtendedProperties", eventid: string): operation3730,
        (api: "/me/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", eventid: string, multiValueLegacyExtendedPropertyid: string): operation3731,
        (api: "/me/calendarView/{event-id}/multiValueExtendedProperties/$count", eventid: string): operation3732,
        (api: "/me/calendarView/{event-id}/singleValueExtendedProperties", eventid: string): operation3733,
        (api: "/me/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", eventid: string, singleValueLegacyExtendedPropertyid: string): operation3734,
        (api: "/me/calendarView/{event-id}/singleValueExtendedProperties/$count", eventid: string): operation3735,
        (api: "/me/calendarView/$count"): operation3736,
        (api: "/me/calendarView/microsoft.graph.delta()"): operation3737,
        (api: "/users/{user-id}/calendar/calendarView", userid: string): operation6362,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}", userid: string, eventid: string): operation6363,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/attachments", userid: string, eventid: string): operation6364,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/attachments/{attachment-id}", userid: string, eventid: string, attachmentid: string): operation6365,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/attachments/$count", userid: string, eventid: string): operation6366,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", userid: string, eventid: string): operation6367,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/calendar", userid: string, eventid: string): operation6368,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/extensions", userid: string, eventid: string): operation6369,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/extensions/{extension-id}", userid: string, eventid: string, extensionid: string): operation6370,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/extensions/$count", userid: string, eventid: string): operation6371,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances", userid: string, eventid: string): operation6372,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}", userid: string, eventid: string, eventid1: string): operation6373,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments", userid: string, eventid: string, eventid1: string): operation6374,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", userid: string, eventid: string, eventid1: string, attachmentid: string): operation6375,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/$count", userid: string, eventid: string, eventid1: string): operation6376,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", userid: string, eventid: string, eventid1: string): operation6377,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/calendar", userid: string, eventid: string, eventid1: string): operation6378,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions", userid: string, eventid: string, eventid1: string): operation6379,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", userid: string, eventid: string, eventid1: string, extensionid: string): operation6380,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/extensions/$count", userid: string, eventid: string, eventid1: string): operation6381,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", userid: string, eventid: string, eventid1: string): operation6382,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", userid: string, eventid: string, eventid1: string): operation6383,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", userid: string, eventid: string, eventid1: string): operation6384,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", userid: string, eventid: string, eventid1: string): operation6385,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", userid: string, eventid: string, eventid1: string): operation6386,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", userid: string, eventid: string, eventid1: string): operation6387,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", userid: string, eventid: string, eventid1: string): operation6388,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", userid: string, eventid: string, eventid1: string): operation6389,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation6390,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", userid: string, eventid: string, eventid1: string): operation6391,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", userid: string, eventid: string, eventid1: string): operation6392,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation6393,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", userid: string, eventid: string, eventid1: string): operation6394,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/$count", userid: string, eventid: string): operation6395,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/instances/microsoft.graph.delta()", userid: string, eventid: string): operation6396,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.accept", userid: string, eventid: string): operation6397,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.cancel", userid: string, eventid: string): operation6398,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.decline", userid: string, eventid: string): operation6399,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.dismissReminder", userid: string, eventid: string): operation6400,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.forward", userid: string, eventid: string): operation6401,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.snoozeReminder", userid: string, eventid: string): operation6402,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/microsoft.graph.tentativelyAccept", userid: string, eventid: string): operation6403,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties", userid: string, eventid: string): operation6404,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation6405,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/multiValueExtendedProperties/$count", userid: string, eventid: string): operation6406,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties", userid: string, eventid: string): operation6407,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation6408,
        (api: "/users/{user-id}/calendar/calendarView/{event-id}/singleValueExtendedProperties/$count", userid: string, eventid: string): operation6409,
        (api: "/users/{user-id}/calendar/calendarView/$count", userid: string): operation6410,
        (api: "/users/{user-id}/calendar/calendarView/microsoft.graph.delta()", userid: string): operation6411,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView", userid: string, calendarid: string): operation6592,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}", userid: string, calendarid: string, eventid: string): operation6593,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments", userid: string, calendarid: string, eventid: string): operation6594,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/{attachment-id}", userid: string, calendarid: string, eventid: string, attachmentid: string): operation6595,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/$count", userid: string, calendarid: string, eventid: string): operation6596,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession", userid: string, calendarid: string, eventid: string): operation6597,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/calendar", userid: string, calendarid: string, eventid: string): operation6598,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions", userid: string, calendarid: string, eventid: string): operation6599,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions/{extension-id}", userid: string, calendarid: string, eventid: string, extensionid: string): operation6600,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/extensions/$count", userid: string, calendarid: string, eventid: string): operation6601,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances", userid: string, calendarid: string, eventid: string): operation6602,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}", userid: string, calendarid: string, eventid: string, eventid1: string): operation6603,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments", userid: string, calendarid: string, eventid: string, eventid1: string): operation6604,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}", userid: string, calendarid: string, eventid: string, eventid1: string, attachmentid: string): operation6605,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/$count", userid: string, calendarid: string, eventid: string, eventid1: string): operation6606,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession", userid: string, calendarid: string, eventid: string, eventid1: string): operation6607,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/calendar", userid: string, calendarid: string, eventid: string, eventid1: string): operation6608,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions", userid: string, calendarid: string, eventid: string, eventid1: string): operation6609,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}", userid: string, calendarid: string, eventid: string, eventid1: string, extensionid: string): operation6610,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count", userid: string, calendarid: string, eventid: string, eventid1: string): operation6611,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept", userid: string, calendarid: string, eventid: string, eventid1: string): operation6612,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel", userid: string, calendarid: string, eventid: string, eventid1: string): operation6613,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline", userid: string, calendarid: string, eventid: string, eventid1: string): operation6614,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder", userid: string, calendarid: string, eventid: string, eventid1: string): operation6615,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward", userid: string, calendarid: string, eventid: string, eventid1: string): operation6616,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder", userid: string, calendarid: string, eventid: string, eventid1: string): operation6617,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept", userid: string, calendarid: string, eventid: string, eventid1: string): operation6618,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties", userid: string, calendarid: string, eventid: string, eventid1: string): operation6619,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, calendarid: string, eventid: string, eventid1: string, multiValueLegacyExtendedPropertyid: string): operation6620,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count", userid: string, calendarid: string, eventid: string, eventid1: string): operation6621,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties", userid: string, calendarid: string, eventid: string, eventid1: string): operation6622,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, calendarid: string, eventid: string, eventid1: string, singleValueLegacyExtendedPropertyid: string): operation6623,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count", userid: string, calendarid: string, eventid: string, eventid1: string): operation6624,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/$count", userid: string, calendarid: string, eventid: string): operation6625,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/microsoft.graph.delta()", userid: string, calendarid: string, eventid: string): operation6626,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.accept", userid: string, calendarid: string, eventid: string): operation6627,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.cancel", userid: string, calendarid: string, eventid: string): operation6628,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.decline", userid: string, calendarid: string, eventid: string): operation6629,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.dismissReminder", userid: string, calendarid: string, eventid: string): operation6630,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.forward", userid: string, calendarid: string, eventid: string): operation6631,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.snoozeReminder", userid: string, calendarid: string, eventid: string): operation6632,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/microsoft.graph.tentativelyAccept", userid: string, calendarid: string, eventid: string): operation6633,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties", userid: string, calendarid: string, eventid: string): operation6634,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", userid: string, calendarid: string, eventid: string, multiValueLegacyExtendedPropertyid: string): operation6635,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/multiValueExtendedProperties/$count", userid: string, calendarid: string, eventid: string): operation6636,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties", userid: string, calendarid: string, eventid: string): operation6637,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", userid: string, calendarid: string, eventid: string, singleValueLegacyExtendedPropertyid: string): operation6638,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/{event-id}/singleValueExtendedProperties/$count", userid: string, calendarid: string, eventid: string): operation6639,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/$count", userid: string, calendarid: string): operation6640,
        (api: "/users/{user-id}/calendars/{calendar-id}/calendarView/microsoft.graph.delta()", userid: string, calendarid: string): operation6641,
        (api:"/users/{user-id}/calendarView",userid: string):operation6701,
    (api:"/users/{user-id}/calendarView/{event-id}",userid: string,eventid: string):operation6702,
    (api:"/users/{user-id}/calendarView/{event-id}/attachments",userid: string,eventid: string):operation6703,
    (api:"/users/{user-id}/calendarView/{event-id}/attachments/{attachment-id}",userid: string,eventid: string,attachmentid: string):operation6704,
    (api:"/users/{user-id}/calendarView/{event-id}/attachments/$count",userid: string,eventid: string):operation6705,
    (api:"/users/{user-id}/calendarView/{event-id}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string):operation6706,
    (api:"/users/{user-id}/calendarView/{event-id}/calendar",userid: string,eventid: string):operation6707,
    (api:"/users/{user-id}/calendarView/{event-id}/extensions",userid: string,eventid: string):operation6708,
    (api:"/users/{user-id}/calendarView/{event-id}/extensions/{extension-id}",userid: string,eventid: string,extensionid: string):operation6709,
    (api:"/users/{user-id}/calendarView/{event-id}/extensions/$count",userid: string,eventid: string):operation6710,
    (api:"/users/{user-id}/calendarView/{event-id}/instances",userid: string,eventid: string):operation6711,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}",userid: string,eventid: string,eventid1: string):operation6712,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/attachments",userid: string,eventid: string,eventid1: string):operation6713,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/attachments/{attachment-id}",userid: string,eventid: string,eventid1: string,attachmentid: string):operation6714,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/attachments/$count",userid: string,eventid: string,eventid1: string):operation6715,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/attachments/microsoft.graph.createUploadSession",userid: string,eventid: string,eventid1: string):operation6716,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/calendar",userid: string,eventid: string,eventid1: string):operation6717,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/extensions",userid: string,eventid: string,eventid1: string):operation6718,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/extensions/{extension-id}",userid: string,eventid: string,eventid1: string,extensionid: string):operation6719,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count",userid: string,eventid: string,eventid1: string):operation6720,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.accept",userid: string,eventid: string,eventid1: string):operation6721,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.cancel",userid: string,eventid: string,eventid1: string):operation6722,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.decline",userid: string,eventid: string,eventid1: string):operation6723,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.dismissReminder",userid: string,eventid: string,eventid1: string):operation6724,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.forward",userid: string,eventid: string,eventid1: string):operation6725,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.snoozeReminder",userid: string,eventid: string,eventid1: string):operation6726,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/microsoft.graph.tentativelyAccept",userid: string,eventid: string,eventid1: string):operation6727,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation6728,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,multiValueLegacyExtendedPropertyid: string):operation6729,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/multiValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation6730,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties",userid: string,eventid: string,eventid1: string):operation6731,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,eventid1: string,singleValueLegacyExtendedPropertyid: string):operation6732,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/{event-id1}/singleValueExtendedProperties/$count",userid: string,eventid: string,eventid1: string):operation6733,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/$count",userid: string,eventid: string):operation6734,
    (api:"/users/{user-id}/calendarView/{event-id}/instances/microsoft.graph.delta()",userid: string,eventid: string):operation6735,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.accept",userid: string,eventid: string):operation6736,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.cancel",userid: string,eventid: string):operation6737,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.decline",userid: string,eventid: string):operation6738,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.dismissReminder",userid: string,eventid: string):operation6739,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.forward",userid: string,eventid: string):operation6740,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.snoozeReminder",userid: string,eventid: string):operation6741,
    (api:"/users/{user-id}/calendarView/{event-id}/microsoft.graph.tentativelyAccept",userid: string,eventid: string):operation6742,
    (api:"/users/{user-id}/calendarView/{event-id}/multiValueExtendedProperties",userid: string,eventid: string):operation6743,
    (api:"/users/{user-id}/calendarView/{event-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}",userid: string,eventid: string,multiValueLegacyExtendedPropertyid: string):operation6744,
    (api:"/users/{user-id}/calendarView/{event-id}/multiValueExtendedProperties/$count",userid: string,eventid: string):operation6745,
    (api:"/users/{user-id}/calendarView/{event-id}/singleValueExtendedProperties",userid: string,eventid: string):operation6746,
    (api:"/users/{user-id}/calendarView/{event-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}",userid: string,eventid: string,singleValueLegacyExtendedPropertyid: string):operation6747,
    (api:"/users/{user-id}/calendarView/{event-id}/singleValueExtendedProperties/$count",userid: string,eventid: string):operation6748,
    (api:"/users/{user-id}/calendarView/$count",userid: string):operation6749,
    (api:"/users/{user-id}/calendarView/microsoft.graph.delta()",userid: string):operation6750,
    }
}

export { }