import { GraphApis } from "../../lib/src/rest/graphAPIs";

import { operation1606, operation1607, operation1608, operation1609, operation1610, operation1611, operation1612, operation1613, operation1614, operation1615, operation1616, operation1617, operation1618, operation1619, operation1620, operation1621, operation1622, operation1623, operation1624, operation1625, operation1626, operation1627, operation1628, operation1629, operation1630, operation1631, operation1632, operation1633, operation1634, operation1635, operation1636, operation1637, operation1638, operation1639, operation1640, operation1641, operation1642, operation1643, operation1644, operation1645, operation1646 } from "../../lib/src/rest/operations";

declare module "../../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api: "/groups/{group-id}/conversations", groupid: string): operation1606,
        (api: "/groups/{group-id}/conversations/{conversation-id}", groupid: string, conversationid: string): operation1607,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads", groupid: string, conversationid: string): operation1608,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}", groupid: string, conversationid: string, conversationThreadid: string): operation1609,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/microsoft.graph.reply", groupid: string, conversationid: string, conversationThreadid: string): operation1610,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts", groupid: string, conversationid: string, conversationThreadid: string): operation1611,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1612,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/attachments", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1613,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/attachments/{attachment-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, attachmentid: string): operation1614,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/attachments/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1615,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/attachments/microsoft.graph.createUploadSession", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1616,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/extensions", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1617,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/extensions/{extension-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, extensionid: string): operation1618,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/extensions/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1619,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1620,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/attachments", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1621,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/attachments/{attachment-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, attachmentid: string): operation1622,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/attachments/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1623,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/attachments/microsoft.graph.createUploadSession", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1624,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/extensions", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1625,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/extensions/{extension-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, extensionid: string): operation1626,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/extensions/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1627,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/microsoft.graph.forward", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1628,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/microsoft.graph.reply", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1629,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/multiValueExtendedProperties", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1630,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, multiValueLegacyExtendedPropertyid: string): operation1631,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/multiValueExtendedProperties/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1632,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/singleValueExtendedProperties", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1633,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, singleValueLegacyExtendedPropertyid: string): operation1634,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/inReplyTo/singleValueExtendedProperties/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1635,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/microsoft.graph.forward", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1636,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/microsoft.graph.reply", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1637,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/multiValueExtendedProperties", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1638,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/multiValueExtendedProperties/{multiValueLegacyExtendedProperty-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, multiValueLegacyExtendedPropertyid: string): operation1639,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/multiValueExtendedProperties/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1640,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/singleValueExtendedProperties", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1641,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/singleValueExtendedProperties/{singleValueLegacyExtendedProperty-id}", groupid: string, conversationid: string, conversationThreadid: string, postid: string, singleValueLegacyExtendedPropertyid: string): operation1642,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/{post-id}/singleValueExtendedProperties/$count", groupid: string, conversationid: string, conversationThreadid: string, postid: string): operation1643,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/{conversationThread-id}/posts/$count", groupid: string, conversationid: string, conversationThreadid: string): operation1644,
        (api: "/groups/{group-id}/conversations/{conversation-id}/threads/$count", groupid: string, conversationid: string): operation1645,
        (api: "/groups/{group-id}/conversations/$count", groupid: string): operation1646,
    }
}

export { };