import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export class PrintCertificateSigningRequest implements Parsable {
    /** Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.  */
    private _additionalData: Map<string, unknown>;
    /** A base64-encoded pkcs10 certificate request. Read-only.  */
    private _content?: string | undefined;
    /** The base64-encoded public portion of an asymmetric key that is generated by the client. Read-only.  */
    private _transportKey?: string | undefined;
    /**
     * Instantiates a new printCertificateSigningRequest and sets the default values.
     */
    public constructor() {
        this._additionalData = new Map<string, unknown>();
    };
    /**
     * Gets the additionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     * @returns a Map<string, unknown>
     */
    public get additionalData() {
        return this._additionalData;
    };
    /**
     * Gets the content property value. A base64-encoded pkcs10 certificate request. Read-only.
     * @returns a string
     */
    public get content() {
        return this._content;
    };
    /**
     * Gets the transportKey property value. The base64-encoded public portion of an asymmetric key that is generated by the client. Read-only.
     * @returns a string
     */
    public get transportKey() {
        return this._transportKey;
    };
    /**
     * The deserialization information for the current model
     * @returns a Map<string, (item: T, node: ParseNode) => void>
     */
    public getFieldDeserializers<T>() : Map<string, (item: T, node: ParseNode) => void> {
        return new Map<string, (item: T, node: ParseNode) => void>([
            ["content", (o, n) => { (o as unknown as PrintCertificateSigningRequest).content = n.getStringValue(); }],
            ["transportKey", (o, n) => { (o as unknown as PrintCertificateSigningRequest).transportKey = n.getStringValue(); }],
        ]);
    };
    /**
     * Serializes information the current object
     * @param writer Serialization writer to use to serialize this model
     */
    public serialize(writer: SerializationWriter) : void {
        if(!writer) throw new Error("writer cannot be undefined");
        writer.writeStringValue("content", this.content);
        writer.writeStringValue("transportKey", this.transportKey);
        writer.writeAdditionalData(this.additionalData);
    };
    /**
     * Sets the additionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     * @param value Value to set for the AdditionalData property.
     */
    public set additionalData(value: Map<string, unknown>) {
        this._additionalData = value;
    };
    /**
     * Sets the content property value. A base64-encoded pkcs10 certificate request. Read-only.
     * @param value Value to set for the content property.
     */
    public set content(value: string | undefined) {
        this._content = value;
    };
    /**
     * Sets the transportKey property value. The base64-encoded public portion of an asymmetric key that is generated by the client. Read-only.
     * @param value Value to set for the transportKey property.
     */
    public set transportKey(value: string | undefined) {
        this._transportKey = value;
    };
}
