export enum SecurityNetworkProtocol {
    Unknown = "unknown",
    Ip = "ip",
    Icmp = "icmp",
    Igmp = "igmp",
    Ggp = "ggp",
    Ipv4 = "ipv4",
    Tcp = "tcp",
    Pup = "pup",
    Udp = "udp",
    Idp = "idp",
    Ipv6 = "ipv6",
    Ipv6RoutingHeader = "ipv6RoutingHeader",
    Ipv6FragmentHeader = "ipv6FragmentHeader",
    IpSecEncapsulatingSecurityPayload = "ipSecEncapsulatingSecurityPayload",
    IpSecAuthenticationHeader = "ipSecAuthenticationHeader",
    IcmpV6 = "icmpV6",
    Ipv6NoNextHeader = "ipv6NoNextHeader",
    Ipv6DestinationOptions = "ipv6DestinationOptions",
    Nd = "nd",
    Raw = "raw",
    Ipx = "ipx",
    Spx = "spx",
    SpxII = "spxII",
    UnknownFutureValue = "unknownFutureValue",
}
