/** Provides operations to manage the collection of group entities.  */
export enum TimeOffReasonIconType {
    None = "none",
    Car = "car",
    Calendar = "calendar",
    Running = "running",
    Plane = "plane",
    FirstAid = "firstAid",
    Doctor = "doctor",
    NotWorking = "notWorking",
    Clock = "clock",
    JuryDuty = "juryDuty",
    Globe = "globe",
    Cup = "cup",
    Phone = "phone",
    Weather = "weather",
    Umbrella = "umbrella",
    PiggyBank = "piggyBank",
    Dog = "dog",
    Cake = "cake",
    TrafficCone = "trafficCone",
    Pin = "pin",
    Sunny = "sunny",
    UnknownFutureValue = "unknownFutureValue",
}
