/** Provides operations to manage the cloudCommunications singleton.  */
export enum Tone {
    Tone0 = "tone0",
    Tone1 = "tone1",
    Tone2 = "tone2",
    Tone3 = "tone3",
    Tone4 = "tone4",
    Tone5 = "tone5",
    Tone6 = "tone6",
    Tone7 = "tone7",
    Tone8 = "tone8",
    Tone9 = "tone9",
    Star = "star",
    Pound = "pound",
    A = "a",
    B = "b",
    C = "c",
    D = "d",
    Flash = "flash",
}
