import { GraphApis } from "../../lib/src/rest/graphAPIs";

import { operation100, operation101, operation102, operation103, operation104, operation105, operation106, operation107, operation108, operation56, operation57, operation58, operation59, operation60, operation61, operation62, operation63, operation64, operation65, operation66, operation67, operation68, operation69, operation70, operation71, operation72, operation73, operation74, operation75, operation76, operation77, operation78, operation79, operation80, operation81, operation82, operation83, operation84, operation85, operation86, operation87, operation88, operation89, operation90, operation91, operation92, operation93, operation94, operation95, operation96, operation97, operation98, operation99 } from "../../lib/src/rest/operations";

declare module "../../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api: "/applications"): operation56,
        (api: "/applications/{application-id}", applicationid: string): operation57,
        (api: "/applications/{application-id}/createdOnBehalfOf", applicationid: string): operation58,
        (api: "/applications/{application-id}/extensionProperties", applicationid: string): operation59,
        (api: "/applications/{application-id}/extensionProperties/{extensionProperty-id}", applicationid: string, extensionPropertyid: string): operation60,
        (api: "/applications/{application-id}/extensionProperties/$count", applicationid: string): operation61,
        (api: "/applications/{application-id}/federatedIdentityCredentials", applicationid: string): operation62,
        (api: "/applications/{application-id}/federatedIdentityCredentials/{federatedIdentityCredential-id}", applicationid: string, federatedIdentityCredentialid: string): operation63,
        (api: "/applications/{application-id}/federatedIdentityCredentials/$count", applicationid: string): operation64,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies", applicationid: string): operation65,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}", applicationid: string, homeRealmDiscoveryPolicyid: string): operation66,
        (api: "/applications/{application-id}/homeRealmDiscoveryPolicies/$count", applicationid: string): operation67,
        (api: "/applications/{application-id}/logo", applicationid: string): operation68,
        (api: "/applications/{application-id}/microsoft.graph.addKey", applicationid: string): operation69,
        (api: "/applications/{application-id}/microsoft.graph.addPassword", applicationid: string): operation70,
        (api: "/applications/{application-id}/microsoft.graph.checkMemberGroups", applicationid: string): operation71,
        (api: "/applications/{application-id}/microsoft.graph.checkMemberObjects", applicationid: string): operation72,
        (api: "/applications/{application-id}/microsoft.graph.getMemberGroups", applicationid: string): operation73,
        (api: "/applications/{application-id}/microsoft.graph.getMemberObjects", applicationid: string): operation74,
        (api: "/applications/{application-id}/microsoft.graph.removeKey", applicationid: string): operation75,
        (api: "/applications/{application-id}/microsoft.graph.removePassword", applicationid: string): operation76,
        (api: "/applications/{application-id}/microsoft.graph.restore", applicationid: string): operation77,
        (api: "/applications/{application-id}/microsoft.graph.setVerifiedPublisher", applicationid: string): operation78,
        (api: "/applications/{application-id}/microsoft.graph.unsetVerifiedPublisher", applicationid: string): operation79,
        (api: "/applications/{application-id}/owners", applicationid: string): operation80,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/$ref", applicationid: string, directoryObjectid: string): operation81,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.appRoleAssignment", applicationid: string, directoryObjectid: string): operation82,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.endpoint", applicationid: string, directoryObjectid: string): operation83,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.servicePrincipal", applicationid: string, directoryObjectid: string): operation84,
        (api: "/applications/{application-id}/owners/{directoryObject-id}/microsoft.graph.user", applicationid: string, directoryObjectid: string): operation85,
        (api: "/applications/{application-id}/owners/$count", applicationid: string): operation86,
        (api: "/applications/{application-id}/owners/$ref", applicationid: string): operation87,
        (api: "/applications/{application-id}/owners/microsoft.graph.appRoleAssignment", applicationid: string): operation88,
        (api: "/applications/{application-id}/owners/microsoft.graph.appRoleAssignment/$count", applicationid: string): operation89,
        (api: "/applications/{application-id}/owners/microsoft.graph.endpoint", applicationid: string): operation90,
        (api: "/applications/{application-id}/owners/microsoft.graph.endpoint/$count", applicationid: string): operation91,
        (api: "/applications/{application-id}/owners/microsoft.graph.servicePrincipal", applicationid: string): operation92,
        (api: "/applications/{application-id}/owners/microsoft.graph.servicePrincipal/$count", applicationid: string): operation93,
        (api: "/applications/{application-id}/owners/microsoft.graph.user", applicationid: string): operation94,
        (api: "/applications/{application-id}/owners/microsoft.graph.user/$count", applicationid: string): operation95,
        (api: "/applications/{application-id}/tokenIssuancePolicies", applicationid: string): operation96,
        (api: "/applications/{application-id}/tokenIssuancePolicies/{tokenIssuancePolicy-id}/$ref", applicationid: string, tokenIssuancePolicyid: string): operation97,
        (api: "/applications/{application-id}/tokenIssuancePolicies/$count", applicationid: string): operation98,
        (api: "/applications/{application-id}/tokenIssuancePolicies/$ref", applicationid: string): operation99,
        (api: "/applications/{application-id}/tokenLifetimePolicies", applicationid: string): operation100,
        (api: "/applications/{application-id}/tokenLifetimePolicies/{tokenLifetimePolicy-id}/$ref", applicationid: string, tokenLifetimePolicyid: string): operation101,
        (api: "/applications/{application-id}/tokenLifetimePolicies/$count", applicationid: string): operation102,
        (api: "/applications/{application-id}/tokenLifetimePolicies/$ref", applicationid: string): operation103,
        (api: "/applications/$count"): operation104,
        (api: "/applications/microsoft.graph.delta()"): operation105,
        (api: "/applications/microsoft.graph.getAvailableExtensionProperties"): operation106,
        (api: "/applications/microsoft.graph.getByIds"): operation107,
        (api: "/applications/microsoft.graph.validateProperties"): operation108,
    }
}
export { };