import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation1971, operation1972, operation1973, operation1974, operation1975, operation1976, operation1977, operation1978, operation1979, operation1980, operation1981, operation1982, operation1983, operation1984, operation1985, operation1986, operation1987, operation1988, operation1989, operation1990, operation1991, operation1992, operation1993, operation1994, operation1995, operation1996, operation1997, operation1998, operation1999, operation2000, operation2001, operation2002, operation2003, operation2004, operation2005, operation2006, operation2007, operation2008, operation2009, operation2010, operation2011, operation2012, operation2013, operation2014, operation2015, operation2016, operation2017, operation2018, operation2019, operation2020, operation2021, operation2022, operation2023, operation2024, operation2025, operation2026, operation2027, operation2028, operation2029, operation2030, operation2031, operation2032, operation2033, operation2034, operation2035, operation2036, operation2037, operation2038, operation2039, operation2040, operation2041, operation2042, operation2043, operation2044, operation2045, operation2046, operation2047, operation2048, operation2049, operation2050, operation2051, operation2052, operation2053, operation2054, operation2055, operation2056, operation2057, operation2058, operation2059, operation2060, operation2061, operation2062, operation2063, operation2064, operation2065, operation2066, operation2067, operation2068, operation2069, operation2070, operation2071, operation2072, operation2073, operation2246, operation2247, operation2248, operation2249, operation2250, operation2251, operation2252, operation2253, operation2254, operation2255, operation2256, operation2257, operation2258, operation2259, operation2260, operation2261, operation2262, operation2263, operation2264, operation2265, operation2266, operation2267, operation2268, operation2269, operation2270, operation2271, operation2272, operation2273, operation2274, operation2275, operation2276, operation2277, operation2278, operation2279, operation2280, operation2281, operation2282, operation2283, operation2284, operation2285, operation2286, operation2287, operation2288, operation2289, operation2290, operation2291, operation2292, operation2293, operation2294, operation2295, operation2296, operation2297, operation2298, operation2299, operation2300, operation2301, operation2302, operation2303, operation2304, operation2305, operation2306, operation2307, operation2308, operation2309, operation2310, operation2311, operation2312, operation2313, operation2314, operation2315, operation2316, operation2317, operation2318, operation2319, operation2320, operation2321, operation2322, operation2323, operation2324, operation2325, operation2326, operation2327, operation2328, operation2329, operation2330, operation2331, operation2332, operation2333, operation2334, operation2335, operation2336, operation2337, operation2338, operation2339, operation2340, operation2341, operation2342, operation2343, operation2344, operation2345, operation2346, operation2347, operation2348, operation4443, operation4444, operation4445, operation4446, operation4447, operation4448, operation4449, operation4450, operation4451, operation4452, operation4453, operation4454, operation4455, operation4456, operation4457, operation4458, operation4459, operation4460, operation4461, operation4462, operation4463, operation4464, operation4465, operation4466, operation4467, operation4468, operation4469, operation4470, operation4471, operation4472, operation4473, operation4474, operation4475, operation4476, operation4477, operation4478, operation4479, operation4480, operation4481, operation4482, operation4483, operation4484, operation4485, operation4486, operation4487, operation4488, operation4489, operation4490, operation4491, operation4492, operation4493, operation4494, operation4495, operation4496, operation4497, operation4498, operation4499, operation4500, operation4501, operation4502, operation4503, operation4504, operation4505, operation4506, operation4507, operation4508, operation4509, operation4510, operation4511, operation4512, operation4513, operation4514, operation4515, operation4516, operation4517, operation4518, operation4519, operation4520, operation4521, operation4522, operation4523, operation4524, operation4525, operation4526, operation4527, operation4528, operation4529, operation4530, operation4531, operation4532, operation4533, operation4534, operation4535, operation4536, operation4537, operation4538, operation4539, operation4540, operation4541, operation4542, operation4543, operation4544, operation4545, operation5544, operation5545, operation5546, operation5547, operation5548, operation5549, operation5550, operation5551, operation5552, operation5553, operation5554, operation5555, operation5556, operation5557, operation5558, operation5559, operation5560, operation5561, operation5562, operation5563, operation5564, operation5565, operation5566, operation5567, operation5568, operation5569, operation5570, operation5571, operation5572, operation5573, operation5574, operation5575, operation5576, operation5577, operation5578, operation5579, operation5580, operation5581, operation5582, operation5583, operation5584, operation5585, operation5586, operation5587, operation5588, operation5589, operation5590, operation5591, operation5592, operation5593, operation5594, operation5595, operation5596, operation5597, operation5598, operation5599, operation5600, operation5601, operation5602, operation5603, operation5604, operation5605, operation5606, operation5607, operation5608, operation5609, operation5610, operation5611, operation5612, operation5613, operation5614, operation5615, operation5616, operation5617, operation5618, operation5619, operation5620, operation5621, operation5622, operation5623, operation5624, operation5625, operation5626, operation5627, operation5628, operation5629, operation5630, operation5631, operation5632, operation5633, operation5634, operation5635, operation5636, operation5637, operation5638, operation5639, operation5640, operation5641, operation5642, operation5643, operation5644, operation5645, operation5646, operation7456, operation7457, operation7458, operation7459, operation7460, operation7461, operation7462, operation7463, operation7464, operation7465, operation7466, operation7467, operation7468, operation7469, operation7470, operation7471, operation7472, operation7473, operation7474, operation7475, operation7476, operation7477, operation7478, operation7479, operation7480, operation7481, operation7482, operation7483, operation7484, operation7485, operation7486, operation7487, operation7488, operation7489, operation7490, operation7491, operation7492, operation7493, operation7494, operation7495, operation7496, operation7497, operation7498, operation7499, operation7500, operation7501, operation7502, operation7503, operation7504, operation7505, operation7506, operation7507, operation7508, operation7509, operation7510, operation7511, operation7512, operation7513, operation7514, operation7515, operation7516, operation7517, operation7518, operation7519, operation7520, operation7521, operation7522, operation7523, operation7524, operation7525, operation7526, operation7527, operation7528, operation7529, operation7530, operation7531, operation7532, operation7533, operation7534, operation7535, operation7536, operation7537, operation7538, operation7539, operation7540, operation7541, operation7542, operation7543, operation7544, operation7545, operation7546, operation7547, operation7548, operation7549, operation7550, operation7551, operation7552, operation7553, operation7554, operation7555, operation7556, operation7557, operation7558 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/users/{user-id}/onenote",userid: string):operation7456,
(api:"/users/{user-id}/onenote/notebooks",userid: string):operation7457,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}",userid: string,notebookid: string):operation7458,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/microsoft.graph.copyNotebook",userid: string,notebookid: string):operation7459,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups",userid: string,notebookid: string):operation7460,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}",userid: string,notebookid: string,sectionGroupid: string):operation7461,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentNotebook",userid: string,notebookid: string,sectionGroupid: string):operation7462,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentSectionGroup",userid: string,notebookid: string,sectionGroupid: string):operation7463,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups",userid: string,notebookid: string,sectionGroupid: string):operation7464,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",userid: string,notebookid: string,sectionGroupid: string,sectionGroupid1: string):operation7465,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/$count",userid: string,notebookid: string,sectionGroupid: string):operation7466,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections",userid: string,notebookid: string,sectionGroupid: string):operation7467,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7468,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7469,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7470,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7471,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7472,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7473,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7474,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7475,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7476,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7477,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7478,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7479,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7480,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",userid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation7481,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/$count",userid: string,notebookid: string,sectionGroupid: string):operation7482,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sectionGroups/$count",userid: string,notebookid: string):operation7483,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections",userid: string,notebookid: string):operation7484,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}",userid: string,notebookid: string,onenoteSectionid: string):operation7485,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",userid: string,notebookid: string,onenoteSectionid: string):operation7486,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",userid: string,notebookid: string,onenoteSectionid: string):operation7487,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages",userid: string,notebookid: string,onenoteSectionid: string):operation7488,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7489,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7490,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7491,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7492,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7493,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7494,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",userid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation7495,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/$count",userid: string,notebookid: string,onenoteSectionid: string):operation7496,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentNotebook",userid: string,notebookid: string,onenoteSectionid: string):operation7497,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentSectionGroup",userid: string,notebookid: string,onenoteSectionid: string):operation7498,
(api:"/users/{user-id}/onenote/notebooks/{notebook-id}/sections/$count",userid: string,notebookid: string):operation7499,
(api:"/users/{user-id}/onenote/notebooks/$count",userid: string):operation7500,
(api:"/users/{user-id}/onenote/notebooks/microsoft.graph.getNotebookFromWebUrl",userid: string):operation7501,
(api:"/users/{user-id}/onenote/notebooks/microsoft.graph.getRecentNotebooks(includePersonalNotebooks={includePersonalNotebooks})",userid: string,includePersonalNotebooks: string):operation7502,
(api:"/users/{user-id}/onenote/operations",userid: string):operation7503,
(api:"/users/{user-id}/onenote/operations/{onenoteOperation-id}",userid: string,onenoteOperationid: string):operation7504,
(api:"/users/{user-id}/onenote/operations/$count",userid: string):operation7505,
(api:"/users/{user-id}/onenote/pages",userid: string):operation7506,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}",userid: string,onenotePageid: string):operation7507,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/content",userid: string,onenotePageid: string):operation7508,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/microsoft.graph.copyToSection",userid: string,onenotePageid: string):operation7509,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",userid: string,onenotePageid: string):operation7510,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/microsoft.graph.preview()",userid: string,onenotePageid: string):operation7511,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/parentNotebook",userid: string,onenotePageid: string):operation7512,
(api:"/users/{user-id}/onenote/pages/{onenotePage-id}/parentSection",userid: string,onenotePageid: string):operation7513,
(api:"/users/{user-id}/onenote/pages/$count",userid: string):operation7514,
(api:"/users/{user-id}/onenote/resources",userid: string):operation7515,
(api:"/users/{user-id}/onenote/resources/{onenoteResource-id}",userid: string,onenoteResourceid: string):operation7516,
(api:"/users/{user-id}/onenote/resources/{onenoteResource-id}/content",userid: string,onenoteResourceid: string):operation7517,
(api:"/users/{user-id}/onenote/resources/$count",userid: string):operation7518,
(api:"/users/{user-id}/onenote/sectionGroups",userid: string):operation7519,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}",userid: string,sectionGroupid: string):operation7520,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/parentNotebook",userid: string,sectionGroupid: string):operation7521,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup",userid: string,sectionGroupid: string):operation7522,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups",userid: string,sectionGroupid: string):operation7523,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",userid: string,sectionGroupid: string,sectionGroupid1: string):operation7524,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count",userid: string,sectionGroupid: string):operation7525,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections",userid: string,sectionGroupid: string):operation7526,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7527,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7528,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7529,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7530,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7531,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7532,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7533,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7534,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7535,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7536,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",userid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation7537,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7538,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7539,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",userid: string,sectionGroupid: string,onenoteSectionid: string):operation7540,
(api:"/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sections/$count",userid: string,sectionGroupid: string):operation7541,
(api:"/users/{user-id}/onenote/sectionGroups/$count",userid: string):operation7542,
(api:"/users/{user-id}/onenote/sections",userid: string):operation7543,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}",userid: string,onenoteSectionid: string):operation7544,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",userid: string,onenoteSectionid: string):operation7545,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",userid: string,onenoteSectionid: string):operation7546,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages",userid: string,onenoteSectionid: string):operation7547,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}",userid: string,onenoteSectionid: string,onenotePageid: string):operation7548,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",userid: string,onenoteSectionid: string,onenotePageid: string):operation7549,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",userid: string,onenoteSectionid: string,onenotePageid: string):operation7550,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",userid: string,onenoteSectionid: string,onenotePageid: string):operation7551,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",userid: string,onenoteSectionid: string,onenotePageid: string):operation7552,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",userid: string,onenoteSectionid: string,onenotePageid: string):operation7553,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",userid: string,onenoteSectionid: string,onenotePageid: string):operation7554,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/pages/$count",userid: string,onenoteSectionid: string):operation7555,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/parentNotebook",userid: string,onenoteSectionid: string):operation7556,
(api:"/users/{user-id}/onenote/sections/{onenoteSection-id}/parentSectionGroup",userid: string,onenoteSectionid: string):operation7557,
(api:"/users/{user-id}/onenote/sections/$count",userid: string):operation7558,


(api:"/groups/{group-id}/onenote",groupid: string):operation1971,
    (api:"/groups/{group-id}/onenote/notebooks",groupid: string):operation1972,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}",groupid: string,notebookid: string):operation1973,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/microsoft.graph.copyNotebook",groupid: string,notebookid: string):operation1974,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups",groupid: string,notebookid: string):operation1975,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}",groupid: string,notebookid: string,sectionGroupid: string):operation1976,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentNotebook",groupid: string,notebookid: string,sectionGroupid: string):operation1977,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentSectionGroup",groupid: string,notebookid: string,sectionGroupid: string):operation1978,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups",groupid: string,notebookid: string,sectionGroupid: string):operation1979,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",groupid: string,notebookid: string,sectionGroupid: string,sectionGroupid1: string):operation1980,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/$count",groupid: string,notebookid: string,sectionGroupid: string):operation1981,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections",groupid: string,notebookid: string,sectionGroupid: string):operation1982,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1983,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1984,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1985,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1986,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1987,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1988,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1989,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1990,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1991,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1992,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation1993,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1994,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1995,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation1996,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/$count",groupid: string,notebookid: string,sectionGroupid: string):operation1997,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/$count",groupid: string,notebookid: string):operation1998,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections",groupid: string,notebookid: string):operation1999,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}",groupid: string,notebookid: string,onenoteSectionid: string):operation2000,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,notebookid: string,onenoteSectionid: string):operation2001,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,notebookid: string,onenoteSectionid: string):operation2002,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages",groupid: string,notebookid: string,onenoteSectionid: string):operation2003,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2004,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2005,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2006,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2007,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2008,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2009,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2010,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,notebookid: string,onenoteSectionid: string):operation2011,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,notebookid: string,onenoteSectionid: string):operation2012,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,notebookid: string,onenoteSectionid: string):operation2013,
    (api:"/groups/{group-id}/onenote/notebooks/{notebook-id}/sections/$count",groupid: string,notebookid: string):operation2014,
    (api:"/groups/{group-id}/onenote/notebooks/$count",groupid: string):operation2015,
    (api:"/groups/{group-id}/onenote/notebooks/microsoft.graph.getNotebookFromWebUrl",groupid: string):operation2016,
    (api:"/groups/{group-id}/onenote/notebooks/microsoft.graph.getRecentNotebooks(includePersonalNotebooks={includePersonalNotebooks})",groupid: string,includePersonalNotebooks: string):operation2017,
    (api:"/groups/{group-id}/onenote/operations",groupid: string):operation2018,
    (api:"/groups/{group-id}/onenote/operations/{onenoteOperation-id}",groupid: string,onenoteOperationid: string):operation2019,
    (api:"/groups/{group-id}/onenote/operations/$count",groupid: string):operation2020,
    (api:"/groups/{group-id}/onenote/pages",groupid: string):operation2021,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}",groupid: string,onenotePageid: string):operation2022,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/content",groupid: string,onenotePageid: string):operation2023,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,onenotePageid: string):operation2024,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,onenotePageid: string):operation2025,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,onenotePageid: string):operation2026,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/parentNotebook",groupid: string,onenotePageid: string):operation2027,
    (api:"/groups/{group-id}/onenote/pages/{onenotePage-id}/parentSection",groupid: string,onenotePageid: string):operation2028,
    (api:"/groups/{group-id}/onenote/pages/$count",groupid: string):operation2029,
    (api:"/groups/{group-id}/onenote/resources",groupid: string):operation2030,
    (api:"/groups/{group-id}/onenote/resources/{onenoteResource-id}",groupid: string,onenoteResourceid: string):operation2031,
    (api:"/groups/{group-id}/onenote/resources/{onenoteResource-id}/content",groupid: string,onenoteResourceid: string):operation2032,
    (api:"/groups/{group-id}/onenote/resources/$count",groupid: string):operation2033,
    (api:"/groups/{group-id}/onenote/sectionGroups",groupid: string):operation2034,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}",groupid: string,sectionGroupid: string):operation2035,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/parentNotebook",groupid: string,sectionGroupid: string):operation2036,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup",groupid: string,sectionGroupid: string):operation2037,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups",groupid: string,sectionGroupid: string):operation2038,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",groupid: string,sectionGroupid: string,sectionGroupid1: string):operation2039,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count",groupid: string,sectionGroupid: string):operation2040,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections",groupid: string,sectionGroupid: string):operation2041,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2042,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2043,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2044,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2045,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2046,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2047,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2048,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2049,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2050,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2051,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2052,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2053,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2054,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,sectionGroupid: string,onenoteSectionid: string):operation2055,
    (api:"/groups/{group-id}/onenote/sectionGroups/{sectionGroup-id}/sections/$count",groupid: string,sectionGroupid: string):operation2056,
    (api:"/groups/{group-id}/onenote/sectionGroups/$count",groupid: string):operation2057,
    (api:"/groups/{group-id}/onenote/sections",groupid: string):operation2058,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}",groupid: string,onenoteSectionid: string):operation2059,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,onenoteSectionid: string):operation2060,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,onenoteSectionid: string):operation2061,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages",groupid: string,onenoteSectionid: string):operation2062,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2063,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2064,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2065,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2066,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2067,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2068,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,onenoteSectionid: string,onenotePageid: string):operation2069,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/pages/$count",groupid: string,onenoteSectionid: string):operation2070,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/parentNotebook",groupid: string,onenoteSectionid: string):operation2071,
    (api:"/groups/{group-id}/onenote/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,onenoteSectionid: string):operation2072,
    (api:"/groups/{group-id}/onenote/sections/$count",groupid: string):operation2073,

    (api:"/groups/{group-id}/sites/{site-id}/onenote",groupid: string,siteid: string):operation2246,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks",groupid: string,siteid: string):operation2247,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}",groupid: string,siteid: string,notebookid: string):operation2248,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/microsoft.graph.copyNotebook",groupid: string,siteid: string,notebookid: string):operation2249,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups",groupid: string,siteid: string,notebookid: string):operation2250,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2251,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentNotebook",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2252,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentSectionGroup",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2253,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2254,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,sectionGroupid1: string):operation2255,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/$count",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2256,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2257,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2258,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2259,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2260,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2261,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2262,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2263,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2264,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2265,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2266,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2267,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2268,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2269,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2270,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation2271,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/$count",groupid: string,siteid: string,notebookid: string,sectionGroupid: string):operation2272,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/$count",groupid: string,siteid: string,notebookid: string):operation2273,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections",groupid: string,siteid: string,notebookid: string):operation2274,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2275,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2276,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2277,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2278,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2279,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2280,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2281,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2282,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2283,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2284,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation2285,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2286,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2287,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,siteid: string,notebookid: string,onenoteSectionid: string):operation2288,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/$count",groupid: string,siteid: string,notebookid: string):operation2289,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/$count",groupid: string,siteid: string):operation2290,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/microsoft.graph.getNotebookFromWebUrl",groupid: string,siteid: string):operation2291,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/notebooks/microsoft.graph.getRecentNotebooks(includePersonalNotebooks={includePersonalNotebooks})",groupid: string,siteid: string,includePersonalNotebooks: string):operation2292,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/operations",groupid: string,siteid: string):operation2293,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/operations/{onenoteOperation-id}",groupid: string,siteid: string,onenoteOperationid: string):operation2294,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/operations/$count",groupid: string,siteid: string):operation2295,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages",groupid: string,siteid: string):operation2296,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}",groupid: string,siteid: string,onenotePageid: string):operation2297,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/content",groupid: string,siteid: string,onenotePageid: string):operation2298,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,siteid: string,onenotePageid: string):operation2299,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,siteid: string,onenotePageid: string):operation2300,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,siteid: string,onenotePageid: string):operation2301,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/parentNotebook",groupid: string,siteid: string,onenotePageid: string):operation2302,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/{onenotePage-id}/parentSection",groupid: string,siteid: string,onenotePageid: string):operation2303,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/pages/$count",groupid: string,siteid: string):operation2304,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/resources",groupid: string,siteid: string):operation2305,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/resources/{onenoteResource-id}",groupid: string,siteid: string,onenoteResourceid: string):operation2306,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/resources/{onenoteResource-id}/content",groupid: string,siteid: string,onenoteResourceid: string):operation2307,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/resources/$count",groupid: string,siteid: string):operation2308,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups",groupid: string,siteid: string):operation2309,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}",groupid: string,siteid: string,sectionGroupid: string):operation2310,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentNotebook",groupid: string,siteid: string,sectionGroupid: string):operation2311,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup",groupid: string,siteid: string,sectionGroupid: string):operation2312,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups",groupid: string,siteid: string,sectionGroupid: string):operation2313,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",groupid: string,siteid: string,sectionGroupid: string,sectionGroupid1: string):operation2314,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count",groupid: string,siteid: string,sectionGroupid: string):operation2315,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections",groupid: string,siteid: string,sectionGroupid: string):operation2316,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2317,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2318,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2319,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2320,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2321,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2322,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2323,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2324,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2325,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2326,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation2327,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2328,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2329,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,siteid: string,sectionGroupid: string,onenoteSectionid: string):operation2330,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/$count",groupid: string,siteid: string,sectionGroupid: string):operation2331,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sectionGroups/$count",groupid: string,siteid: string):operation2332,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections",groupid: string,siteid: string):operation2333,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}",groupid: string,siteid: string,onenoteSectionid: string):operation2334,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",groupid: string,siteid: string,onenoteSectionid: string):operation2335,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",groupid: string,siteid: string,onenoteSectionid: string):operation2336,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages",groupid: string,siteid: string,onenoteSectionid: string):operation2337,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2338,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2339,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2340,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2341,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2342,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2343,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",groupid: string,siteid: string,onenoteSectionid: string,onenotePageid: string):operation2344,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/$count",groupid: string,siteid: string,onenoteSectionid: string):operation2345,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/parentNotebook",groupid: string,siteid: string,onenoteSectionid: string):operation2346,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/{onenoteSection-id}/parentSectionGroup",groupid: string,siteid: string,onenoteSectionid: string):operation2347,
    (api:"/groups/{group-id}/sites/{site-id}/onenote/sections/$count",groupid: string,siteid: string):operation2348,


    (api:"/me/onenote"):operation4443,
    (api:"/me/onenote/notebooks"):operation4444,
    (api:"/me/onenote/notebooks/{notebook-id}",notebookid: string):operation4445,
    (api:"/me/onenote/notebooks/{notebook-id}/microsoft.graph.copyNotebook",notebookid: string):operation4446,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups",notebookid: string):operation4447,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}",notebookid: string,sectionGroupid: string):operation4448,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentNotebook",notebookid: string,sectionGroupid: string):operation4449,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentSectionGroup",notebookid: string,sectionGroupid: string):operation4450,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups",notebookid: string,sectionGroupid: string):operation4451,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",notebookid: string,sectionGroupid: string,sectionGroupid1: string):operation4452,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/$count",notebookid: string,sectionGroupid: string):operation4453,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections",notebookid: string,sectionGroupid: string):operation4454,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4455,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4456,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4457,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4458,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4459,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4460,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4461,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4462,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4463,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4464,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4465,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4466,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4467,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation4468,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/$count",notebookid: string,sectionGroupid: string):operation4469,
    (api:"/me/onenote/notebooks/{notebook-id}/sectionGroups/$count",notebookid: string):operation4470,
    (api:"/me/onenote/notebooks/{notebook-id}/sections",notebookid: string):operation4471,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}",notebookid: string,onenoteSectionid: string):operation4472,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",notebookid: string,onenoteSectionid: string):operation4473,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",notebookid: string,onenoteSectionid: string):operation4474,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages",notebookid: string,onenoteSectionid: string):operation4475,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4476,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4477,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4478,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4479,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4480,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4481,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",notebookid: string,onenoteSectionid: string,onenotePageid: string):operation4482,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/$count",notebookid: string,onenoteSectionid: string):operation4483,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentNotebook",notebookid: string,onenoteSectionid: string):operation4484,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentSectionGroup",notebookid: string,onenoteSectionid: string):operation4485,
    (api:"/me/onenote/notebooks/{notebook-id}/sections/$count",notebookid: string):operation4486,
    (api:"/me/onenote/notebooks/$count"):operation4487,
    (api:"/me/onenote/notebooks/microsoft.graph.getNotebookFromWebUrl"):operation4488,
    (api:"/me/onenote/notebooks/microsoft.graph.getRecentNotebooks(includePersonalNotebooks={includePersonalNotebooks})",includePersonalNotebooks: string):operation4489,
    (api:"/me/onenote/operations"):operation4490,
    (api:"/me/onenote/operations/{onenoteOperation-id}",onenoteOperationid: string):operation4491,
    (api:"/me/onenote/operations/$count"):operation4492,
    (api:"/me/onenote/pages"):operation4493,
    (api:"/me/onenote/pages/{onenotePage-id}",onenotePageid: string):operation4494,
    (api:"/me/onenote/pages/{onenotePage-id}/content",onenotePageid: string):operation4495,
    (api:"/me/onenote/pages/{onenotePage-id}/microsoft.graph.copyToSection",onenotePageid: string):operation4496,
    (api:"/me/onenote/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",onenotePageid: string):operation4497,
    (api:"/me/onenote/pages/{onenotePage-id}/microsoft.graph.preview()",onenotePageid: string):operation4498,
    (api:"/me/onenote/pages/{onenotePage-id}/parentNotebook",onenotePageid: string):operation4499,
    (api:"/me/onenote/pages/{onenotePage-id}/parentSection",onenotePageid: string):operation4500,
    (api:"/me/onenote/pages/$count"):operation4501,
    (api:"/me/onenote/resources"):operation4502,
    (api:"/me/onenote/resources/{onenoteResource-id}",onenoteResourceid: string):operation4503,
    (api:"/me/onenote/resources/{onenoteResource-id}/content",onenoteResourceid: string):operation4504,
    (api:"/me/onenote/resources/$count"):operation4505,
    (api:"/me/onenote/sectionGroups"):operation4506,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}",sectionGroupid: string):operation4507,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/parentNotebook",sectionGroupid: string):operation4508,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup",sectionGroupid: string):operation4509,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sectionGroups",sectionGroupid: string):operation4510,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",sectionGroupid: string,sectionGroupid1: string):operation4511,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count",sectionGroupid: string):operation4512,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections",sectionGroupid: string):operation4513,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",sectionGroupid: string,onenoteSectionid: string):operation4514,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",sectionGroupid: string,onenoteSectionid: string):operation4515,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",sectionGroupid: string,onenoteSectionid: string):operation4516,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",sectionGroupid: string,onenoteSectionid: string):operation4517,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4518,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4519,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4520,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4521,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4522,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4523,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation4524,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",sectionGroupid: string,onenoteSectionid: string):operation4525,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",sectionGroupid: string,onenoteSectionid: string):operation4526,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",sectionGroupid: string,onenoteSectionid: string):operation4527,
    (api:"/me/onenote/sectionGroups/{sectionGroup-id}/sections/$count",sectionGroupid: string):operation4528,
    (api:"/me/onenote/sectionGroups/$count"):operation4529,
    (api:"/me/onenote/sections"):operation4530,
    (api:"/me/onenote/sections/{onenoteSection-id}",onenoteSectionid: string):operation4531,
    (api:"/me/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",onenoteSectionid: string):operation4532,
    (api:"/me/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",onenoteSectionid: string):operation4533,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages",onenoteSectionid: string):operation4534,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}",onenoteSectionid: string,onenotePageid: string):operation4535,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",onenoteSectionid: string,onenotePageid: string):operation4536,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",onenoteSectionid: string,onenotePageid: string):operation4537,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",onenoteSectionid: string,onenotePageid: string):operation4538,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",onenoteSectionid: string,onenotePageid: string):operation4539,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",onenoteSectionid: string,onenotePageid: string):operation4540,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",onenoteSectionid: string,onenotePageid: string):operation4541,
    (api:"/me/onenote/sections/{onenoteSection-id}/pages/$count",onenoteSectionid: string):operation4542,
    (api:"/me/onenote/sections/{onenoteSection-id}/parentNotebook",onenoteSectionid: string):operation4543,
    (api:"/me/onenote/sections/{onenoteSection-id}/parentSectionGroup",onenoteSectionid: string):operation4544,
    (api:"/me/onenote/sections/$count"):operation4545,


    (api:"/sites/{site-id}/onenote",siteid: string):operation5544,
    (api:"/sites/{site-id}/onenote/notebooks",siteid: string):operation5545,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}",siteid: string,notebookid: string):operation5546,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/microsoft.graph.copyNotebook",siteid: string,notebookid: string):operation5547,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups",siteid: string,notebookid: string):operation5548,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}",siteid: string,notebookid: string,sectionGroupid: string):operation5549,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentNotebook",siteid: string,notebookid: string,sectionGroupid: string):operation5550,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/parentSectionGroup",siteid: string,notebookid: string,sectionGroupid: string):operation5551,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups",siteid: string,notebookid: string,sectionGroupid: string):operation5552,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",siteid: string,notebookid: string,sectionGroupid: string,sectionGroupid1: string):operation5553,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sectionGroups/$count",siteid: string,notebookid: string,sectionGroupid: string):operation5554,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections",siteid: string,notebookid: string,sectionGroupid: string):operation5555,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5556,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5557,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5558,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5559,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5560,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5561,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5562,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5563,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5564,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5565,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5566,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5567,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5568,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",siteid: string,notebookid: string,sectionGroupid: string,onenoteSectionid: string):operation5569,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/$count",siteid: string,notebookid: string,sectionGroupid: string):operation5570,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/$count",siteid: string,notebookid: string):operation5571,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections",siteid: string,notebookid: string):operation5572,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}",siteid: string,notebookid: string,onenoteSectionid: string):operation5573,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",siteid: string,notebookid: string,onenoteSectionid: string):operation5574,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",siteid: string,notebookid: string,onenoteSectionid: string):operation5575,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages",siteid: string,notebookid: string,onenoteSectionid: string):operation5576,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5577,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5578,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5579,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5580,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5581,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5582,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",siteid: string,notebookid: string,onenoteSectionid: string,onenotePageid: string):operation5583,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/pages/$count",siteid: string,notebookid: string,onenoteSectionid: string):operation5584,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentNotebook",siteid: string,notebookid: string,onenoteSectionid: string):operation5585,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}/parentSectionGroup",siteid: string,notebookid: string,onenoteSectionid: string):operation5586,
    (api:"/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/$count",siteid: string,notebookid: string):operation5587,
    (api:"/sites/{site-id}/onenote/notebooks/$count",siteid: string):operation5588,
    (api:"/sites/{site-id}/onenote/notebooks/microsoft.graph.getNotebookFromWebUrl",siteid: string):operation5589,
    (api:"/sites/{site-id}/onenote/notebooks/microsoft.graph.getRecentNotebooks(includePersonalNotebooks={includePersonalNotebooks})",siteid: string,includePersonalNotebooks: string):operation5590,
    (api:"/sites/{site-id}/onenote/operations",siteid: string):operation5591,
    (api:"/sites/{site-id}/onenote/operations/{onenoteOperation-id}",siteid: string,onenoteOperationid: string):operation5592,
    (api:"/sites/{site-id}/onenote/operations/$count",siteid: string):operation5593,
    (api:"/sites/{site-id}/onenote/pages",siteid: string):operation5594,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}",siteid: string,onenotePageid: string):operation5595,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/content",siteid: string,onenotePageid: string):operation5596,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.copyToSection",siteid: string,onenotePageid: string):operation5597,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",siteid: string,onenotePageid: string):operation5598,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/microsoft.graph.preview()",siteid: string,onenotePageid: string):operation5599,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/parentNotebook",siteid: string,onenotePageid: string):operation5600,
    (api:"/sites/{site-id}/onenote/pages/{onenotePage-id}/parentSection",siteid: string,onenotePageid: string):operation5601,
    (api:"/sites/{site-id}/onenote/pages/$count",siteid: string):operation5602,
    (api:"/sites/{site-id}/onenote/resources",siteid: string):operation5603,
    (api:"/sites/{site-id}/onenote/resources/{onenoteResource-id}",siteid: string,onenoteResourceid: string):operation5604,
    (api:"/sites/{site-id}/onenote/resources/{onenoteResource-id}/content",siteid: string,onenoteResourceid: string):operation5605,
    (api:"/sites/{site-id}/onenote/resources/$count",siteid: string):operation5606,
    (api:"/sites/{site-id}/onenote/sectionGroups",siteid: string):operation5607,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}",siteid: string,sectionGroupid: string):operation5608,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentNotebook",siteid: string,sectionGroupid: string):operation5609,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup",siteid: string,sectionGroupid: string):operation5610,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups",siteid: string,sectionGroupid: string):operation5611,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}",siteid: string,sectionGroupid: string,sectionGroupid1: string):operation5612,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count",siteid: string,sectionGroupid: string):operation5613,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections",siteid: string,sectionGroupid: string):operation5614,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5615,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5616,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5617,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5618,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5619,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5620,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5621,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5622,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5623,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5624,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",siteid: string,sectionGroupid: string,onenoteSectionid: string,onenotePageid: string):operation5625,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages/$count",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5626,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentNotebook",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5627,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/parentSectionGroup",siteid: string,sectionGroupid: string,onenoteSectionid: string):operation5628,
    (api:"/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sections/$count",siteid: string,sectionGroupid: string):operation5629,
    (api:"/sites/{site-id}/onenote/sectionGroups/$count",siteid: string):operation5630,
    (api:"/sites/{site-id}/onenote/sections",siteid: string):operation5631,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}",siteid: string,onenoteSectionid: string):operation5632,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToNotebook",siteid: string,onenoteSectionid: string):operation5633,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/microsoft.graph.copyToSectionGroup",siteid: string,onenoteSectionid: string):operation5634,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages",siteid: string,onenoteSectionid: string):operation5635,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5636,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/content",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5637,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.copyToSection",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5638,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.onenotePatchContent",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5639,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/microsoft.graph.preview()",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5640,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentNotebook",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5641,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/{onenotePage-id}/parentSection",siteid: string,onenoteSectionid: string,onenotePageid: string):operation5642,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/pages/$count",siteid: string,onenoteSectionid: string):operation5643,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/parentNotebook",siteid: string,onenoteSectionid: string):operation5644,
    (api:"/sites/{site-id}/onenote/sections/{onenoteSection-id}/parentSectionGroup",siteid: string,onenoteSectionid: string):operation5645,
    (api:"/sites/{site-id}/onenote/sections/$count",siteid: string):operation5646,

    }
}

export {};