import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation7726, operation7727, operation7728, operation7729, operation7730, operation7731, operation7732, operation7733, operation7734, operation7735, operation7736, operation7737, operation7738, operation7739, operation7740, operation7741, operation7742, operation7743, operation7744, operation7745, operation7746, operation7747, operation7748, operation7749, operation7750, operation7751, operation7752, operation7753, operation7754, operation7755, operation7756, operation7757, operation7758, operation7759, operation7760, operation7761, operation7762, operation7763, operation7764, operation7765, operation7766, operation7767, operation7768, operation7769, operation7770, operation7771, operation7772, operation7773, operation7774, operation7775, operation7776, operation7777, operation7778, operation7779, operation7780, operation7781, operation7782 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/workbooks"):operation7726,
(api:"/workbooks/{driveItem-id}",driveItemid: string):operation7727,
(api:"/workbooks/{driveItem-id}/analytics",driveItemid: string):operation7728,
(api:"/workbooks/{driveItem-id}/children",driveItemid: string):operation7729,
(api:"/workbooks/{driveItem-id}/children/{driveItem-id1}",driveItemid: string,driveItemid1: string):operation7730,
(api:"/workbooks/{driveItem-id}/children/{driveItem-id1}/content",driveItemid: string,driveItemid1: string):operation7731,
(api:"/workbooks/{driveItem-id}/children/$count",driveItemid: string):operation7732,
(api:"/workbooks/{driveItem-id}/content",driveItemid: string):operation7733,
(api:"/workbooks/{driveItem-id}/listItem",driveItemid: string):operation7734,
(api:"/workbooks/{driveItem-id}/listItem/analytics",driveItemid: string):operation7735,
(api:"/workbooks/{driveItem-id}/listItem/documentSetVersions",driveItemid: string):operation7736,
(api:"/workbooks/{driveItem-id}/listItem/documentSetVersions/{documentSetVersion-id}",driveItemid: string,documentSetVersionid: string):operation7737,
(api:"/workbooks/{driveItem-id}/listItem/documentSetVersions/{documentSetVersion-id}/microsoft.graph.restore",driveItemid: string,documentSetVersionid: string):operation7738,
(api:"/workbooks/{driveItem-id}/listItem/documentSetVersions/$count",driveItemid: string):operation7739,
(api:"/workbooks/{driveItem-id}/listItem/driveItem",driveItemid: string):operation7740,
(api:"/workbooks/{driveItem-id}/listItem/driveItem/content",driveItemid: string):operation7741,
(api:"/workbooks/{driveItem-id}/listItem/fields",driveItemid: string):operation7742,
(api:"/workbooks/{driveItem-id}/listItem/microsoft.graph.getActivitiesByInterval()",driveItemid: string):operation7743,
(api:"/workbooks/{driveItem-id}/listItem/microsoft.graph.getActivitiesByInterval(startDateTime='{startDateTime}',endDateTime='{endDateTime}',interval='{interval}')",driveItemid: string,startDateTime: string,endDateTime: string,interval: string):operation7744,
(api:"/workbooks/{driveItem-id}/listItem/versions",driveItemid: string):operation7745,
(api:"/workbooks/{driveItem-id}/listItem/versions/{listItemVersion-id}",driveItemid: string,listItemVersionid: string):operation7746,
(api:"/workbooks/{driveItem-id}/listItem/versions/{listItemVersion-id}/fields",driveItemid: string,listItemVersionid: string):operation7747,
(api:"/workbooks/{driveItem-id}/listItem/versions/{listItemVersion-id}/microsoft.graph.restoreVersion",driveItemid: string,listItemVersionid: string):operation7748,
(api:"/workbooks/{driveItem-id}/listItem/versions/$count",driveItemid: string):operation7749,
(api:"/workbooks/{driveItem-id}/microsoft.graph.checkin",driveItemid: string):operation7750,
(api:"/workbooks/{driveItem-id}/microsoft.graph.checkout",driveItemid: string):operation7751,
(api:"/workbooks/{driveItem-id}/microsoft.graph.copy",driveItemid: string):operation7752,
(api:"/workbooks/{driveItem-id}/microsoft.graph.createLink",driveItemid: string):operation7753,
(api:"/workbooks/{driveItem-id}/microsoft.graph.createUploadSession",driveItemid: string):operation7754,
(api:"/workbooks/{driveItem-id}/microsoft.graph.delta()",driveItemid: string):operation7755,
(api:"/workbooks/{driveItem-id}/microsoft.graph.delta(token='{token}')",driveItemid: string,token: string):operation7756,
(api:"/workbooks/{driveItem-id}/microsoft.graph.follow",driveItemid: string):operation7757,
(api:"/workbooks/{driveItem-id}/microsoft.graph.getActivitiesByInterval()",driveItemid: string):operation7758,
(api:"/workbooks/{driveItem-id}/microsoft.graph.getActivitiesByInterval(startDateTime='{startDateTime}',endDateTime='{endDateTime}',interval='{interval}')",driveItemid: string,startDateTime: string,endDateTime: string,interval: string):operation7759,
(api:"/workbooks/{driveItem-id}/microsoft.graph.invite",driveItemid: string):operation7760,
(api:"/workbooks/{driveItem-id}/microsoft.graph.preview",driveItemid: string):operation7761,
(api:"/workbooks/{driveItem-id}/microsoft.graph.restore",driveItemid: string):operation7762,
(api:"/workbooks/{driveItem-id}/microsoft.graph.search(q='{q}')",driveItemid: string,q: string):operation7763,
(api:"/workbooks/{driveItem-id}/microsoft.graph.unfollow",driveItemid: string):operation7764,
(api:"/workbooks/{driveItem-id}/microsoft.graph.validatePermission",driveItemid: string):operation7765,
(api:"/workbooks/{driveItem-id}/permissions",driveItemid: string):operation7766,
(api:"/workbooks/{driveItem-id}/permissions/{permission-id}",driveItemid: string,permissionid: string):operation7767,
(api:"/workbooks/{driveItem-id}/permissions/{permission-id}/microsoft.graph.grant",driveItemid: string,permissionid: string):operation7768,
(api:"/workbooks/{driveItem-id}/permissions/$count",driveItemid: string):operation7769,
(api:"/workbooks/{driveItem-id}/subscriptions",driveItemid: string):operation7770,
(api:"/workbooks/{driveItem-id}/subscriptions/{subscription-id}",driveItemid: string,subscriptionid: string):operation7771,
(api:"/workbooks/{driveItem-id}/subscriptions/{subscription-id}/microsoft.graph.reauthorize",driveItemid: string,subscriptionid: string):operation7772,
(api:"/workbooks/{driveItem-id}/subscriptions/$count",driveItemid: string):operation7773,
(api:"/workbooks/{driveItem-id}/thumbnails",driveItemid: string):operation7774,
(api:"/workbooks/{driveItem-id}/thumbnails/{thumbnailSet-id}",driveItemid: string,thumbnailSetid: string):operation7775,
(api:"/workbooks/{driveItem-id}/thumbnails/$count",driveItemid: string):operation7776,
(api:"/workbooks/{driveItem-id}/versions",driveItemid: string):operation7777,
(api:"/workbooks/{driveItem-id}/versions/{driveItemVersion-id}",driveItemid: string,driveItemVersionid: string):operation7778,
(api:"/workbooks/{driveItem-id}/versions/{driveItemVersion-id}/content",driveItemid: string,driveItemVersionid: string):operation7779,
(api:"/workbooks/{driveItem-id}/versions/{driveItemVersion-id}/microsoft.graph.restoreVersion",driveItemid: string,driveItemVersionid: string):operation7780,
(api:"/workbooks/{driveItem-id}/versions/$count",driveItemid: string):operation7781,
(api:"/workbooks/$count"):operation7782,

    }
}

export {};