import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation3132, operation3133, operation3134, operation3135, operation3136, operation3137, operation3138, operation3139, operation3140, operation3141, operation3142, operation3143, operation3144, operation3145, operation3146, operation3840, operation3841, operation3842, operation3843, operation3844, operation3845, operation3846, operation3847, operation3848, operation3849, operation3850, operation3851, operation3852, operation3853, operation3854, operation3855, operation3856, operation3857, operation4095, operation4096, operation4097, operation4098, operation4099, operation4100, operation4101, operation4102, operation4103, operation4104, operation4105, operation4106, operation4107, operation4108, operation4109, operation4110, operation4111, operation4112, operation4113, operation4114, operation4115, operation4116, operation4117, operation4118, operation4253, operation4254, operation4255, operation4340, operation4341, operation4342, operation4343, operation4344, operation4345, operation4346, operation4347, operation4348, operation4349, operation4350, operation4351, operation4352, operation4353, operation4354, operation4355, operation4356, operation4357, operation4358, operation4359, operation4360, operation4361, operation4362, operation4363, operation4364, operation4365, operation4366, operation4367, operation4368, operation4369, operation4370, operation4371, operation4372, operation4373, operation4374, operation4375, operation4376, operation4377, operation4378, operation4379, operation4380, operation4381, operation4382, operation4383, operation4384, operation4385, operation4386, operation4387, operation4388, operation4389, operation4390, operation4391, operation4392, operation4393, operation4421, operation4422, operation4423, operation4424, operation4425, operation4426, operation4427, operation4428, operation4429, operation4430, operation4431, operation4432, operation4433, operation4434, operation4435, operation4436, operation4437, operation4438, operation4439, operation4440, operation4441, operation4442, operation4546, operation4547, operation4548, operation4549, operation4550, operation4551, operation4552, operation4553, operation4554, operation4555, operation4556, operation4557, operation4561, operation4562, operation4563, operation4564, operation4565, operation4566, operation4567, operation4568, operation4569, operation4570, operation4571, operation4572, operation4573, operation4574, operation4575, operation4576, operation4577, operation4578, operation4579, operation4580, operation4581, operation4582, operation4583, operation4584, operation4585, operation4586, operation4587, operation4588, operation4589, operation4590, operation4591, operation4592, operation4593, operation4594, operation4595, operation4596, operation4626, operation4627, operation4628, operation4629, operation4630, operation4631, operation4632, operation4633, operation4634, operation4635, operation4636, operation4637, operation4638, operation4639, operation4640, operation4641, operation4642, operation4643, operation4644, operation4645, operation4646, operation4647, operation4648, operation4649, operation4650, operation4651, operation4652, operation4653, operation4654, operation4655, operation4656, operation4687, operation4688, operation4689, operation4690, operation4691, operation4692, operation4693, operation4694, operation4695, operation4696, operation4697, operation4698, operation4699, operation4700, operation4701, operation4702, operation4703, operation4704, operation4705, operation4706, operation4707, operation6144, operation6145, operation6146, operation6147, operation6148, operation6149, operation6150, operation6151, operation6152, operation6153, operation6154, operation6155, operation6156, operation6157, operation6158, operation6159, operation6853, operation6854, operation6855, operation6856, operation6857, operation6858, operation6859, operation6860, operation6861, operation6862, operation6863, operation6864, operation6865, operation6866, operation6867, operation6868, operation6869, operation6870, operation7108, operation7109, operation7110, operation7111, operation7112, operation7113, operation7114, operation7115, operation7116, operation7117, operation7118, operation7119, operation7120, operation7121, operation7122, operation7123, operation7124, operation7125, operation7126, operation7127, operation7128, operation7129, operation7130, operation7131, operation7266, operation7267, operation7268, operation7353, operation7354, operation7355, operation7356, operation7357, operation7358, operation7359, operation7360, operation7361, operation7362, operation7363, operation7364, operation7365, operation7366, operation7367, operation7368, operation7369, operation7370, operation7371, operation7372, operation7373, operation7374, operation7375, operation7376, operation7377, operation7378, operation7379, operation7380, operation7381, operation7382, operation7383, operation7384, operation7385, operation7386, operation7387, operation7388, operation7389, operation7390, operation7391, operation7392, operation7393, operation7394, operation7395, operation7396, operation7397, operation7398, operation7399, operation7400, operation7401, operation7402, operation7403, operation7404, operation7405, operation7406, operation7434, operation7435, operation7436, operation7437, operation7438, operation7439, operation7440, operation7441, operation7442, operation7443, operation7444, operation7445, operation7446, operation7447, operation7448, operation7449, operation7450, operation7451, operation7452, operation7453, operation7454, operation7455, operation7570, operation7574, operation7575, operation7576, operation7577, operation7578, operation7579, operation7580, operation7581, operation7582, operation7583, operation7584, operation7585, operation7586, operation7587, operation7588, operation7589, operation7590, operation7591, operation7592, operation7593, operation7594, operation7595, operation7596, operation7597, operation7598, operation7599, operation7600, operation7601, operation7602, operation7603, operation7604, operation7605, operation7606, operation7607, operation7608, operation7609, operation7639, operation7640, operation7641, operation7642, operation7643, operation7644, operation7645, operation7646, operation7647, operation7648, operation7649, operation7650, operation7651, operation7652, operation7653, operation7654, operation7655, operation7656, operation7657, operation7658, operation7659, operation7660, operation7661, operation7662, operation7663, operation7664, operation7665, operation7666, operation7667, operation7668, operation7669, operation7700, operation7701, operation7702, operation7703, operation7704, operation7705, operation7706, operation7707, operation7708, operation7709, operation7710, operation7711, operation7712, operation7713, operation7714, operation7715, operation7716, operation7717, operation7718, operation7719, operation7720, operation7721, operation7722, operation7723, operation7724, operation7725 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api: "/users"): operation6144,
        (api: "/users/{user-id}", userid: string): operation6145,

        (api: "/users/{user-id}/agreementAcceptances", userid: string): operation6154,
        (api: "/users/{user-id}/agreementAcceptances/{agreementAcceptance-id}", userid: string, agreementAcceptanceid: string): operation6155,
        (api: "/users/{user-id}/agreementAcceptances/$count", userid: string): operation6156,
        (api: "/users/{user-id}/appRoleAssignments", userid: string): operation6157,
        (api: "/users/{user-id}/appRoleAssignments/{appRoleAssignment-id}", userid: string, appRoleAssignmentid: string): operation6158,
        (api: "/users/{user-id}/appRoleAssignments/$count", userid: string): operation6159,
        (api: "/users/{user-id}/createdObjects", userid: string): operation6853,
        (api: "/users/{user-id}/createdObjects/{directoryObject-id}", userid: string, directoryObjectid: string): operation6854,
        (api: "/users/{user-id}/createdObjects/{directoryObject-id}/microsoft.graph.servicePrincipal", userid: string, directoryObjectid: string): operation6855,
        (api: "/users/{user-id}/createdObjects/$count", userid: string): operation6856,
        (api: "/users/{user-id}/createdObjects/microsoft.graph.servicePrincipal", userid: string): operation6857,
        (api: "/users/{user-id}/createdObjects/microsoft.graph.servicePrincipal/$count", userid: string): operation6858,
        (api: "/users/{user-id}/deviceManagementTroubleshootingEvents", userid: string): operation6859,
        (api: "/users/{user-id}/deviceManagementTroubleshootingEvents/{deviceManagementTroubleshootingEvent-id}", userid: string, deviceManagementTroubleshootingEventid: string): operation6860,
        (api: "/users/{user-id}/deviceManagementTroubleshootingEvents/$count", userid: string): operation6861,
        (api: "/users/{user-id}/directReports", userid: string): operation6862,
        (api: "/users/{user-id}/directReports/{directoryObject-id}", userid: string, directoryObjectid: string): operation6863,
        (api: "/users/{user-id}/directReports/{directoryObject-id}/microsoft.graph.orgContact", userid: string, directoryObjectid: string): operation6864,
        (api: "/users/{user-id}/directReports/{directoryObject-id}/microsoft.graph.user", userid: string, directoryObjectid: string): operation6865,
        (api: "/users/{user-id}/directReports/$count", userid: string): operation6866,
        (api: "/users/{user-id}/directReports/microsoft.graph.orgContact", userid: string): operation6867,
        (api: "/users/{user-id}/directReports/microsoft.graph.orgContact/$count", userid: string): operation6868,
        (api: "/users/{user-id}/directReports/microsoft.graph.user", userid: string): operation6869,
        (api: "/users/{user-id}/directReports/microsoft.graph.user/$count", userid: string): operation6870,
        (api: "/users/{user-id}/extensions", userid: string): operation7108,
        (api: "/users/{user-id}/extensions/{extension-id}", userid: string, extensionid: string): operation7109,
        (api: "/users/{user-id}/extensions/$count", userid: string): operation7110,
        (api: "/users/{user-id}/followedSites", userid: string): operation7111,
        (api: "/users/{user-id}/followedSites/{site-id}", userid: string, siteid: string): operation7112,
        (api: "/users/{user-id}/followedSites/$count", userid: string): operation7113,
        (api: "/users/{user-id}/inferenceClassification", userid: string): operation7114,
        (api: "/users/{user-id}/inferenceClassification/overrides", userid: string): operation7115,
        (api: "/users/{user-id}/inferenceClassification/overrides/{inferenceClassificationOverride-id}", userid: string, inferenceClassificationOverrideid: string): operation7116,
        (api: "/users/{user-id}/inferenceClassification/overrides/$count", userid: string): operation7117,
        (api: "/users/{user-id}/insights", userid: string): operation7118,
        (api: "/users/{user-id}/insights/shared", userid: string): operation7119,
        (api: "/users/{user-id}/insights/shared/{sharedInsight-id}", userid: string, sharedInsightid: string): operation7120,
        (api: "/users/{user-id}/insights/shared/{sharedInsight-id}/lastSharedMethod", userid: string, sharedInsightid: string): operation7121,
        (api: "/users/{user-id}/insights/shared/{sharedInsight-id}/resource", userid: string, sharedInsightid: string): operation7122,
        (api: "/users/{user-id}/insights/shared/$count", userid: string): operation7123,
        (api: "/users/{user-id}/insights/trending", userid: string): operation7124,
        (api: "/users/{user-id}/insights/trending/{trending-id}", userid: string, trendingid: string): operation7125,
        (api: "/users/{user-id}/insights/trending/{trending-id}/resource", userid: string, trendingid: string): operation7126,
        (api: "/users/{user-id}/insights/trending/$count", userid: string): operation7127,
        (api: "/users/{user-id}/insights/used", userid: string): operation7128,
        (api: "/users/{user-id}/insights/used/{usedInsight-id}", userid: string, usedInsightid: string): operation7129,
        (api: "/users/{user-id}/insights/used/{usedInsight-id}/resource", userid: string, usedInsightid: string): operation7130,
        (api: "/users/{user-id}/insights/used/$count", userid: string): operation7131,
        (api: "/users/{user-id}/licenseDetails", userid: string): operation7266,
        (api: "/users/{user-id}/licenseDetails/{licenseDetails-id}", userid: string, licenseDetailsid: string): operation7267,
        (api: "/users/{user-id}/licenseDetails/$count", userid: string): operation7268,

        (api: "/users/{user-id}/managedAppRegistrations", userid: string): operation7353,
        (api: "/users/{user-id}/managedAppRegistrations/{managedAppRegistration-id}", userid: string, managedAppRegistrationid: string): operation7354,
        (api: "/users/{user-id}/managedAppRegistrations/$count", userid: string): operation7355,
        (api: "/users/{user-id}/managedDevices", userid: string): operation7356,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}", userid: string, managedDeviceid: string): operation7357,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceCategory", userid: string, managedDeviceid: string): operation7358,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates", userid: string, managedDeviceid: string): operation7359,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/{deviceCompliancePolicyState-id}", userid: string, managedDeviceid: string, deviceCompliancePolicyStateid: string): operation7360,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/$count", userid: string, managedDeviceid: string): operation7361,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceConfigurationStates", userid: string, managedDeviceid: string): operation7362,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceConfigurationStates/{deviceConfigurationState-id}", userid: string, managedDeviceid: string, deviceConfigurationStateid: string): operation7363,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/deviceConfigurationStates/$count", userid: string, managedDeviceid: string): operation7364,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.bypassActivationLock", userid: string, managedDeviceid: string): operation7365,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.cleanWindowsDevice", userid: string, managedDeviceid: string): operation7366,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.deleteUserFromSharedAppleDevice", userid: string, managedDeviceid: string): operation7367,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.disableLostMode", userid: string, managedDeviceid: string): operation7368,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.locateDevice", userid: string, managedDeviceid: string): operation7369,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.logoutSharedAppleDeviceActiveUser", userid: string, managedDeviceid: string): operation7370,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.rebootNow", userid: string, managedDeviceid: string): operation7371,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.recoverPasscode", userid: string, managedDeviceid: string): operation7372,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.remoteLock", userid: string, managedDeviceid: string): operation7373,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.requestRemoteAssistance", userid: string, managedDeviceid: string): operation7374,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.resetPasscode", userid: string, managedDeviceid: string): operation7375,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.retire", userid: string, managedDeviceid: string): operation7376,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.shutDown", userid: string, managedDeviceid: string): operation7377,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.syncDevice", userid: string, managedDeviceid: string): operation7378,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.updateWindowsDeviceAccount", userid: string, managedDeviceid: string): operation7379,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderScan", userid: string, managedDeviceid: string): operation7380,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderUpdateSignatures", userid: string, managedDeviceid: string): operation7381,
        (api: "/users/{user-id}/managedDevices/{managedDevice-id}/microsoft.graph.wipe", userid: string, managedDeviceid: string): operation7382,
        (api: "/users/{user-id}/managedDevices/$count", userid: string): operation7383,
        (api: "/users/{user-id}/manager", userid: string): operation7384,
        (api: "/users/{user-id}/manager/$ref", userid: string): operation7385,
        (api: "/users/{user-id}/memberOf", userid: string): operation7386,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}", userid: string, directoryObjectid: string): operation7387,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.application", userid: string, directoryObjectid: string): operation7388,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.device", userid: string, directoryObjectid: string): operation7389,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.group", userid: string, directoryObjectid: string): operation7390,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.orgContact", userid: string, directoryObjectid: string): operation7391,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.servicePrincipal", userid: string, directoryObjectid: string): operation7392,
        (api: "/users/{user-id}/memberOf/{directoryObject-id}/microsoft.graph.user", userid: string, directoryObjectid: string): operation7393,
        (api: "/users/{user-id}/memberOf/$count", userid: string): operation7394,
        (api: "/users/{user-id}/memberOf/microsoft.graph.application", userid: string): operation7395,
        (api: "/users/{user-id}/memberOf/microsoft.graph.application/$count", userid: string): operation7396,
        (api: "/users/{user-id}/memberOf/microsoft.graph.device", userid: string): operation7397,
        (api: "/users/{user-id}/memberOf/microsoft.graph.device/$count", userid: string): operation7398,
        (api: "/users/{user-id}/memberOf/microsoft.graph.group", userid: string): operation7399,
        (api: "/users/{user-id}/memberOf/microsoft.graph.group/$count", userid: string): operation7400,
        (api: "/users/{user-id}/memberOf/microsoft.graph.orgContact", userid: string): operation7401,
        (api: "/users/{user-id}/memberOf/microsoft.graph.orgContact/$count", userid: string): operation7402,
        (api: "/users/{user-id}/memberOf/microsoft.graph.servicePrincipal", userid: string): operation7403,
        (api: "/users/{user-id}/memberOf/microsoft.graph.servicePrincipal/$count", userid: string): operation7404,
        (api: "/users/{user-id}/memberOf/microsoft.graph.user", userid: string): operation7405,
        (api: "/users/{user-id}/memberOf/microsoft.graph.user/$count", userid: string): operation7406,

        (api: "/users/{user-id}/microsoft.graph.assignLicense", userid: string): operation7434,
        (api: "/users/{user-id}/microsoft.graph.changePassword", userid: string): operation7435,
        (api: "/users/{user-id}/microsoft.graph.checkMemberGroups", userid: string): operation7436,
        (api: "/users/{user-id}/microsoft.graph.checkMemberObjects", userid: string): operation7437,
        (api: "/users/{user-id}/microsoft.graph.exportPersonalData", userid: string): operation7438,
        (api: "/users/{user-id}/microsoft.graph.findMeetingTimes", userid: string): operation7439,
        (api: "/users/{user-id}/microsoft.graph.getMailTips", userid: string): operation7440,
        (api: "/users/{user-id}/microsoft.graph.getManagedAppDiagnosticStatuses()", userid: string): operation7441,
        (api: "/users/{user-id}/microsoft.graph.getManagedAppPolicies()", userid: string): operation7442,
        (api: "/users/{user-id}/microsoft.graph.getMemberGroups", userid: string): operation7443,
        (api: "/users/{user-id}/microsoft.graph.getMemberObjects", userid: string): operation7444,
        (api: "/users/{user-id}/microsoft.graph.reminderView(StartDateTime='{StartDateTime}',EndDateTime='{EndDateTime}')", userid: string, StartDateTime: string, EndDateTime: string): operation7445,
        (api: "/users/{user-id}/microsoft.graph.removeAllDevicesFromManagement", userid: string): operation7446,
        (api: "/users/{user-id}/microsoft.graph.reprocessLicenseAssignment", userid: string): operation7447,
        (api: "/users/{user-id}/microsoft.graph.restore", userid: string): operation7448,
        (api: "/users/{user-id}/microsoft.graph.revokeSignInSessions", userid: string): operation7449,
        (api: "/users/{user-id}/microsoft.graph.sendMail", userid: string): operation7450,
        (api: "/users/{user-id}/microsoft.graph.translateExchangeIds", userid: string): operation7451,
        (api: "/users/{user-id}/microsoft.graph.wipeManagedAppRegistrationsByDeviceTag", userid: string): operation7452,
        (api: "/users/{user-id}/oauth2PermissionGrants", userid: string): operation7453,
        (api: "/users/{user-id}/oauth2PermissionGrants/{oAuth2PermissionGrant-id}", userid: string, oAuth2PermissionGrantid: string): operation7454,
        (api: "/users/{user-id}/oauth2PermissionGrants/$count", userid: string): operation7455,


        (api: "/users/{user-id}/outlook", userid: string): operation7570,

        (api: "/users/{user-id}/outlook/microsoft.graph.supportedLanguages()", userid: string): operation7574,
        (api: "/users/{user-id}/outlook/microsoft.graph.supportedTimeZones()", userid: string): operation7575,
        (api: "/users/{user-id}/outlook/microsoft.graph.supportedTimeZones(TimeZoneStandard='{TimeZoneStandard}')", userid: string, TimeZoneStandard: string): operation7576,
        (api: "/users/{user-id}/ownedDevices", userid: string): operation7577,
        (api: "/users/{user-id}/ownedDevices/{directoryObject-id}", userid: string, directoryObjectid: string): operation7578,
        (api: "/users/{user-id}/ownedDevices/{directoryObject-id}/microsoft.graph.appRoleAssignment", userid: string, directoryObjectid: string): operation7579,
        (api: "/users/{user-id}/ownedDevices/{directoryObject-id}/microsoft.graph.device", userid: string, directoryObjectid: string): operation7580,
        (api: "/users/{user-id}/ownedDevices/{directoryObject-id}/microsoft.graph.endpoint", userid: string, directoryObjectid: string): operation7581,
        (api: "/users/{user-id}/ownedDevices/$count", userid: string): operation7582,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.appRoleAssignment", userid: string): operation7583,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.appRoleAssignment/$count", userid: string): operation7584,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.device", userid: string): operation7585,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.device/$count", userid: string): operation7586,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.endpoint", userid: string): operation7587,
        (api: "/users/{user-id}/ownedDevices/microsoft.graph.endpoint/$count", userid: string): operation7588,
        (api: "/users/{user-id}/ownedObjects", userid: string): operation7589,
        (api: "/users/{user-id}/ownedObjects/{directoryObject-id}", userid: string, directoryObjectid: string): operation7590,
        (api: "/users/{user-id}/ownedObjects/{directoryObject-id}/microsoft.graph.application", userid: string, directoryObjectid: string): operation7591,
        (api: "/users/{user-id}/ownedObjects/{directoryObject-id}/microsoft.graph.group", userid: string, directoryObjectid: string): operation7592,
        (api: "/users/{user-id}/ownedObjects/{directoryObject-id}/microsoft.graph.servicePrincipal", userid: string, directoryObjectid: string): operation7593,
        (api: "/users/{user-id}/ownedObjects/$count", userid: string): operation7594,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.application", userid: string): operation7595,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.application/$count", userid: string): operation7596,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.group", userid: string): operation7597,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.group/$count", userid: string): operation7598,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.servicePrincipal", userid: string): operation7599,
        (api: "/users/{user-id}/ownedObjects/microsoft.graph.servicePrincipal/$count", userid: string): operation7600,
        (api: "/users/{user-id}/people", userid: string): operation7601,
        (api: "/users/{user-id}/people/{person-id}", userid: string, personid: string): operation7602,
        (api: "/users/{user-id}/people/$count", userid: string): operation7603,
        (api: "/users/{user-id}/photo", userid: string): operation7604,
        (api: "/users/{user-id}/photo/$value", userid: string): operation7605,
        (api: "/users/{user-id}/photos", userid: string): operation7606,
        (api: "/users/{user-id}/photos/{profilePhoto-id}", userid: string, profilePhotoid: string): operation7607,
        (api: "/users/{user-id}/photos/{profilePhoto-id}/$value", userid: string, profilePhotoid: string): operation7608,
        (api: "/users/{user-id}/photos/$count", userid: string): operation7609,

        (api: "/users/{user-id}/presence", userid: string): operation7639,
        (api: "/users/{user-id}/presence/microsoft.graph.clearPresence", userid: string): operation7640,
        (api: "/users/{user-id}/presence/microsoft.graph.clearUserPreferredPresence", userid: string): operation7641,
        (api: "/users/{user-id}/presence/microsoft.graph.setPresence", userid: string): operation7642,
        (api: "/users/{user-id}/presence/microsoft.graph.setUserPreferredPresence", userid: string): operation7643,
        (api: "/users/{user-id}/registeredDevices", userid: string): operation7644,
        (api: "/users/{user-id}/registeredDevices/{directoryObject-id}", userid: string, directoryObjectid: string): operation7645,
        (api: "/users/{user-id}/registeredDevices/{directoryObject-id}/microsoft.graph.appRoleAssignment", userid: string, directoryObjectid: string): operation7646,
        (api: "/users/{user-id}/registeredDevices/{directoryObject-id}/microsoft.graph.device", userid: string, directoryObjectid: string): operation7647,
        (api: "/users/{user-id}/registeredDevices/{directoryObject-id}/microsoft.graph.endpoint", userid: string, directoryObjectid: string): operation7648,
        (api: "/users/{user-id}/registeredDevices/$count", userid: string): operation7649,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.appRoleAssignment", userid: string): operation7650,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.appRoleAssignment/$count", userid: string): operation7651,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.device", userid: string): operation7652,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.device/$count", userid: string): operation7653,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.endpoint", userid: string): operation7654,
        (api: "/users/{user-id}/registeredDevices/microsoft.graph.endpoint/$count", userid: string): operation7655,
        (api: "/users/{user-id}/scopedRoleMemberOf", userid: string): operation7656,
        (api: "/users/{user-id}/scopedRoleMemberOf/{scopedRoleMembership-id}", userid: string, scopedRoleMembershipid: string): operation7657,
        (api: "/users/{user-id}/scopedRoleMemberOf/$count", userid: string): operation7658,
        (api: "/users/{user-id}/settings", userid: string): operation7659,
        (api: "/users/{user-id}/settings/shiftPreferences", userid: string): operation7660,
        (api: "/users/{user-id}/teamwork", userid: string): operation7661,
        (api: "/users/{user-id}/teamwork/associatedTeams", userid: string): operation7662,
        (api: "/users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}", userid: string, associatedTeamInfoid: string): operation7663,
        (api: "/users/{user-id}/teamwork/associatedTeams/$count", userid: string): operation7664,
        (api: "/users/{user-id}/teamwork/installedApps", userid: string): operation7665,
        (api: "/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}", userid: string, userScopeTeamsAppInstallationid: string): operation7666,
        (api: "/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}/chat", userid: string, userScopeTeamsAppInstallationid: string): operation7667,
        (api: "/users/{user-id}/teamwork/installedApps/$count", userid: string): operation7668,
        (api: "/users/{user-id}/teamwork/microsoft.graph.sendActivityNotification", userid: string): operation7669,

        (api: "/users/{user-id}/transitiveMemberOf", userid: string): operation7700,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}", userid: string, directoryObjectid: string): operation7701,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.application", userid: string, directoryObjectid: string): operation7702,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.device", userid: string, directoryObjectid: string): operation7703,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.group", userid: string, directoryObjectid: string): operation7704,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.orgContact", userid: string, directoryObjectid: string): operation7705,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.servicePrincipal", userid: string, directoryObjectid: string): operation7706,
        (api: "/users/{user-id}/transitiveMemberOf/{directoryObject-id}/microsoft.graph.user", userid: string, directoryObjectid: string): operation7707,
        (api: "/users/{user-id}/transitiveMemberOf/$count", userid: string): operation7708,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.application", userid: string): operation7709,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.application/$count", userid: string): operation7710,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.device", userid: string): operation7711,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.device/$count", userid: string): operation7712,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.group", userid: string): operation7713,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.group/$count", userid: string): operation7714,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.orgContact", userid: string): operation7715,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.orgContact/$count", userid: string): operation7716,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.servicePrincipal", userid: string): operation7717,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.servicePrincipal/$count", userid: string): operation7718,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.user", userid: string): operation7719,
        (api: "/users/{user-id}/transitiveMemberOf/microsoft.graph.user/$count", userid: string): operation7720,
        (api: "/users/$count"): operation7721,
        (api: "/users/microsoft.graph.delta()"): operation7722,
        (api: "/users/microsoft.graph.getAvailableExtensionProperties"): operation7723,
        (api: "/users/microsoft.graph.getByIds"): operation7724,
        (api: "/users/microsoft.graph.validateProperties"): operation7725,

        (api: "/me"): operation3132,

        (api: "/me/agreementAcceptances"): operation3141,
        (api: "/me/agreementAcceptances/{agreementAcceptance-id}", agreementAcceptanceid: string): operation3142,
        (api: "/me/agreementAcceptances/$count"): operation3143,
        (api: "/me/appRoleAssignments"): operation3144,
        (api: "/me/appRoleAssignments/{appRoleAssignment-id}", appRoleAssignmentid: string): operation3145,
        (api: "/me/appRoleAssignments/$count"): operation3146,
        (api: "/me/createdObjects"): operation3840,
        (api: "/me/createdObjects/{directoryObject-id}", directoryObjectid: string): operation3841,
        (api: "/me/createdObjects/{directoryObject-id}/microsoft.graph.servicePrincipal", directoryObjectid: string): operation3842,
        (api: "/me/createdObjects/$count"): operation3843,
        (api: "/me/createdObjects/microsoft.graph.servicePrincipal"): operation3844,
        (api: "/me/createdObjects/microsoft.graph.servicePrincipal/$count"): operation3845,
        (api: "/me/deviceManagementTroubleshootingEvents"): operation3846,
        (api: "/me/deviceManagementTroubleshootingEvents/{deviceManagementTroubleshootingEvent-id}", deviceManagementTroubleshootingEventid: string): operation3847,
        (api: "/me/deviceManagementTroubleshootingEvents/$count"): operation3848,
        (api: "/me/directReports"): operation3849,
        (api: "/me/directReports/{directoryObject-id}", directoryObjectid: string): operation3850,
        (api: "/me/directReports/{directoryObject-id}/microsoft.graph.orgContact", directoryObjectid: string): operation3851,
        (api: "/me/directReports/{directoryObject-id}/microsoft.graph.user", directoryObjectid: string): operation3852,
        (api: "/me/directReports/$count"): operation3853,
        (api: "/me/directReports/microsoft.graph.orgContact"): operation3854,
        (api: "/me/directReports/microsoft.graph.orgContact/$count"): operation3855,
        (api: "/me/directReports/microsoft.graph.user"): operation3856,
        (api: "/me/directReports/microsoft.graph.user/$count"): operation3857,

        (api: "/me/extensions"): operation4095,
        (api: "/me/extensions/{extension-id}", extensionid: string): operation4096,
        (api: "/me/extensions/$count"): operation4097,
        (api: "/me/followedSites"): operation4098,
        (api: "/me/followedSites/{site-id}", siteid: string): operation4099,
        (api: "/me/followedSites/$count"): operation4100,
        (api: "/me/inferenceClassification"): operation4101,
        (api: "/me/inferenceClassification/overrides"): operation4102,
        (api: "/me/inferenceClassification/overrides/{inferenceClassificationOverride-id}", inferenceClassificationOverrideid: string): operation4103,
        (api: "/me/inferenceClassification/overrides/$count"): operation4104,
        (api: "/me/insights"): operation4105,
        (api: "/me/insights/shared"): operation4106,
        (api: "/me/insights/shared/{sharedInsight-id}", sharedInsightid: string): operation4107,
        (api: "/me/insights/shared/{sharedInsight-id}/lastSharedMethod", sharedInsightid: string): operation4108,
        (api: "/me/insights/shared/{sharedInsight-id}/resource", sharedInsightid: string): operation4109,
        (api: "/me/insights/shared/$count"): operation4110,
        (api: "/me/insights/trending"): operation4111,
        (api: "/me/insights/trending/{trending-id}", trendingid: string): operation4112,
        (api: "/me/insights/trending/{trending-id}/resource", trendingid: string): operation4113,
        (api: "/me/insights/trending/$count"): operation4114,
        (api: "/me/insights/used"): operation4115,
        (api: "/me/insights/used/{usedInsight-id}", usedInsightid: string): operation4116,
        (api: "/me/insights/used/{usedInsight-id}/resource", usedInsightid: string): operation4117,
        (api: "/me/insights/used/$count"): operation4118,
        (api: "/me/licenseDetails"): operation4253,
        (api: "/me/licenseDetails/{licenseDetails-id}", licenseDetailsid: string): operation4254,
        (api: "/me/licenseDetails/$count"): operation4255,

        (api: "/me/managedAppRegistrations"): operation4340,
        (api: "/me/managedAppRegistrations/{managedAppRegistration-id}", managedAppRegistrationid: string): operation4341,
        (api: "/me/managedAppRegistrations/$count"): operation4342,
        (api: "/me/managedDevices"): operation4343,
        (api: "/me/managedDevices/{managedDevice-id}", managedDeviceid: string): operation4344,
        (api: "/me/managedDevices/{managedDevice-id}/deviceCategory", managedDeviceid: string): operation4345,
        (api: "/me/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates", managedDeviceid: string): operation4346,
        (api: "/me/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/{deviceCompliancePolicyState-id}", managedDeviceid: string, deviceCompliancePolicyStateid: string): operation4347,
        (api: "/me/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/$count", managedDeviceid: string): operation4348,
        (api: "/me/managedDevices/{managedDevice-id}/deviceConfigurationStates", managedDeviceid: string): operation4349,
        (api: "/me/managedDevices/{managedDevice-id}/deviceConfigurationStates/{deviceConfigurationState-id}", managedDeviceid: string, deviceConfigurationStateid: string): operation4350,
        (api: "/me/managedDevices/{managedDevice-id}/deviceConfigurationStates/$count", managedDeviceid: string): operation4351,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.bypassActivationLock", managedDeviceid: string): operation4352,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.cleanWindowsDevice", managedDeviceid: string): operation4353,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.deleteUserFromSharedAppleDevice", managedDeviceid: string): operation4354,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.disableLostMode", managedDeviceid: string): operation4355,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.locateDevice", managedDeviceid: string): operation4356,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.logoutSharedAppleDeviceActiveUser", managedDeviceid: string): operation4357,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.rebootNow", managedDeviceid: string): operation4358,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.recoverPasscode", managedDeviceid: string): operation4359,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.remoteLock", managedDeviceid: string): operation4360,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.requestRemoteAssistance", managedDeviceid: string): operation4361,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.resetPasscode", managedDeviceid: string): operation4362,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.retire", managedDeviceid: string): operation4363,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.shutDown", managedDeviceid: string): operation4364,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.syncDevice", managedDeviceid: string): operation4365,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.updateWindowsDeviceAccount", managedDeviceid: string): operation4366,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderScan", managedDeviceid: string): operation4367,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderUpdateSignatures", managedDeviceid: string): operation4368,
        (api: "/me/managedDevices/{managedDevice-id}/microsoft.graph.wipe", managedDeviceid: string): operation4369,
        (api: "/me/managedDevices/$count"): operation4370,
        (api: "/me/manager"): operation4371,
        (api: "/me/manager/$ref"): operation4372,
        (api: "/me/memberOf"): operation4373,
        (api: "/me/memberOf/{directoryObject-id}", directoryObjectid: string): operation4374,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.application", directoryObjectid: string): operation4375,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.device", directoryObjectid: string): operation4376,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.group", directoryObjectid: string): operation4377,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.orgContact", directoryObjectid: string): operation4378,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.servicePrincipal", directoryObjectid: string): operation4379,
        (api: "/me/memberOf/{directoryObject-id}/microsoft.graph.user", directoryObjectid: string): operation4380,
        (api: "/me/memberOf/$count"): operation4381,
        (api: "/me/memberOf/microsoft.graph.application"): operation4382,
        (api: "/me/memberOf/microsoft.graph.application/$count"): operation4383,
        (api: "/me/memberOf/microsoft.graph.device"): operation4384,
        (api: "/me/memberOf/microsoft.graph.device/$count"): operation4385,
        (api: "/me/memberOf/microsoft.graph.group"): operation4386,
        (api: "/me/memberOf/microsoft.graph.group/$count"): operation4387,
        (api: "/me/memberOf/microsoft.graph.orgContact"): operation4388,
        (api: "/me/memberOf/microsoft.graph.orgContact/$count"): operation4389,
        (api: "/me/memberOf/microsoft.graph.servicePrincipal"): operation4390,
        (api: "/me/memberOf/microsoft.graph.servicePrincipal/$count"): operation4391,
        (api: "/me/memberOf/microsoft.graph.user"): operation4392,
        (api: "/me/memberOf/microsoft.graph.user/$count"): operation4393,
        (api: "/me/microsoft.graph.assignLicense"): operation4421,
        (api: "/me/microsoft.graph.changePassword"): operation4422,
        (api: "/me/microsoft.graph.checkMemberGroups"): operation4423,
        (api: "/me/microsoft.graph.checkMemberObjects"): operation4424,
        (api: "/me/microsoft.graph.exportPersonalData"): operation4425,
        (api: "/me/microsoft.graph.findMeetingTimes"): operation4426,
        (api: "/me/microsoft.graph.getMailTips"): operation4427,
        (api: "/me/microsoft.graph.getManagedAppDiagnosticStatuses()"): operation4428,
        (api: "/me/microsoft.graph.getManagedAppPolicies()"): operation4429,
        (api: "/me/microsoft.graph.getMemberGroups"): operation4430,
        (api: "/me/microsoft.graph.getMemberObjects"): operation4431,
        (api: "/me/microsoft.graph.reminderView(StartDateTime='{StartDateTime}',EndDateTime='{EndDateTime}')", StartDateTime: string, EndDateTime: string): operation4432,
        (api: "/me/microsoft.graph.removeAllDevicesFromManagement"): operation4433,
        (api: "/me/microsoft.graph.reprocessLicenseAssignment"): operation4434,
        (api: "/me/microsoft.graph.restore"): operation4435,
        (api: "/me/microsoft.graph.revokeSignInSessions"): operation4436,
        (api: "/me/microsoft.graph.sendMail"): operation4437,
        (api: "/me/microsoft.graph.translateExchangeIds"): operation4438,
        (api: "/me/microsoft.graph.wipeManagedAppRegistrationsByDeviceTag"): operation4439,
        (api: "/me/oauth2PermissionGrants"): operation4440,
        (api: "/me/oauth2PermissionGrants/{oAuth2PermissionGrant-id}", oAuth2PermissionGrantid: string): operation4441,
        (api: "/me/oauth2PermissionGrants/$count"): operation4442,

        (api: "/me/onlineMeetings"): operation4546,
        (api: "/me/onlineMeetings/{onlineMeeting-id}", onlineMeetingid: string): operation4547,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports", onlineMeetingid: string): operation4548,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}", onlineMeetingid: string, meetingAttendanceReportid: string): operation4549,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords", onlineMeetingid: string, meetingAttendanceReportid: string): operation4550,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/{attendanceRecord-id}", onlineMeetingid: string, meetingAttendanceReportid: string, attendanceRecordid: string): operation4551,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/$count", onlineMeetingid: string, meetingAttendanceReportid: string): operation4552,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendanceReports/$count", onlineMeetingid: string): operation4553,
        (api: "/me/onlineMeetings/{onlineMeeting-id}/attendeeReport", onlineMeetingid: string): operation4554,
        (api: "/me/onlineMeetings/$count"): operation4555,
        (api: "/me/onlineMeetings/microsoft.graph.createOrGet"): operation4556,
        (api: "/me/outlook"): operation4557,

        (api: "/me/outlook/microsoft.graph.supportedLanguages()"): operation4561,
        (api: "/me/outlook/microsoft.graph.supportedTimeZones()"): operation4562,
        (api: "/me/outlook/microsoft.graph.supportedTimeZones(TimeZoneStandard='{TimeZoneStandard}')", TimeZoneStandard: string): operation4563,
        (api: "/me/ownedDevices"): operation4564,
        (api: "/me/ownedDevices/{directoryObject-id}", directoryObjectid: string): operation4565,
        (api: "/me/ownedDevices/{directoryObject-id}/microsoft.graph.appRoleAssignment", directoryObjectid: string): operation4566,
        (api: "/me/ownedDevices/{directoryObject-id}/microsoft.graph.device", directoryObjectid: string): operation4567,
        (api: "/me/ownedDevices/{directoryObject-id}/microsoft.graph.endpoint", directoryObjectid: string): operation4568,
        (api: "/me/ownedDevices/$count"): operation4569,
        (api: "/me/ownedDevices/microsoft.graph.appRoleAssignment"): operation4570,
        (api: "/me/ownedDevices/microsoft.graph.appRoleAssignment/$count"): operation4571,
        (api: "/me/ownedDevices/microsoft.graph.device"): operation4572,
        (api: "/me/ownedDevices/microsoft.graph.device/$count"): operation4573,
        (api: "/me/ownedDevices/microsoft.graph.endpoint"): operation4574,
        (api: "/me/ownedDevices/microsoft.graph.endpoint/$count"): operation4575,
        (api: "/me/ownedObjects"): operation4576,
        (api: "/me/ownedObjects/{directoryObject-id}", directoryObjectid: string): operation4577,
        (api: "/me/ownedObjects/{directoryObject-id}/microsoft.graph.application", directoryObjectid: string): operation4578,
        (api: "/me/ownedObjects/{directoryObject-id}/microsoft.graph.group", directoryObjectid: string): operation4579,
        (api: "/me/ownedObjects/{directoryObject-id}/microsoft.graph.servicePrincipal", directoryObjectid: string): operation4580,
        (api: "/me/ownedObjects/$count"): operation4581,
        (api: "/me/ownedObjects/microsoft.graph.application"): operation4582,
        (api: "/me/ownedObjects/microsoft.graph.application/$count"): operation4583,
        (api: "/me/ownedObjects/microsoft.graph.group"): operation4584,
        (api: "/me/ownedObjects/microsoft.graph.group/$count"): operation4585,
        (api: "/me/ownedObjects/microsoft.graph.servicePrincipal"): operation4586,
        (api: "/me/ownedObjects/microsoft.graph.servicePrincipal/$count"): operation4587,
        (api: "/me/people"): operation4588,
        (api: "/me/people/{person-id}", personid: string): operation4589,
        (api: "/me/people/$count"): operation4590,
        (api: "/me/photo"): operation4591,
        (api: "/me/photo/$value"): operation4592,
        (api: "/me/photos"): operation4593,
        (api: "/me/photos/{profilePhoto-id}", profilePhotoid: string): operation4594,
        (api: "/me/photos/{profilePhoto-id}/$value", profilePhotoid: string): operation4595,
        (api: "/me/photos/$count"): operation4596,

        (api: "/me/presence"): operation4626,
        (api: "/me/presence/microsoft.graph.clearPresence"): operation4627,
        (api: "/me/presence/microsoft.graph.clearUserPreferredPresence"): operation4628,
        (api: "/me/presence/microsoft.graph.setPresence"): operation4629,
        (api: "/me/presence/microsoft.graph.setUserPreferredPresence"): operation4630,
        (api: "/me/registeredDevices"): operation4631,
        (api: "/me/registeredDevices/{directoryObject-id}", directoryObjectid: string): operation4632,
        (api: "/me/registeredDevices/{directoryObject-id}/microsoft.graph.appRoleAssignment", directoryObjectid: string): operation4633,
        (api: "/me/registeredDevices/{directoryObject-id}/microsoft.graph.device", directoryObjectid: string): operation4634,
        (api: "/me/registeredDevices/{directoryObject-id}/microsoft.graph.endpoint", directoryObjectid: string): operation4635,
        (api: "/me/registeredDevices/$count"): operation4636,
        (api: "/me/registeredDevices/microsoft.graph.appRoleAssignment"): operation4637,
        (api: "/me/registeredDevices/microsoft.graph.appRoleAssignment/$count"): operation4638,
        (api: "/me/registeredDevices/microsoft.graph.device"): operation4639,
        (api: "/me/registeredDevices/microsoft.graph.device/$count"): operation4640,
        (api: "/me/registeredDevices/microsoft.graph.endpoint"): operation4641,
        (api: "/me/registeredDevices/microsoft.graph.endpoint/$count"): operation4642,
        (api: "/me/scopedRoleMemberOf"): operation4643,
        (api: "/me/scopedRoleMemberOf/{scopedRoleMembership-id}", scopedRoleMembershipid: string): operation4644,
        (api: "/me/scopedRoleMemberOf/$count"): operation4645,
        (api: "/me/settings"): operation4646,
        (api: "/me/settings/shiftPreferences"): operation4647,
        (api: "/me/teamwork"): operation4648,
        (api: "/me/teamwork/associatedTeams"): operation4649,
        (api: "/me/teamwork/associatedTeams/{associatedTeamInfo-id}", associatedTeamInfoid: string): operation4650,
        (api: "/me/teamwork/associatedTeams/$count"): operation4651,
        (api: "/me/teamwork/installedApps"): operation4652,
        (api: "/me/teamwork/installedApps/{userScopeTeamsAppInstallation-id}", userScopeTeamsAppInstallationid: string): operation4653,
        (api: "/me/teamwork/installedApps/{userScopeTeamsAppInstallation-id}/chat", userScopeTeamsAppInstallationid: string): operation4654,
        (api: "/me/teamwork/installedApps/$count"): operation4655,
        (api: "/me/teamwork/microsoft.graph.sendActivityNotification"): operation4656,

        (api: "/me/transitiveMemberOf"): operation4687,
        (api: "/me/transitiveMemberOf/{directoryObject-id}", directoryObjectid: string): operation4688,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.application", directoryObjectid: string): operation4689,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.device", directoryObjectid: string): operation4690,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.group", directoryObjectid: string): operation4691,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.orgContact", directoryObjectid: string): operation4692,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.servicePrincipal", directoryObjectid: string): operation4693,
        (api: "/me/transitiveMemberOf/{directoryObject-id}/microsoft.graph.user", directoryObjectid: string): operation4694,
        (api: "/me/transitiveMemberOf/$count"): operation4695,
        (api: "/me/transitiveMemberOf/microsoft.graph.application"): operation4696,
        (api: "/me/transitiveMemberOf/microsoft.graph.application/$count"): operation4697,
        (api: "/me/transitiveMemberOf/microsoft.graph.device"): operation4698,
        (api: "/me/transitiveMemberOf/microsoft.graph.device/$count"): operation4699,
        (api: "/me/transitiveMemberOf/microsoft.graph.group"): operation4700,
        (api: "/me/transitiveMemberOf/microsoft.graph.group/$count"): operation4701,
        (api: "/me/transitiveMemberOf/microsoft.graph.orgContact"): operation4702,
        (api: "/me/transitiveMemberOf/microsoft.graph.orgContact/$count"): operation4703,
        (api: "/me/transitiveMemberOf/microsoft.graph.servicePrincipal"): operation4704,
        (api: "/me/transitiveMemberOf/microsoft.graph.servicePrincipal/$count"): operation4705,
        (api: "/me/transitiveMemberOf/microsoft.graph.user"): operation4706,
        (api: "/me/transitiveMemberOf/microsoft.graph.user/$count"): operation4707,

    }
}

export { };