import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation1247, operation1248, operation1249, operation1250, operation1251, operation1252, operation1253, operation1254, operation1255, operation1256, operation1257, operation1258, operation1259, operation1260, operation1261, operation1262, operation1263, operation1264, operation1265, operation1266, operation1267, operation1268, operation1269, operation1270, operation1271, operation1272, operation1273, operation1274, operation1275, operation1276, operation1277, operation1278, operation1279, operation1280, operation1281, operation1282, operation1283, operation1284, operation1285, operation1286, operation1287, operation1288, operation1289, operation1290, operation1291, operation1292, operation1293, operation1294, operation1295, operation1296, operation1297, operation1298, operation1299, operation1300, operation1301, operation1302, operation1303, operation1304, operation1305, operation1306, operation1307, operation1308, operation1309, operation1310, operation1311, operation1312, operation1313, operation1314, operation1315, operation1316, operation1317, operation1318, operation1319, operation1320, operation1321, operation1322, operation1323, operation1324, operation1325, operation1326, operation1327, operation1328, operation1329, operation1330, operation1331, operation1332, operation1333, operation1334, operation1335, operation1336, operation1337, operation1338, operation1339, operation1340, operation1341, operation1342, operation1343, operation1344, operation1345, operation1346, operation1347, operation1348, operation1349, operation1350, operation1351, operation1352, operation1353, operation1354, operation1355, operation1356, operation1357, operation1358, operation1359, operation1360, operation1361, operation1362, operation1363, operation1364, operation1365, operation1366, operation1367, operation1368, operation1369, operation1370, operation1371, operation1372, operation1373, operation1374, operation1375, operation1376, operation1377, operation1378, operation1379, operation1380, operation1381, operation1382, operation1383, operation1384, operation1385, operation1386, operation1387, operation1388, operation1389, operation1390, operation1391, operation1392, operation1393, operation1394, operation1395, operation1396, operation1397, operation1398, operation1399, operation1400, operation1401, operation1402, operation1403, operation1404, operation1405, operation1406, operation1407, operation1408, operation1409, operation1410, operation1411, operation1412 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/education"):operation1247,
    (api:"/education/classes"):operation1248,
    (api:"/education/classes/{educationClass-id}",educationClassid: string):operation1249,
    (api:"/education/classes/{educationClass-id}/assignmentCategories",educationClassid: string):operation1250,
    (api:"/education/classes/{educationClass-id}/assignmentCategories/{educationCategory-id}",educationClassid: string,educationCategoryid: string):operation1251,
    (api:"/education/classes/{educationClass-id}/assignmentCategories/$count",educationClassid: string):operation1252,
    (api:"/education/classes/{educationClass-id}/assignmentCategories/microsoft.graph.delta()",educationClassid: string):operation1253,
    (api:"/education/classes/{educationClass-id}/assignmentDefaults",educationClassid: string):operation1254,
    (api:"/education/classes/{educationClass-id}/assignments",educationClassid: string):operation1255,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}",educationClassid: string,educationAssignmentid: string):operation1256,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/categories",educationClassid: string,educationAssignmentid: string):operation1257,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/categories/{educationCategory-id}/$ref",educationClassid: string,educationAssignmentid: string,educationCategoryid: string):operation1258,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/categories/$count",educationClassid: string,educationAssignmentid: string):operation1259,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/categories/$ref",educationClassid: string,educationAssignmentid: string):operation1260,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/categories/microsoft.graph.delta()",educationClassid: string,educationAssignmentid: string):operation1261,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/microsoft.graph.publish",educationClassid: string,educationAssignmentid: string):operation1262,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/microsoft.graph.setUpResourcesFolder",educationClassid: string,educationAssignmentid: string):operation1263,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/resources",educationClassid: string,educationAssignmentid: string):operation1264,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/resources/{educationAssignmentResource-id}",educationClassid: string,educationAssignmentid: string,educationAssignmentResourceid: string):operation1265,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/resources/$count",educationClassid: string,educationAssignmentid: string):operation1266,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/rubric",educationClassid: string,educationAssignmentid: string):operation1267,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/rubric/$ref",educationClassid: string,educationAssignmentid: string):operation1268,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions",educationClassid: string,educationAssignmentid: string):operation1269,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1270,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.reassign",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1271,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.return",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1272,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.setUpResourcesFolder",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1273,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.submit",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1274,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.unsubmit",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1275,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1276,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/{educationOutcome-id}",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string,educationOutcomeid: string):operation1277,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/$count",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1278,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1279,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/{educationSubmissionResource-id}",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1280,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/$count",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1281,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1282,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/{educationSubmissionResource-id}",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1283,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/$count",educationClassid: string,educationAssignmentid: string,educationSubmissionid: string):operation1284,
    (api:"/education/classes/{educationClass-id}/assignments/{educationAssignment-id}/submissions/$count",educationClassid: string,educationAssignmentid: string):operation1285,
    (api:"/education/classes/{educationClass-id}/assignments/$count",educationClassid: string):operation1286,
    (api:"/education/classes/{educationClass-id}/assignments/microsoft.graph.delta()",educationClassid: string):operation1287,
    (api:"/education/classes/{educationClass-id}/assignmentSettings",educationClassid: string):operation1288,
    (api:"/education/classes/{educationClass-id}/group",educationClassid: string):operation1289,
    (api:"/education/classes/{educationClass-id}/members",educationClassid: string):operation1290,
    (api:"/education/classes/{educationClass-id}/members/{educationUser-id}/$ref",educationClassid: string,educationUserid: string):operation1291,
    (api:"/education/classes/{educationClass-id}/members/$count",educationClassid: string):operation1292,
    (api:"/education/classes/{educationClass-id}/members/$ref",educationClassid: string):operation1293,
    (api:"/education/classes/{educationClass-id}/schools",educationClassid: string):operation1294,
    (api:"/education/classes/{educationClass-id}/schools/{educationSchool-id}",educationClassid: string,educationSchoolid: string):operation1295,
    (api:"/education/classes/{educationClass-id}/schools/$count",educationClassid: string):operation1296,
    (api:"/education/classes/{educationClass-id}/teachers",educationClassid: string):operation1297,
    (api:"/education/classes/{educationClass-id}/teachers/{educationUser-id}/$ref",educationClassid: string,educationUserid: string):operation1298,
    (api:"/education/classes/{educationClass-id}/teachers/$count",educationClassid: string):operation1299,
    (api:"/education/classes/{educationClass-id}/teachers/$ref",educationClassid: string):operation1300,
    (api:"/education/classes/$count"):operation1301,
    (api:"/education/classes/microsoft.graph.delta()"):operation1302,
    (api:"/education/me"):operation1303,
    (api:"/education/me/assignments"):operation1304,
    (api:"/education/me/assignments/{educationAssignment-id}",educationAssignmentid: string):operation1305,
    (api:"/education/me/assignments/{educationAssignment-id}/categories",educationAssignmentid: string):operation1306,
    (api:"/education/me/assignments/{educationAssignment-id}/categories/{educationCategory-id}/$ref",educationAssignmentid: string,educationCategoryid: string):operation1307,
    (api:"/education/me/assignments/{educationAssignment-id}/categories/$count",educationAssignmentid: string):operation1308,
    (api:"/education/me/assignments/{educationAssignment-id}/categories/$ref",educationAssignmentid: string):operation1309,
    (api:"/education/me/assignments/{educationAssignment-id}/categories/microsoft.graph.delta()",educationAssignmentid: string):operation1310,
    (api:"/education/me/assignments/{educationAssignment-id}/microsoft.graph.publish",educationAssignmentid: string):operation1311,
    (api:"/education/me/assignments/{educationAssignment-id}/microsoft.graph.setUpResourcesFolder",educationAssignmentid: string):operation1312,
    (api:"/education/me/assignments/{educationAssignment-id}/resources",educationAssignmentid: string):operation1313,
    (api:"/education/me/assignments/{educationAssignment-id}/resources/{educationAssignmentResource-id}",educationAssignmentid: string,educationAssignmentResourceid: string):operation1314,
    (api:"/education/me/assignments/{educationAssignment-id}/resources/$count",educationAssignmentid: string):operation1315,
    (api:"/education/me/assignments/{educationAssignment-id}/rubric",educationAssignmentid: string):operation1316,
    (api:"/education/me/assignments/{educationAssignment-id}/rubric/$ref",educationAssignmentid: string):operation1317,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions",educationAssignmentid: string):operation1318,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}",educationAssignmentid: string,educationSubmissionid: string):operation1319,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.reassign",educationAssignmentid: string,educationSubmissionid: string):operation1320,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.return",educationAssignmentid: string,educationSubmissionid: string):operation1321,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.setUpResourcesFolder",educationAssignmentid: string,educationSubmissionid: string):operation1322,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.submit",educationAssignmentid: string,educationSubmissionid: string):operation1323,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.unsubmit",educationAssignmentid: string,educationSubmissionid: string):operation1324,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes",educationAssignmentid: string,educationSubmissionid: string):operation1325,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/{educationOutcome-id}",educationAssignmentid: string,educationSubmissionid: string,educationOutcomeid: string):operation1326,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/$count",educationAssignmentid: string,educationSubmissionid: string):operation1327,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources",educationAssignmentid: string,educationSubmissionid: string):operation1328,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/{educationSubmissionResource-id}",educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1329,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/$count",educationAssignmentid: string,educationSubmissionid: string):operation1330,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources",educationAssignmentid: string,educationSubmissionid: string):operation1331,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/{educationSubmissionResource-id}",educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1332,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/$count",educationAssignmentid: string,educationSubmissionid: string):operation1333,
    (api:"/education/me/assignments/{educationAssignment-id}/submissions/$count",educationAssignmentid: string):operation1334,
    (api:"/education/me/assignments/$count"):operation1335,
    (api:"/education/me/assignments/microsoft.graph.delta()"):operation1336,
    (api:"/education/me/classes"):operation1337,
    (api:"/education/me/classes/{educationClass-id}",educationClassid: string):operation1338,
    (api:"/education/me/classes/$count"):operation1339,
    (api:"/education/me/rubrics"):operation1340,
    (api:"/education/me/rubrics/{educationRubric-id}",educationRubricid: string):operation1341,
    (api:"/education/me/rubrics/$count"):operation1342,
    (api:"/education/me/schools"):operation1343,
    (api:"/education/me/schools/{educationSchool-id}",educationSchoolid: string):operation1344,
    (api:"/education/me/schools/$count"):operation1345,
    (api:"/education/me/taughtClasses"):operation1346,
    (api:"/education/me/taughtClasses/{educationClass-id}",educationClassid: string):operation1347,
    (api:"/education/me/taughtClasses/$count"):operation1348,
    (api:"/education/me/user"):operation1349,
    (api:"/education/schools"):operation1350,
    (api:"/education/schools/{educationSchool-id}",educationSchoolid: string):operation1351,
    (api:"/education/schools/{educationSchool-id}/administrativeUnit",educationSchoolid: string):operation1352,
    (api:"/education/schools/{educationSchool-id}/classes",educationSchoolid: string):operation1353,
    (api:"/education/schools/{educationSchool-id}/classes/{educationClass-id}/$ref",educationSchoolid: string,educationClassid: string):operation1354,
    (api:"/education/schools/{educationSchool-id}/classes/$count",educationSchoolid: string):operation1355,
    (api:"/education/schools/{educationSchool-id}/classes/$ref",educationSchoolid: string):operation1356,
    (api:"/education/schools/{educationSchool-id}/users",educationSchoolid: string):operation1357,
    (api:"/education/schools/{educationSchool-id}/users/{educationUser-id}/$ref",educationSchoolid: string,educationUserid: string):operation1358,
    (api:"/education/schools/{educationSchool-id}/users/$count",educationSchoolid: string):operation1359,
    (api:"/education/schools/{educationSchool-id}/users/$ref",educationSchoolid: string):operation1360,
    (api:"/education/schools/$count"):operation1361,
    (api:"/education/schools/microsoft.graph.delta()"):operation1362,
    (api:"/education/users"):operation1363,
    (api:"/education/users/{educationUser-id}",educationUserid: string):operation1364,
    (api:"/education/users/{educationUser-id}/assignments",educationUserid: string):operation1365,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}",educationUserid: string,educationAssignmentid: string):operation1366,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/categories",educationUserid: string,educationAssignmentid: string):operation1367,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/categories/{educationCategory-id}/$ref",educationUserid: string,educationAssignmentid: string,educationCategoryid: string):operation1368,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/categories/$count",educationUserid: string,educationAssignmentid: string):operation1369,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/categories/$ref",educationUserid: string,educationAssignmentid: string):operation1370,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/categories/microsoft.graph.delta()",educationUserid: string,educationAssignmentid: string):operation1371,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/microsoft.graph.publish",educationUserid: string,educationAssignmentid: string):operation1372,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/microsoft.graph.setUpResourcesFolder",educationUserid: string,educationAssignmentid: string):operation1373,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/resources",educationUserid: string,educationAssignmentid: string):operation1374,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/resources/{educationAssignmentResource-id}",educationUserid: string,educationAssignmentid: string,educationAssignmentResourceid: string):operation1375,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/resources/$count",educationUserid: string,educationAssignmentid: string):operation1376,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/rubric",educationUserid: string,educationAssignmentid: string):operation1377,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/rubric/$ref",educationUserid: string,educationAssignmentid: string):operation1378,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions",educationUserid: string,educationAssignmentid: string):operation1379,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1380,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.reassign",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1381,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.return",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1382,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.setUpResourcesFolder",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1383,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.submit",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1384,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/microsoft.graph.unsubmit",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1385,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1386,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/{educationOutcome-id}",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string,educationOutcomeid: string):operation1387,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/outcomes/$count",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1388,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1389,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/{educationSubmissionResource-id}",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1390,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/resources/$count",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1391,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1392,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/{educationSubmissionResource-id}",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string,educationSubmissionResourceid: string):operation1393,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/{educationSubmission-id}/submittedResources/$count",educationUserid: string,educationAssignmentid: string,educationSubmissionid: string):operation1394,
    (api:"/education/users/{educationUser-id}/assignments/{educationAssignment-id}/submissions/$count",educationUserid: string,educationAssignmentid: string):operation1395,
    (api:"/education/users/{educationUser-id}/assignments/$count",educationUserid: string):operation1396,
    (api:"/education/users/{educationUser-id}/assignments/microsoft.graph.delta()",educationUserid: string):operation1397,
    (api:"/education/users/{educationUser-id}/classes",educationUserid: string):operation1398,
    (api:"/education/users/{educationUser-id}/classes/{educationClass-id}",educationUserid: string,educationClassid: string):operation1399,
    (api:"/education/users/{educationUser-id}/classes/$count",educationUserid: string):operation1400,
    (api:"/education/users/{educationUser-id}/rubrics",educationUserid: string):operation1401,
    (api:"/education/users/{educationUser-id}/rubrics/{educationRubric-id}",educationUserid: string,educationRubricid: string):operation1402,
    (api:"/education/users/{educationUser-id}/rubrics/$count",educationUserid: string):operation1403,
    (api:"/education/users/{educationUser-id}/schools",educationUserid: string):operation1404,
    (api:"/education/users/{educationUser-id}/schools/{educationSchool-id}",educationUserid: string,educationSchoolid: string):operation1405,
    (api:"/education/users/{educationUser-id}/schools/$count",educationUserid: string):operation1406,
    (api:"/education/users/{educationUser-id}/taughtClasses",educationUserid: string):operation1407,
    (api:"/education/users/{educationUser-id}/taughtClasses/{educationClass-id}",educationUserid: string,educationClassid: string):operation1408,
    (api:"/education/users/{educationUser-id}/taughtClasses/$count",educationUserid: string):operation1409,
    (api:"/education/users/{educationUser-id}/user",educationUserid: string):operation1410,
    (api:"/education/users/$count"):operation1411,
    (api:"/education/users/microsoft.graph.delta()"):operation1412,

    }
}
export {};