import { GraphApis } from "../lib/src/rest/graphAPIs";

import { operation1, operation10, operation11, operation12, operation13, operation14, operation15, operation16, operation17, operation18, operation19, operation2, operation20, operation21, operation22, operation23, operation24, operation25, operation26, operation27, operation3, operation336, operation337, operation338, operation339, operation340, operation341, operation342, operation343, operation344, operation345, operation346, operation347, operation348, operation349, operation350, operation351, operation352, operation353, operation354, operation355, operation356, operation357, operation358, operation359, operation360, operation361, operation362, operation363, operation364, operation365, operation366, operation367, operation368, operation369, operation370, operation371, operation372, operation373, operation374, operation375, operation376, operation377, operation378, operation379, operation380, operation381, operation382, operation383, operation384, operation385, operation386, operation387, operation388, operation389, operation390, operation391, operation392, operation393, operation394, operation395, operation396, operation397, operation398, operation399, operation4, operation400, operation401, operation402, operation403, operation404, operation405, operation406, operation407, operation408, operation409, operation410, operation411, operation412, operation413, operation414, operation415, operation416, operation417, operation418, operation419, operation420, operation421, operation422, operation423, operation424, operation425, operation426, operation427, operation428, operation429, operation430, operation431, operation432, operation433, operation434, operation435, operation436, operation437, operation438, operation439, operation440, operation441, operation442, operation443, operation444, operation445, operation446, operation447, operation448, operation449, operation450, operation451, operation452, operation453, operation454, operation455, operation456, operation457, operation458, operation459, operation460, operation461, operation462, operation463, operation464, operation465, operation466, operation467, operation468, operation469, operation470, operation471, operation472, operation473, operation474, operation475, operation476, operation477, operation478, operation479, operation480, operation481, operation482, operation483, operation484, operation485, operation486, operation4860, operation4861, operation4862, operation4863, operation4864, operation4865, operation4866, operation4867, operation4868, operation4869, operation487, operation4870, operation4871, operation4872, operation4873, operation4874, operation4875, operation4876, operation4877, operation4878, operation4879, operation488, operation4880, operation4881, operation4882, operation4883, operation4884, operation4885, operation4886, operation4887, operation4888, operation4889, operation489, operation4890, operation4891, operation4892, operation4893, operation4894, operation4895, operation4896, operation4897, operation4898, operation4899, operation490, operation4900, operation4901, operation4902, operation4903, operation4904, operation4905, operation4906, operation4907, operation491, operation492, operation493, operation494, operation495, operation496, operation497, operation498, operation499, operation5, operation500, operation501, operation502, operation503, operation504, operation505, operation506, operation507, operation508, operation509, operation510, operation511, operation512, operation513, operation514, operation515, operation516, operation517, operation518, operation519, operation520, operation521, operation522, operation523, operation524, operation525, operation526, operation527, operation528, operation529, operation530, operation531, operation532, operation533, operation534, operation535, operation536, operation537, operation538, operation539, operation540, operation541, operation542, operation543, operation544, operation545, operation546, operation547, operation548, operation549, operation550, operation551, operation552, operation553, operation554, operation555, operation556, operation557, operation558, operation559, operation560, operation561, operation562, operation563, operation564, operation565, operation566, operation567, operation568, operation569, operation570, operation571, operation572, operation573, operation574, operation575, operation576, operation577, operation578, operation579, operation580, operation581, operation582, operation583, operation584, operation585, operation586, operation587, operation588, operation589, operation590, operation591, operation592, operation593, operation594, operation595, operation596, operation597, operation598, operation599, operation6, operation600, operation601, operation602, operation603, operation604, operation605, operation606, operation607, operation608, operation609, operation610, operation611, operation612, operation613, operation614, operation615, operation616, operation617, operation618, operation619, operation620, operation621, operation622, operation623, operation624, operation625, operation626, operation627, operation628, operation629, operation630, operation631, operation632, operation633, operation634, operation635, operation636, operation637, operation638, operation639, operation640, operation641, operation642, operation643, operation644, operation645, operation646, operation647, operation648, operation649, operation650, operation651, operation652, operation7, operation8, operation9 } from "../lib/src/rest/operations";

declare module "../lib/src/rest/graphAPIs" {
    export interface GraphApis {
        (api:"/deviceAppManagement"):operation336,
        (api:"/deviceAppManagement/androidManagedAppProtections"):operation337,
        (api:"/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtection-id}",androidManagedAppProtectionid: string):operation338,
        (api:"/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtection-id}/apps",androidManagedAppProtectionid: string):operation339,
        (api:"/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtection-id}/apps/{managedMobileApp-id}",androidManagedAppProtectionid: string,managedMobileAppid: string):operation340,
        (api:"/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtection-id}/apps/$count",androidManagedAppProtectionid: string):operation341,
        (api:"/deviceAppManagement/androidManagedAppProtections/{androidManagedAppProtection-id}/deploymentSummary",androidManagedAppProtectionid: string):operation342,
        (api:"/deviceAppManagement/androidManagedAppProtections/$count"):operation343,
        (api:"/deviceAppManagement/defaultManagedAppProtections"):operation344,
        (api:"/deviceAppManagement/defaultManagedAppProtections/{defaultManagedAppProtection-id}",defaultManagedAppProtectionid: string):operation345,
        (api:"/deviceAppManagement/defaultManagedAppProtections/{defaultManagedAppProtection-id}/apps",defaultManagedAppProtectionid: string):operation346,
        (api:"/deviceAppManagement/defaultManagedAppProtections/{defaultManagedAppProtection-id}/apps/{managedMobileApp-id}",defaultManagedAppProtectionid: string,managedMobileAppid: string):operation347,
        (api:"/deviceAppManagement/defaultManagedAppProtections/{defaultManagedAppProtection-id}/apps/$count",defaultManagedAppProtectionid: string):operation348,
        (api:"/deviceAppManagement/defaultManagedAppProtections/{defaultManagedAppProtection-id}/deploymentSummary",defaultManagedAppProtectionid: string):operation349,
        (api:"/deviceAppManagement/defaultManagedAppProtections/$count"):operation350,
        (api:"/deviceAppManagement/iosManagedAppProtections"):operation351,
        (api:"/deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtection-id}",iosManagedAppProtectionid: string):operation352,
        (api:"/deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtection-id}/apps",iosManagedAppProtectionid: string):operation353,
        (api:"/deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtection-id}/apps/{managedMobileApp-id}",iosManagedAppProtectionid: string,managedMobileAppid: string):operation354,
        (api:"/deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtection-id}/apps/$count",iosManagedAppProtectionid: string):operation355,
        (api:"/deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtection-id}/deploymentSummary",iosManagedAppProtectionid: string):operation356,
        (api:"/deviceAppManagement/iosManagedAppProtections/$count"):operation357,
        (api:"/deviceAppManagement/managedAppPolicies"):operation358,
        (api:"/deviceAppManagement/managedAppPolicies/{managedAppPolicy-id}",managedAppPolicyid: string):operation359,
        (api:"/deviceAppManagement/managedAppPolicies/{managedAppPolicy-id}/microsoft.graph.targetApps",managedAppPolicyid: string):operation360,
        (api:"/deviceAppManagement/managedAppPolicies/$count"):operation361,
        (api:"/deviceAppManagement/managedAppRegistrations"):operation362,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}",managedAppRegistrationid: string):operation363,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/appliedPolicies",managedAppRegistrationid: string):operation364,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/appliedPolicies/{managedAppPolicy-id}",managedAppRegistrationid: string,managedAppPolicyid: string):operation365,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/appliedPolicies/{managedAppPolicy-id}/microsoft.graph.targetApps",managedAppRegistrationid: string,managedAppPolicyid: string):operation366,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/appliedPolicies/$count",managedAppRegistrationid: string):operation367,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/intendedPolicies",managedAppRegistrationid: string):operation368,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/intendedPolicies/{managedAppPolicy-id}",managedAppRegistrationid: string,managedAppPolicyid: string):operation369,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/intendedPolicies/{managedAppPolicy-id}/microsoft.graph.targetApps",managedAppRegistrationid: string,managedAppPolicyid: string):operation370,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/intendedPolicies/$count",managedAppRegistrationid: string):operation371,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/operations",managedAppRegistrationid: string):operation372,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/operations/{managedAppOperation-id}",managedAppRegistrationid: string,managedAppOperationid: string):operation373,
        (api:"/deviceAppManagement/managedAppRegistrations/{managedAppRegistration-id}/operations/$count",managedAppRegistrationid: string):operation374,
        (api:"/deviceAppManagement/managedAppRegistrations/$count"):operation375,
        (api:"/deviceAppManagement/managedAppRegistrations/microsoft.graph.getUserIdsWithFlaggedAppRegistration()"):operation376,
        (api:"/deviceAppManagement/managedAppStatuses"):operation377,
        (api:"/deviceAppManagement/managedAppStatuses/{managedAppStatus-id}",managedAppStatusid: string):operation378,
        (api:"/deviceAppManagement/managedAppStatuses/$count"):operation379,
        (api:"/deviceAppManagement/managedEBooks"):operation380,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}",managedEBookid: string):operation381,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/assignments",managedEBookid: string):operation382,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/assignments/{managedEBookAssignment-id}",managedEBookid: string,managedEBookAssignmentid: string):operation383,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/assignments/$count",managedEBookid: string):operation384,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/deviceStates",managedEBookid: string):operation385,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/deviceStates/{deviceInstallState-id}",managedEBookid: string,deviceInstallStateid: string):operation386,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/deviceStates/$count",managedEBookid: string):operation387,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/installSummary",managedEBookid: string):operation388,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/microsoft.graph.assign",managedEBookid: string):operation389,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary",managedEBookid: string):operation390,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary/{userInstallStateSummary-id}",managedEBookid: string,userInstallStateSummaryid: string):operation391,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary/{userInstallStateSummary-id}/deviceStates",managedEBookid: string,userInstallStateSummaryid: string):operation392,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary/{userInstallStateSummary-id}/deviceStates/{deviceInstallState-id}",managedEBookid: string,userInstallStateSummaryid: string,deviceInstallStateid: string):operation393,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary/{userInstallStateSummary-id}/deviceStates/$count",managedEBookid: string,userInstallStateSummaryid: string):operation394,
        (api:"/deviceAppManagement/managedEBooks/{managedEBook-id}/userStateSummary/$count",managedEBookid: string):operation395,
        (api:"/deviceAppManagement/managedEBooks/$count"):operation396,
        (api:"/deviceAppManagement/mdmWindowsInformationProtectionPolicies"):operation397,
        (api:"/deviceAppManagement/mdmWindowsInformationProtectionPolicies/{mdmWindowsInformationProtectionPolicy-id}",mdmWindowsInformationProtectionPolicyid: string):operation398,
        (api:"/deviceAppManagement/mdmWindowsInformationProtectionPolicies/$count"):operation399,
        (api:"/deviceAppManagement/microsoft.graph.syncMicrosoftStoreForBusinessApps"):operation400,
        (api:"/deviceAppManagement/mobileAppCategories"):operation401,
        (api:"/deviceAppManagement/mobileAppCategories/{mobileAppCategory-id}",mobileAppCategoryid: string):operation402,
        (api:"/deviceAppManagement/mobileAppCategories/$count"):operation403,
        (api:"/deviceAppManagement/mobileAppConfigurations"):operation404,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}",managedDeviceMobileAppConfigurationid: string):operation405,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/assignments",managedDeviceMobileAppConfigurationid: string):operation406,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/assignments/{managedDeviceMobileAppConfigurationAssignment-id}",managedDeviceMobileAppConfigurationid: string,managedDeviceMobileAppConfigurationAssignmentid: string):operation407,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/assignments/$count",managedDeviceMobileAppConfigurationid: string):operation408,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/deviceStatuses",managedDeviceMobileAppConfigurationid: string):operation409,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/deviceStatuses/{managedDeviceMobileAppConfigurationDeviceStatus-id}",managedDeviceMobileAppConfigurationid: string,managedDeviceMobileAppConfigurationDeviceStatusid: string):operation410,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/deviceStatuses/$count",managedDeviceMobileAppConfigurationid: string):operation411,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/deviceStatusSummary",managedDeviceMobileAppConfigurationid: string):operation412,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/microsoft.graph.assign",managedDeviceMobileAppConfigurationid: string):operation413,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/userStatuses",managedDeviceMobileAppConfigurationid: string):operation414,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/userStatuses/{managedDeviceMobileAppConfigurationUserStatus-id}",managedDeviceMobileAppConfigurationid: string,managedDeviceMobileAppConfigurationUserStatusid: string):operation415,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/userStatuses/$count",managedDeviceMobileAppConfigurationid: string):operation416,
        (api:"/deviceAppManagement/mobileAppConfigurations/{managedDeviceMobileAppConfiguration-id}/userStatusSummary",managedDeviceMobileAppConfigurationid: string):operation417,
        (api:"/deviceAppManagement/mobileAppConfigurations/$count"):operation418,
        (api:"/deviceAppManagement/mobileApps"):operation419,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}",mobileAppid: string):operation420,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/assignments",mobileAppid: string):operation421,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/assignments/{mobileAppAssignment-id}",mobileAppid: string,mobileAppAssignmentid: string):operation422,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/assignments/$count",mobileAppid: string):operation423,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/categories",mobileAppid: string):operation424,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/categories/{mobileAppCategory-id}",mobileAppid: string,mobileAppCategoryid: string):operation425,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/categories/$count",mobileAppid: string):operation426,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.assign",mobileAppid: string):operation427,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.managedMobileLobApp",mobileAppid: string):operation428,
        (api:"/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.mobileLobApp",mobileAppid: string):operation429,
        (api:"/deviceAppManagement/mobileApps/$count"):operation430,
        (api:"/deviceAppManagement/mobileApps/microsoft.graph.managedMobileLobApp"):operation431,
        (api:"/deviceAppManagement/mobileApps/microsoft.graph.managedMobileLobApp/$count"):operation432,
        (api:"/deviceAppManagement/mobileApps/microsoft.graph.mobileLobApp"):operation433,
        (api:"/deviceAppManagement/mobileApps/microsoft.graph.mobileLobApp/$count"):operation434,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations"):operation435,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}",targetedManagedAppConfigurationid: string):operation436,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/apps",targetedManagedAppConfigurationid: string):operation437,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/apps/{managedMobileApp-id}",targetedManagedAppConfigurationid: string,managedMobileAppid: string):operation438,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/apps/$count",targetedManagedAppConfigurationid: string):operation439,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/assignments",targetedManagedAppConfigurationid: string):operation440,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/assignments/{targetedManagedAppPolicyAssignment-id}",targetedManagedAppConfigurationid: string,targetedManagedAppPolicyAssignmentid: string):operation441,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/assignments/$count",targetedManagedAppConfigurationid: string):operation442,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/deploymentSummary",targetedManagedAppConfigurationid: string):operation443,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/microsoft.graph.assign",targetedManagedAppConfigurationid: string):operation444,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/{targetedManagedAppConfiguration-id}/microsoft.graph.targetApps",targetedManagedAppConfigurationid: string):operation445,
        (api:"/deviceAppManagement/targetedManagedAppConfigurations/$count"):operation446,
        (api:"/deviceAppManagement/vppTokens"):operation447,
        (api:"/deviceAppManagement/vppTokens/{vppToken-id}",vppTokenid: string):operation448,
        (api:"/deviceAppManagement/vppTokens/{vppToken-id}/microsoft.graph.syncLicenses",vppTokenid: string):operation449,
        (api:"/deviceAppManagement/vppTokens/$count"):operation450,
        (api:"/deviceAppManagement/windowsInformationProtectionPolicies"):operation451,
        (api:"/deviceAppManagement/windowsInformationProtectionPolicies/{windowsInformationProtectionPolicy-id}",windowsInformationProtectionPolicyid: string):operation452,
        (api:"/deviceAppManagement/windowsInformationProtectionPolicies/$count"):operation453,
        (api:"/deviceManagement"):operation454,
        (api:"/deviceManagement/applePushNotificationCertificate"):operation455,
        (api:"/deviceManagement/applePushNotificationCertificate/microsoft.graph.downloadApplePushNotificationCertificateSigningRequest()"):operation456,
        (api:"/deviceManagement/complianceManagementPartners"):operation457,
        (api:"/deviceManagement/complianceManagementPartners/{complianceManagementPartner-id}",complianceManagementPartnerid: string):operation458,
        (api:"/deviceManagement/complianceManagementPartners/$count"):operation459,
        (api:"/deviceManagement/conditionalAccessSettings"):operation460,
        (api:"/deviceManagement/detectedApps"):operation461,
        (api:"/deviceManagement/detectedApps/{detectedApp-id}",detectedAppid: string):operation462,
        (api:"/deviceManagement/detectedApps/{detectedApp-id}/managedDevices",detectedAppid: string):operation463,
        (api:"/deviceManagement/detectedApps/{detectedApp-id}/managedDevices/{managedDevice-id}",detectedAppid: string,managedDeviceid: string):operation464,
        (api:"/deviceManagement/detectedApps/{detectedApp-id}/managedDevices/$count",detectedAppid: string):operation465,
        (api:"/deviceManagement/detectedApps/$count"):operation466,
        (api:"/deviceManagement/deviceCategories"):operation467,
        (api:"/deviceManagement/deviceCategories/{deviceCategory-id}",deviceCategoryid: string):operation468,
        (api:"/deviceManagement/deviceCategories/$count"):operation469,
        (api:"/deviceManagement/deviceCompliancePolicies"):operation470,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}",deviceCompliancePolicyid: string):operation471,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/assignments",deviceCompliancePolicyid: string):operation472,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/assignments/{deviceCompliancePolicyAssignment-id}",deviceCompliancePolicyid: string,deviceCompliancePolicyAssignmentid: string):operation473,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/assignments/$count",deviceCompliancePolicyid: string):operation474,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceSettingStateSummaries",deviceCompliancePolicyid: string):operation475,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceSettingStateSummaries/{settingStateDeviceSummary-id}",deviceCompliancePolicyid: string,settingStateDeviceSummaryid: string):operation476,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceSettingStateSummaries/$count",deviceCompliancePolicyid: string):operation477,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceStatuses",deviceCompliancePolicyid: string):operation478,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceStatuses/{deviceComplianceDeviceStatus-id}",deviceCompliancePolicyid: string,deviceComplianceDeviceStatusid: string):operation479,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceStatuses/$count",deviceCompliancePolicyid: string):operation480,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/deviceStatusOverview",deviceCompliancePolicyid: string):operation481,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/microsoft.graph.assign",deviceCompliancePolicyid: string):operation482,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/microsoft.graph.scheduleActionsForRules",deviceCompliancePolicyid: string):operation483,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule",deviceCompliancePolicyid: string):operation484,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule/{deviceComplianceScheduledActionForRule-id}",deviceCompliancePolicyid: string,deviceComplianceScheduledActionForRuleid: string):operation485,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule/{deviceComplianceScheduledActionForRule-id}/scheduledActionConfigurations",deviceCompliancePolicyid: string,deviceComplianceScheduledActionForRuleid: string):operation486,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule/{deviceComplianceScheduledActionForRule-id}/scheduledActionConfigurations/{deviceComplianceActionItem-id}",deviceCompliancePolicyid: string,deviceComplianceScheduledActionForRuleid: string,deviceComplianceActionItemid: string):operation487,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule/{deviceComplianceScheduledActionForRule-id}/scheduledActionConfigurations/$count",deviceCompliancePolicyid: string,deviceComplianceScheduledActionForRuleid: string):operation488,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/scheduledActionsForRule/$count",deviceCompliancePolicyid: string):operation489,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/userStatuses",deviceCompliancePolicyid: string):operation490,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/userStatuses/{deviceComplianceUserStatus-id}",deviceCompliancePolicyid: string,deviceComplianceUserStatusid: string):operation491,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/userStatuses/$count",deviceCompliancePolicyid: string):operation492,
        (api:"/deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicy-id}/userStatusOverview",deviceCompliancePolicyid: string):operation493,
        (api:"/deviceManagement/deviceCompliancePolicies/$count"):operation494,
        (api:"/deviceManagement/deviceCompliancePolicyDeviceStateSummary"):operation495,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries"):operation496,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries/{deviceCompliancePolicySettingStateSummary-id}",deviceCompliancePolicySettingStateSummaryid: string):operation497,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries/{deviceCompliancePolicySettingStateSummary-id}/deviceComplianceSettingStates",deviceCompliancePolicySettingStateSummaryid: string):operation498,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries/{deviceCompliancePolicySettingStateSummary-id}/deviceComplianceSettingStates/{deviceComplianceSettingState-id}",deviceCompliancePolicySettingStateSummaryid: string,deviceComplianceSettingStateid: string):operation499,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries/{deviceCompliancePolicySettingStateSummary-id}/deviceComplianceSettingStates/$count",deviceCompliancePolicySettingStateSummaryid: string):operation500,
        (api:"/deviceManagement/deviceCompliancePolicySettingStateSummaries/$count"):operation501,
        (api:"/deviceManagement/deviceConfigurationDeviceStateSummaries"):operation502,
        (api:"/deviceManagement/deviceConfigurations"):operation503,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}",deviceConfigurationid: string):operation504,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/assignments",deviceConfigurationid: string):operation505,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/assignments/{deviceConfigurationAssignment-id}",deviceConfigurationid: string,deviceConfigurationAssignmentid: string):operation506,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/assignments/$count",deviceConfigurationid: string):operation507,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceSettingStateSummaries",deviceConfigurationid: string):operation508,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceSettingStateSummaries/{settingStateDeviceSummary-id}",deviceConfigurationid: string,settingStateDeviceSummaryid: string):operation509,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceSettingStateSummaries/$count",deviceConfigurationid: string):operation510,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceStatuses",deviceConfigurationid: string):operation511,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceStatuses/{deviceConfigurationDeviceStatus-id}",deviceConfigurationid: string,deviceConfigurationDeviceStatusid: string):operation512,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceStatuses/$count",deviceConfigurationid: string):operation513,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/deviceStatusOverview",deviceConfigurationid: string):operation514,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/microsoft.graph.assign",deviceConfigurationid: string):operation515,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/microsoft.graph.getOmaSettingPlainTextValue(secretReferenceValueId='{secretReferenceValueId}')",deviceConfigurationid: string,secretReferenceValueId: string):operation516,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/userStatuses",deviceConfigurationid: string):operation517,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/userStatuses/{deviceConfigurationUserStatus-id}",deviceConfigurationid: string,deviceConfigurationUserStatusid: string):operation518,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/userStatuses/$count",deviceConfigurationid: string):operation519,
        (api:"/deviceManagement/deviceConfigurations/{deviceConfiguration-id}/userStatusOverview",deviceConfigurationid: string):operation520,
        (api:"/deviceManagement/deviceConfigurations/$count"):operation521,
        (api:"/deviceManagement/deviceEnrollmentConfigurations"):operation522,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}",deviceEnrollmentConfigurationid: string):operation523,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/assignments",deviceEnrollmentConfigurationid: string):operation524,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/assignments/{enrollmentConfigurationAssignment-id}",deviceEnrollmentConfigurationid: string,enrollmentConfigurationAssignmentid: string):operation525,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/assignments/$count",deviceEnrollmentConfigurationid: string):operation526,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/microsoft.graph.assign",deviceEnrollmentConfigurationid: string):operation527,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/{deviceEnrollmentConfiguration-id}/microsoft.graph.setPriority",deviceEnrollmentConfigurationid: string):operation528,
        (api:"/deviceManagement/deviceEnrollmentConfigurations/$count"):operation529,
        (api:"/deviceManagement/deviceManagementPartners"):operation530,
        (api:"/deviceManagement/deviceManagementPartners/{deviceManagementPartner-id}",deviceManagementPartnerid: string):operation531,
        (api:"/deviceManagement/deviceManagementPartners/$count"):operation532,
        (api:"/deviceManagement/exchangeConnectors"):operation533,
        (api:"/deviceManagement/exchangeConnectors/{deviceManagementExchangeConnector-id}",deviceManagementExchangeConnectorid: string):operation534,
        (api:"/deviceManagement/exchangeConnectors/{deviceManagementExchangeConnector-id}/microsoft.graph.sync",deviceManagementExchangeConnectorid: string):operation535,
        (api:"/deviceManagement/exchangeConnectors/$count"):operation536,
        (api:"/deviceManagement/importedWindowsAutopilotDeviceIdentities"):operation537,
        (api:"/deviceManagement/importedWindowsAutopilotDeviceIdentities/{importedWindowsAutopilotDeviceIdentity-id}",importedWindowsAutopilotDeviceIdentityid: string):operation538,
        (api:"/deviceManagement/importedWindowsAutopilotDeviceIdentities/$count"):operation539,
        (api:"/deviceManagement/importedWindowsAutopilotDeviceIdentities/microsoft.graph.import"):operation540,
        (api:"/deviceManagement/iosUpdateStatuses"):operation541,
        (api:"/deviceManagement/iosUpdateStatuses/{iosUpdateDeviceStatus-id}",iosUpdateDeviceStatusid: string):operation542,
        (api:"/deviceManagement/iosUpdateStatuses/$count"):operation543,
        (api:"/deviceManagement/managedDeviceOverview"):operation544,
        (api:"/deviceManagement/managedDevices"):operation545,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}",managedDeviceid: string):operation546,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceCategory",managedDeviceid: string):operation547,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates",managedDeviceid: string):operation548,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/{deviceCompliancePolicyState-id}",managedDeviceid: string,deviceCompliancePolicyStateid: string):operation549,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceCompliancePolicyStates/$count",managedDeviceid: string):operation550,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceConfigurationStates",managedDeviceid: string):operation551,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceConfigurationStates/{deviceConfigurationState-id}",managedDeviceid: string,deviceConfigurationStateid: string):operation552,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/deviceConfigurationStates/$count",managedDeviceid: string):operation553,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.bypassActivationLock",managedDeviceid: string):operation554,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.cleanWindowsDevice",managedDeviceid: string):operation555,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.deleteUserFromSharedAppleDevice",managedDeviceid: string):operation556,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.disableLostMode",managedDeviceid: string):operation557,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.locateDevice",managedDeviceid: string):operation558,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.logoutSharedAppleDeviceActiveUser",managedDeviceid: string):operation559,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.rebootNow",managedDeviceid: string):operation560,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.recoverPasscode",managedDeviceid: string):operation561,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.remoteLock",managedDeviceid: string):operation562,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.requestRemoteAssistance",managedDeviceid: string):operation563,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.resetPasscode",managedDeviceid: string):operation564,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.retire",managedDeviceid: string):operation565,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.shutDown",managedDeviceid: string):operation566,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.syncDevice",managedDeviceid: string):operation567,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.updateWindowsDeviceAccount",managedDeviceid: string):operation568,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderScan",managedDeviceid: string):operation569,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.windowsDefenderUpdateSignatures",managedDeviceid: string):operation570,
        (api:"/deviceManagement/managedDevices/{managedDevice-id}/microsoft.graph.wipe",managedDeviceid: string):operation571,
        (api:"/deviceManagement/managedDevices/$count"):operation572,
        (api:"/deviceManagement/microsoft.graph.getEffectivePermissions(scope='{scope}')",scope: string):operation573,
        (api:"/deviceManagement/microsoft.graph.verifyWindowsEnrollmentAutoDiscovery(domainName='{domainName}')",domainName: string):operation574,
        (api:"/deviceManagement/mobileThreatDefenseConnectors"):operation575,
        (api:"/deviceManagement/mobileThreatDefenseConnectors/{mobileThreatDefenseConnector-id}",mobileThreatDefenseConnectorid: string):operation576,
        (api:"/deviceManagement/mobileThreatDefenseConnectors/$count"):operation577,
        (api:"/deviceManagement/notificationMessageTemplates"):operation578,
        (api:"/deviceManagement/notificationMessageTemplates/{notificationMessageTemplate-id}",notificationMessageTemplateid: string):operation579,
        (api:"/deviceManagement/notificationMessageTemplates/{notificationMessageTemplate-id}/localizedNotificationMessages",notificationMessageTemplateid: string):operation580,
        (api:"/deviceManagement/notificationMessageTemplates/{notificationMessageTemplate-id}/localizedNotificationMessages/{localizedNotificationMessage-id}",notificationMessageTemplateid: string,localizedNotificationMessageid: string):operation581,
        (api:"/deviceManagement/notificationMessageTemplates/{notificationMessageTemplate-id}/localizedNotificationMessages/$count",notificationMessageTemplateid: string):operation582,
        (api:"/deviceManagement/notificationMessageTemplates/{notificationMessageTemplate-id}/microsoft.graph.sendTestMessage",notificationMessageTemplateid: string):operation583,
        (api:"/deviceManagement/notificationMessageTemplates/$count"):operation584,
        (api:"/deviceManagement/remoteAssistancePartners"):operation585,
        (api:"/deviceManagement/remoteAssistancePartners/{remoteAssistancePartner-id}",remoteAssistancePartnerid: string):operation586,
        (api:"/deviceManagement/remoteAssistancePartners/{remoteAssistancePartner-id}/microsoft.graph.beginOnboarding",remoteAssistancePartnerid: string):operation587,
        (api:"/deviceManagement/remoteAssistancePartners/{remoteAssistancePartner-id}/microsoft.graph.disconnect",remoteAssistancePartnerid: string):operation588,
        (api:"/deviceManagement/remoteAssistancePartners/$count"):operation589,
        (api:"/deviceManagement/reports"):operation590,
        (api:"/deviceManagement/reports/exportJobs"):operation591,
        (api:"/deviceManagement/reports/exportJobs/{deviceManagementExportJob-id}",deviceManagementExportJobid: string):operation592,
        (api:"/deviceManagement/reports/exportJobs/$count"):operation593,
        (api:"/deviceManagement/reports/microsoft.graph.getCachedReport"):operation594,
        (api:"/deviceManagement/reports/microsoft.graph.getCompliancePolicyNonComplianceReport"):operation595,
        (api:"/deviceManagement/reports/microsoft.graph.getCompliancePolicyNonComplianceSummaryReport"):operation596,
        (api:"/deviceManagement/reports/microsoft.graph.getComplianceSettingNonComplianceReport"):operation597,
        (api:"/deviceManagement/reports/microsoft.graph.getConfigurationPolicyNonComplianceReport"):operation598,
        (api:"/deviceManagement/reports/microsoft.graph.getConfigurationPolicyNonComplianceSummaryReport"):operation599,
        (api:"/deviceManagement/reports/microsoft.graph.getConfigurationSettingNonComplianceReport"):operation600,
        (api:"/deviceManagement/reports/microsoft.graph.getDeviceManagementIntentPerSettingContributingProfiles"):operation601,
        (api:"/deviceManagement/reports/microsoft.graph.getDeviceManagementIntentSettingsReport"):operation602,
        (api:"/deviceManagement/reports/microsoft.graph.getDeviceNonComplianceReport"):operation603,
        (api:"/deviceManagement/reports/microsoft.graph.getHistoricalReport"):operation604,
        (api:"/deviceManagement/reports/microsoft.graph.getNoncompliantDevicesAndSettingsReport"):operation605,
        (api:"/deviceManagement/reports/microsoft.graph.getPolicyNonComplianceMetadata"):operation606,
        (api:"/deviceManagement/reports/microsoft.graph.getPolicyNonComplianceReport"):operation607,
        (api:"/deviceManagement/reports/microsoft.graph.getPolicyNonComplianceSummaryReport"):operation608,
        (api:"/deviceManagement/reports/microsoft.graph.getReportFilters"):operation609,
        (api:"/deviceManagement/reports/microsoft.graph.getSettingNonComplianceReport"):operation610,
        (api:"/deviceManagement/resourceOperations"):operation611,
        (api:"/deviceManagement/resourceOperations/{resourceOperation-id}",resourceOperationid: string):operation612,
        (api:"/deviceManagement/resourceOperations/$count"):operation613,
        (api:"/deviceManagement/roleAssignments"):operation614,
        (api:"/deviceManagement/roleAssignments/{deviceAndAppManagementRoleAssignment-id}",deviceAndAppManagementRoleAssignmentid: string):operation615,
        (api:"/deviceManagement/roleAssignments/$count"):operation616,
        (api:"/deviceManagement/roleDefinitions"):operation617,
        (api:"/deviceManagement/roleDefinitions/{roleDefinition-id}",roleDefinitionid: string):operation618,
        (api:"/deviceManagement/roleDefinitions/{roleDefinition-id}/roleAssignments",roleDefinitionid: string):operation619,
        (api:"/deviceManagement/roleDefinitions/{roleDefinition-id}/roleAssignments/{roleAssignment-id}",roleDefinitionid: string,roleAssignmentid: string):operation620,
        (api:"/deviceManagement/roleDefinitions/{roleDefinition-id}/roleAssignments/{roleAssignment-id}/roleDefinition",roleDefinitionid: string,roleAssignmentid: string):operation621,
        (api:"/deviceManagement/roleDefinitions/{roleDefinition-id}/roleAssignments/$count",roleDefinitionid: string):operation622,
        (api:"/deviceManagement/roleDefinitions/$count"):operation623,
        (api:"/deviceManagement/softwareUpdateStatusSummary"):operation624,
        (api:"/deviceManagement/telecomExpenseManagementPartners"):operation625,
        (api:"/deviceManagement/telecomExpenseManagementPartners/{telecomExpenseManagementPartner-id}",telecomExpenseManagementPartnerid: string):operation626,
        (api:"/deviceManagement/telecomExpenseManagementPartners/$count"):operation627,
        (api:"/deviceManagement/termsAndConditions"):operation628,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}",termsAndConditionsid: string):operation629,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/acceptanceStatuses",termsAndConditionsid: string):operation630,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/acceptanceStatuses/{termsAndConditionsAcceptanceStatus-id}",termsAndConditionsid: string,termsAndConditionsAcceptanceStatusid: string):operation631,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/acceptanceStatuses/{termsAndConditionsAcceptanceStatus-id}/termsAndConditions",termsAndConditionsid: string,termsAndConditionsAcceptanceStatusid: string):operation632,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/acceptanceStatuses/$count",termsAndConditionsid: string):operation633,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/assignments",termsAndConditionsid: string):operation634,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/assignments/{termsAndConditionsAssignment-id}",termsAndConditionsid: string,termsAndConditionsAssignmentid: string):operation635,
        (api:"/deviceManagement/termsAndConditions/{termsAndConditions-id}/assignments/$count",termsAndConditionsid: string):operation636,
        (api:"/deviceManagement/termsAndConditions/$count"):operation637,
        (api:"/deviceManagement/troubleshootingEvents"):operation638,
        (api:"/deviceManagement/troubleshootingEvents/{deviceManagementTroubleshootingEvent-id}",deviceManagementTroubleshootingEventid: string):operation639,
        (api:"/deviceManagement/troubleshootingEvents/$count"):operation640,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities"):operation641,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities/{windowsAutopilotDeviceIdentity-id}",windowsAutopilotDeviceIdentityid: string):operation642,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities/{windowsAutopilotDeviceIdentity-id}/microsoft.graph.assignUserToDevice",windowsAutopilotDeviceIdentityid: string):operation643,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities/{windowsAutopilotDeviceIdentity-id}/microsoft.graph.unassignUserFromDevice",windowsAutopilotDeviceIdentityid: string):operation644,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities/{windowsAutopilotDeviceIdentity-id}/microsoft.graph.updateDeviceProperties",windowsAutopilotDeviceIdentityid: string):operation645,
        (api:"/deviceManagement/windowsAutopilotDeviceIdentities/$count"):operation646,
        (api:"/deviceManagement/windowsInformationProtectionAppLearningSummaries"):operation647,
        (api:"/deviceManagement/windowsInformationProtectionAppLearningSummaries/{windowsInformationProtectionAppLearningSummary-id}",windowsInformationProtectionAppLearningSummaryid: string):operation648,
        (api:"/deviceManagement/windowsInformationProtectionAppLearningSummaries/$count"):operation649,
        (api:"/deviceManagement/windowsInformationProtectionNetworkLearningSummaries"):operation650,
        (api:"/deviceManagement/windowsInformationProtectionNetworkLearningSummaries/{windowsInformationProtectionNetworkLearningSummary-id}",windowsInformationProtectionNetworkLearningSummaryid: string):operation651,
        (api:"/deviceManagement/windowsInformationProtectionNetworkLearningSummaries/$count"):operation652,
        (api:"/admin"):operation1,
    (api:"/admin/serviceAnnouncement"):operation2,
    (api:"/admin/serviceAnnouncement/healthOverviews"):operation3,
    (api:"/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}",serviceHealthid: string):operation4,
    (api:"/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues",serviceHealthid: string):operation5,
    (api:"/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues/{serviceHealthIssue-id}",serviceHealthid: string,serviceHealthIssueid: string):operation6,
    (api:"/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues/{serviceHealthIssue-id}/microsoft.graph.incidentReport()",serviceHealthid: string,serviceHealthIssueid: string):operation7,
    (api:"/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues/$count",serviceHealthid: string):operation8,
    (api:"/admin/serviceAnnouncement/healthOverviews/$count"):operation9,
    (api:"/admin/serviceAnnouncement/issues"):operation10,
    (api:"/admin/serviceAnnouncement/issues/{serviceHealthIssue-id}",serviceHealthIssueid: string):operation11,
    (api:"/admin/serviceAnnouncement/issues/{serviceHealthIssue-id}/microsoft.graph.incidentReport()",serviceHealthIssueid: string):operation12,
    (api:"/admin/serviceAnnouncement/issues/$count"):operation13,
    (api:"/admin/serviceAnnouncement/messages"):operation14,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}",serviceUpdateMessageid: string):operation15,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}/attachments",serviceUpdateMessageid: string):operation16,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}/attachments/{serviceAnnouncementAttachment-id}",serviceUpdateMessageid: string,serviceAnnouncementAttachmentid: string):operation17,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}/attachments/{serviceAnnouncementAttachment-id}/content",serviceUpdateMessageid: string,serviceAnnouncementAttachmentid: string):operation18,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}/attachments/$count",serviceUpdateMessageid: string):operation19,
    (api:"/admin/serviceAnnouncement/messages/{serviceUpdateMessage-id}/attachmentsArchive",serviceUpdateMessageid: string):operation20,
    (api:"/admin/serviceAnnouncement/messages/$count"):operation21,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.archive"):operation22,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.favorite"):operation23,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.markRead"):operation24,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.markUnread"):operation25,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.unarchive"):operation26,
    (api:"/admin/serviceAnnouncement/messages/microsoft.graph.unfavorite"):operation27,

    (api:"/print"):operation4860,
    (api:"/print/connectors"):operation4861,
    (api:"/print/connectors/{printConnector-id}",printConnectorid: string):operation4862,
    (api:"/print/connectors/$count"):operation4863,
    (api:"/print/operations"):operation4864,
    (api:"/print/operations/{printOperation-id}",printOperationid: string):operation4865,
    (api:"/print/operations/$count"):operation4866,
    (api:"/print/printers"):operation4867,
    (api:"/print/printers/{printer-id}",printerid: string):operation4868,
    (api:"/print/printers/{printer-id}/connectors",printerid: string):operation4869,
    (api:"/print/printers/{printer-id}/connectors/{printConnector-id}",printerid: string,printConnectorid: string):operation4870,
    (api:"/print/printers/{printer-id}/connectors/$count",printerid: string):operation4871,
    (api:"/print/printers/{printer-id}/microsoft.graph.restoreFactoryDefaults",printerid: string):operation4872,
    (api:"/print/printers/{printer-id}/shares",printerid: string):operation4873,
    (api:"/print/printers/{printer-id}/shares/{printerShare-id}",printerid: string,printerShareid: string):operation4874,
    (api:"/print/printers/{printer-id}/shares/$count",printerid: string):operation4875,
    (api:"/print/printers/{printer-id}/taskTriggers",printerid: string):operation4876,
    (api:"/print/printers/{printer-id}/taskTriggers/{printTaskTrigger-id}",printerid: string,printTaskTriggerid: string):operation4877,
    (api:"/print/printers/{printer-id}/taskTriggers/{printTaskTrigger-id}/definition",printerid: string,printTaskTriggerid: string):operation4878,
    (api:"/print/printers/{printer-id}/taskTriggers/$count",printerid: string):operation4879,
    (api:"/print/printers/$count"):operation4880,
    (api:"/print/printers/microsoft.graph.create"):operation4881,
    (api:"/print/services"):operation4882,
    (api:"/print/services/{printService-id}",printServiceid: string):operation4883,
    (api:"/print/services/{printService-id}/endpoints",printServiceid: string):operation4884,
    (api:"/print/services/{printService-id}/endpoints/{printServiceEndpoint-id}",printServiceid: string,printServiceEndpointid: string):operation4885,
    (api:"/print/services/{printService-id}/endpoints/$count",printServiceid: string):operation4886,
    (api:"/print/services/$count"):operation4887,
    (api:"/print/shares"):operation4888,
    (api:"/print/shares/{printerShare-id}",printerShareid: string):operation4889,
    (api:"/print/shares/{printerShare-id}/allowedGroups",printerShareid: string):operation4890,
    (api:"/print/shares/{printerShare-id}/allowedGroups/{group-id}/$ref",printerShareid: string,groupid: string):operation4891,
    (api:"/print/shares/{printerShare-id}/allowedGroups/$count",printerShareid: string):operation4892,
    (api:"/print/shares/{printerShare-id}/allowedGroups/$ref",printerShareid: string):operation4893,
    (api:"/print/shares/{printerShare-id}/allowedUsers",printerShareid: string):operation4894,
    (api:"/print/shares/{printerShare-id}/allowedUsers/{user-id}/$ref",printerShareid: string,userid: string):operation4895,
    (api:"/print/shares/{printerShare-id}/allowedUsers/$count",printerShareid: string):operation4896,
    (api:"/print/shares/{printerShare-id}/allowedUsers/$ref",printerShareid: string):operation4897,
    (api:"/print/shares/{printerShare-id}/printer",printerShareid: string):operation4898,
    (api:"/print/shares/$count"):operation4899,
    (api:"/print/taskDefinitions"):operation4900,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}",printTaskDefinitionid: string):operation4901,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}/tasks",printTaskDefinitionid: string):operation4902,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}/tasks/{printTask-id}",printTaskDefinitionid: string,printTaskid: string):operation4903,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}/tasks/{printTask-id}/definition",printTaskDefinitionid: string,printTaskid: string):operation4904,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}/tasks/{printTask-id}/trigger",printTaskDefinitionid: string,printTaskid: string):operation4905,
    (api:"/print/taskDefinitions/{printTaskDefinition-id}/tasks/$count",printTaskDefinitionid: string):operation4906,
    (api:"/print/taskDefinitions/$count"):operation4907,

    }
}